#!/usr/bin/env bash
# Scans MainWindow.*.cs partials to help pick the next refactor target:
# still-generated-preview files (genuinely unreviewed) first, then everything
# by size. Run from anywhere; it locates the repo root itself.

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || {
    echo "Could not cd into script directory"
    pwd
    exit 1
}

if [[ -f ./terminal-helpers.sh ]]; then
    source ./terminal-helpers.sh
else
    heading() { echo; echo "=== $* ==="; }
    success() { echo "$*"; }
    fail() { echo; echo "ERROR: $*" >&2; exit 1; }
    copy_clean() {
        local file="$1"
        if command -v clip.exe >/dev/null 2>&1; then
            sed -r 's/\x1B\[[0-9;]*[A-Za-z]//g' "$file" | clip.exe
            return 0
        fi
        return 1
    }
fi

(
    set -euo pipefail

    OUTPUT="/tmp/mainwindow-next-candidate-scan.txt"
    MAINWINDOW_DIR="VintageStoryModManager/Views/MainWindow"

    {
        heading "Repository state"
        git status --short --branch

        heading "Largest remaining generated-preview MainWindow partials"

        python - "$MAINWINDOW_DIR" <<'PY'
from pathlib import Path
import re
import sys

mainwindow_dir = Path(sys.argv[1])

method_pattern = re.compile(
    r"(?ms)^ {4}"
    r"(?:private|protected|public|internal)\s+"
    r"(?:(?:static|async|sealed|override|virtual|partial|extern|new)\s+)*"
    r".*?"
    r"\b(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*"
    r"\([^;{}]*?\)\s*"
    r"(?:where\s+.*?)*\{"
)

rows = []

for path in sorted(mainwindow_dir.glob("MainWindow.*.cs")):
    text = path.read_text(encoding="utf-8", errors="replace")
    if "<auto-generated-preview>" not in text:
        continue

    methods = [match.group("name") for match in method_pattern.finditer(text)]
    line_count = len(text.splitlines())

    rows.append((line_count, len(methods), path, methods))

rows.sort(reverse=True, key=lambda row: (row[0], row[1], str(row[2])))

for line_count, method_count, path, methods in rows:
    print(f"{line_count:5} lines  {method_count:3} methods  {path}")
    for method in methods:
        print(f"       - {method}")
    print()
PY

        heading "Largest MainWindow partials overall"

        python - "$MAINWINDOW_DIR" <<'PY'
from pathlib import Path
import re
import sys

mainwindow_dir = Path(sys.argv[1])

method_pattern = re.compile(
    r"(?ms)^ {4}"
    r"(?:private|protected|public|internal)\s+"
    r"(?:(?:static|async|sealed|override|virtual|partial|extern|new)\s+)*"
    r".*?"
    r"\b(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*"
    r"\([^;{}]*?\)\s*"
    r"(?:where\s+.*?)*\{"
)

rows = []

for path in sorted(mainwindow_dir.glob("MainWindow.*.cs")):
    text = path.read_text(encoding="utf-8", errors="replace")
    methods = [match.group("name") for match in method_pattern.finditer(text)]
    line_count = len(text.splitlines())
    generated = "generated-preview" if "<auto-generated-preview>" in text else "clean"

    rows.append((line_count, len(methods), generated, path))

rows.sort(reverse=True, key=lambda row: (row[0], row[1], str(row[3])))

for line_count, method_count, generated, path in rows[:35]:
    print(f"{line_count:5} lines  {method_count:3} methods  {generated:17} {path}")
PY

        heading "Recent checkpoint tags"

        git tag --sort=-creatordate |
            grep '^refactor-' |
            head -20

        success "Next candidate scan complete."
    } 2>&1 | tee "$OUTPUT"

    if declare -F copy_clean >/dev/null 2>&1 && copy_clean "$OUTPUT"; then
        success "Clean next-candidate scan output copied to the clipboard."
    else
        echo
        echo "copy_clean is unavailable; output remains at $OUTPUT"
    fi
)
