// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private void UseFasterThumbnailsMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not MenuItem menuItem) return;

            _userConfiguration.SetUseFasterThumbnails(menuItem.IsChecked);
            menuItem.IsChecked = _userConfiguration.UseFasterThumbnails;
        }

    private void DisableHoverEffectsMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not MenuItem menuItem) return;

            _userConfiguration.SetDisableHoverEffects(menuItem.IsChecked);
            menuItem.IsChecked = _userConfiguration.DisableHoverEffects;

            // Set the attached property on the main window to disable hover effects globally
            HoverEffectHelper.SetDisableHoverEffects(this, menuItem.IsChecked);

            RefreshHoverOverlayState();
        }

    private void LogModUpdateMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not MenuItem menuItem) return;

            _userConfiguration.SetLogModUpdates(menuItem.IsChecked);
            menuItem.IsChecked = _userConfiguration.LogModUpdates;
        }

    private void LogModInstallMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not MenuItem menuItem) return;

            _userConfiguration.SetLogModInstalls(menuItem.IsChecked);
            menuItem.IsChecked = _userConfiguration.LogModInstalls;
        }

    private void LogModDeletionMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not MenuItem menuItem) return;

            _userConfiguration.SetLogModDeletions(menuItem.IsChecked);
            menuItem.IsChecked = _userConfiguration.LogModDeletions;
        }

    private void LogAppLifecycleMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not MenuItem menuItem) return;

            _userConfiguration.SetLogAppLaunchAndExit(menuItem.IsChecked);
            menuItem.IsChecked = _userConfiguration.LogAppLaunchAndExit;
        }

    private void LogErrorsAndExceptionsMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not MenuItem menuItem) return;

            _userConfiguration.SetLogErrorsAndExceptions(menuItem.IsChecked);
            menuItem.IsChecked = _userConfiguration.LogErrorsAndExceptions;
            InitializeTraceListener();
        }

    private void InitializeTraceListener()
        {
            // Remove existing listener if present
            if (_traceListener != null)
            {
                System.Diagnostics.Trace.Listeners.Remove(_traceListener);
                _traceListener.Dispose();
                _traceListener = null;
            }

            // Add new listener if logging is enabled
            if (_userConfiguration.LogErrorsAndExceptions)
            {
                _traceListener = new ModManagerTraceListener(_modActivityLoggingService);
                System.Diagnostics.Trace.Listeners.Add(_traceListener);
                _modActivityLoggingService.LogDiagnostic("Error and exception logging enabled");
            }
        }

    private void UpdateLoggingMenuState()
        {
            if (LogModUpdateMenuItem is not null)
                LogModUpdateMenuItem.IsChecked = _userConfiguration.LogModUpdates;
            if (LogModInstallMenuItem is not null)
                LogModInstallMenuItem.IsChecked = _userConfiguration.LogModInstalls;
            if (LogModDeletionMenuItem is not null)
                LogModDeletionMenuItem.IsChecked = _userConfiguration.LogModDeletions;
            if (LogAppLifecycleMenuItem is not null)
                LogAppLifecycleMenuItem.IsChecked = _userConfiguration.LogAppLaunchAndExit;
            if (LogErrorsAndExceptionsMenuItem is not null)
                LogErrorsAndExceptionsMenuItem.IsChecked = _userConfiguration.LogErrorsAndExceptions;
        }
}
