// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private void DisableAutoRefreshMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not MenuItem menuItem) return;

            var disable = menuItem.IsChecked;

            if (disable && !_userConfiguration.DisableAutoRefreshWarningAcknowledged)
            {
                var message =
                    "This will disable automatic refresh functions such as update checks, loading of tags and other mod details, user reports and other similar functions." +
                    Environment.NewLine + Environment.NewLine +
                    "This will decrease loading times on start for example. Use the \"Refresh\" button to choose when you want to fetch details from cache and/or Mod DB. This dialog will not be shown again.";

                var confirmation = WpfMessageBox.Show(
                    message,
                    "Simple VS Manager",
                    MessageBoxButton.YesNo,
                    MessageBoxImage.Warning);

                if (confirmation != MessageBoxResult.Yes)
                {
                    menuItem.IsChecked = false;
                    return;
                }

                _userConfiguration.SetDisableAutoRefreshWarningAcknowledged(true);
            }

            _userConfiguration.SetDisableAutoRefresh(disable);
            _viewModel?.SetAutoRefreshDisabled(disable);
        }

    private void AutomaticDataBackupsMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not MenuItem menuItem) return;

            if (menuItem.IsChecked && (string.IsNullOrWhiteSpace(_dataDirectory) || !Directory.Exists(_dataDirectory)))
            {
                WpfMessageBox.Show(
                    "Please configure a valid VintagestoryData folder before enabling automatic backups.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
                menuItem.IsChecked = false;
                return;
            }

            if (menuItem.IsChecked && !_userConfiguration.AutomaticDataBackupsWarningAcknowledged)
            {
                const string message =
                    "This is an experimental feature and will increase your start up time depending on your files. Depending on your mods, saves and other files it could also end up taking up a lot of disk space."
                    + "\n\n"
                    + "But probably not. Report any bugs! Remember to launch with the \"Launch Vintage Story\" button, it backups at launch ONLY.";

                WpfMessageBox.Show(
                    message,
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);

                _userConfiguration.SetAutomaticDataBackupsWarningAcknowledged(true);
            }

            _userConfiguration.SetAutomaticDataBackupsEnabled(menuItem.IsChecked);
            menuItem.IsChecked = _userConfiguration.AutomaticDataBackupsEnabled;
        }

    private void DisableInternetAccessMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not MenuItem menuItem) return;

            var isDisabled = menuItem.IsChecked;
            InternetAccessManager.SetInternetAccessDisabled(isDisabled);
            _userConfiguration.SetDisableInternetAccess(isDisabled);

            _viewModel?.OnInternetAccessStateChanged();
        }

    private void AlwaysClearModlistsMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            HandleModlistAutoLoadMenuClick(
                sender,
                ModlistAutoLoadBehavior.Replace,
                ModlistAutoLoadBehavior.Prompt);
        }

    private void AlwaysAddModlistsMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            HandleModlistAutoLoadMenuClick(
                sender,
                ModlistAutoLoadBehavior.Add,
                ModlistAutoLoadBehavior.Prompt);
        }

    private void HandleModlistAutoLoadMenuClick(object sender, ModlistAutoLoadBehavior enabledBehavior,
            ModlistAutoLoadBehavior disabledBehavior)
        {
            if (sender is not MenuItem menuItem) return;

            var newBehavior = menuItem.IsChecked ? enabledBehavior : disabledBehavior;
            SetModlistAutoLoadBehavior(newBehavior);
        }

    private void SetModlistAutoLoadBehavior(ModlistAutoLoadBehavior behavior)
        {
            UpdateModlistAutoLoadMenu(behavior);
            _userConfiguration.SetModlistAutoLoadBehavior(behavior);
        }

    private void UpdateModlistAutoLoadMenu(ModlistAutoLoadBehavior behavior)
        {
            if (AlwaysClearModlistsMenuItem is not null)
                AlwaysClearModlistsMenuItem.IsChecked = behavior == ModlistAutoLoadBehavior.Replace;

            if (AlwaysAddModlistsMenuItem is not null)
                AlwaysAddModlistsMenuItem.IsChecked = behavior == ModlistAutoLoadBehavior.Add;
        }

    private void UpdateGameVersionMenuItem(string? gameVersion)
        {
            if (GameVersionMenuItem is null) return;

            if (string.IsNullOrWhiteSpace(gameVersion))
            {
                GameVersionMenuItem.Visibility = Visibility.Collapsed;
                return;
            }

            GameVersionMenuItem.Header = $"Vintage Story: {gameVersion}";
            GameVersionMenuItem.Visibility = Visibility.Visible;
        }
}
