// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private async Task<bool> TryEnsureDataBackupBeforeLaunchAsync()
        {
            if (!_userConfiguration.AutomaticDataBackupsEnabled) return true;
            if (string.IsNullOrWhiteSpace(_dataDirectory) || !Directory.Exists(_dataDirectory)) return true;

            ShowDataBackupOverlay("Preparing VintagestoryData backup...");
            var progress = CreateDataBackupProgressReporter("Backing up VintagestoryData...");

            var installedGameVersion = VintageStoryVersionLocator.GetInstalledVersion(_gameDirectory);

            try
            {
                await _dataBackupService
                    .CreateBackupAsync(_dataDirectory!, installedGameVersion, progress, CancellationToken.None)
                    .ConfigureAwait(true);
                return true;
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                var response = WpfMessageBox.Show(
                    $"The automatic VintagestoryData backup failed:\n{ex.Message}\n\nLaunch Vintage Story without creating a backup?",
                    "Simple VS Manager",
                    MessageBoxButton.YesNo,
                    MessageBoxImage.Warning);
                return response == MessageBoxResult.Yes;
            }
            catch (Exception ex)
            {
                WpfMessageBox.Show(
                    $"The automatic VintagestoryData backup failed:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return false;
            }
            finally
            {
                HideDataBackupOverlay();
            }
        }

    private async void LaunchGameButton_OnClick(object sender, RoutedEventArgs e)
        {
            if (_isApplyingPreset) return;

            if (!await TryEnsureDataBackupBeforeLaunchAsync().ConfigureAwait(true)) return;

            if (!string.IsNullOrWhiteSpace(_customShortcutPath))
            {
                if (!File.Exists(_customShortcutPath))
                {
                    WpfMessageBox.Show(
                        "The custom Vintage Story shortcut could not be found. Please set it again from File > Set custom Vintage Story shortcut.",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Warning);
                    _userConfiguration.ClearCustomShortcutPath();
                    _customShortcutPath = null;
                    return;
                }

                try
                {
                    Process.Start(new ProcessStartInfo
                    {
                        FileName = _customShortcutPath,
                        UseShellExecute = true
                    });
                }
                catch (Exception ex)
                {
                    WpfMessageBox.Show($"Failed to launch Vintage Story using the shortcut:\n{ex.Message}",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Error);
                }

                return;
            }

            if (string.IsNullOrWhiteSpace(_dataDirectory) || !Directory.Exists(_dataDirectory))
            {
                WpfMessageBox.Show(
                    "The VintagestoryData folder could not be located. Please verify it from File > Set Data Folder before launching the game.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
                return;
            }

            var executable = GameDirectoryLocator.FindExecutable(_gameDirectory);
            if (executable is null)
            {
                WpfMessageBox.Show(
                    "The Vintage Story executable could not be found. Verify the game folder in File > Set Game Folder.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
                return;
            }

            try
            {
                var startInfo = new ProcessStartInfo
                {
                    FileName = executable,
                    WorkingDirectory = Path.GetDirectoryName(executable)!,
                    UseShellExecute = false
                };
                startInfo.ArgumentList.Add("--dataPath");
                startInfo.ArgumentList.Add(_dataDirectory);

                Process.Start(startInfo);
            }
            catch (Exception ex)
            {
                WpfMessageBox.Show($"Failed to launch Vintage Story:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }

    private void SetCustomShortcutMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            string? initialDirectory = null;
            string? initialFileName = null;

            if (!string.IsNullOrWhiteSpace(_customShortcutPath))
                try
                {
                    initialDirectory = Path.GetDirectoryName(_customShortcutPath);
                    initialFileName = Path.GetFileName(_customShortcutPath);
                }
                catch (Exception)
                {
                    initialDirectory = null;
                    initialFileName = null;
                }

            using var dialog = new WinForms.OpenFileDialog
            {
                Title = "Select Vintage Story shortcut",
                Filter = "Shortcut files (*.lnk)|*.lnk|All files (*.*)|*.*",
                CheckFileExists = true,
                Multiselect = false,
                RestoreDirectory = true
            };

            if (!string.IsNullOrWhiteSpace(initialDirectory) && Directory.Exists(initialDirectory))
                dialog.InitialDirectory = initialDirectory;

            if (!string.IsNullOrWhiteSpace(initialFileName)) dialog.FileName = initialFileName;

            var result = dialog.ShowDialog();
            if (result == WinForms.DialogResult.OK)
            {
                var selected = dialog.FileName;
                if (!File.Exists(selected))
                {
                    WpfMessageBox.Show(
                        "The selected shortcut could not be found.",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Warning);
                    return;
                }

                try
                {
                    _userConfiguration.SetCustomShortcutPath(selected);
                    _customShortcutPath = _userConfiguration.CustomShortcutPath;
                }
                catch (ArgumentException ex)
                {
                    WpfMessageBox.Show(
                        $"The selected shortcut is not valid:\n{ex.Message}",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Warning);
                }

                return;
            }

            if (string.IsNullOrWhiteSpace(_customShortcutPath)) return;

            var clear = WpfMessageBox.Show(
                "Do you want to clear the custom Vintage Story shortcut?",
                "Simple VS Manager",
                MessageBoxButton.YesNo,
                MessageBoxImage.Question);

            if (clear != MessageBoxResult.Yes) return;

            _userConfiguration.ClearCustomShortcutPath();
            _customShortcutPath = null;
        }
}
