// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private ModlistLoadMode? PromptModlistLoadMode()
        {
            var behavior = _userConfiguration.ModlistAutoLoadBehavior;
            switch (behavior)
            {
                case ModlistAutoLoadBehavior.Replace:
                    return ModlistLoadMode.Replace;
                case ModlistAutoLoadBehavior.Add:
                    return ModlistLoadMode.Add;
            }

            var buttonOverrides = new MessageDialogButtonContentOverrides
            {
                Yes = "Only Modlist mods",
                No = "Add Modlist mods"
            };

            var result = WpfMessageBox.Show(
                this,
                "How would you like to load the modlist?" +
                "\n\nOnly Modlist mods: Delete your current mods and install only the mods from the modlist." +
                "\nAdd Modlist mods: Keep your current mods and add any missing mods from the modlist." +
                "\nCancel: Do nothing.",
                "Load Modlist",
                MessageBoxButton.YesNoCancel,
                MessageBoxImage.Question,
                buttonContentOverrides: buttonOverrides);

            return result switch
            {
                MessageBoxResult.Yes => ModlistLoadMode.Replace,
                MessageBoxResult.No => ModlistLoadMode.Add,
                _ => null
            };
        }

    private PresetLoadOptions GetModlistLoadOptions(ModlistLoadMode mode)
        {
            if (mode == ModlistLoadMode.Replace) return ModListLoadOptions;

            return new PresetLoadOptions(ModListLoadOptions.ApplyModStatus, ModListLoadOptions.ApplyModVersions, false);
        }

    private bool EnsureModlistBackupBeforeLoad()
        {
            MessageBoxResult prompt;
            if (_userConfiguration.SuppressModlistSavePrompt)
            {
                prompt = MessageBoxResult.No;
            }
            else
            {
                var suppressButton = new MessageDialogExtraButton(
                    "No, don't ask again",
                    MessageBoxResult.No,
                    () => _userConfiguration.SetSuppressModlistSavePrompt(true));

                prompt = WpfMessageBox.Show(
                    "Would you like to backup your current mods as a Modlist before loading the selected Modlist? Your current mods will be deleted! ",
                    "Simple VS Manager",
                    MessageBoxButton.YesNoCancel,
                    MessageBoxImage.Question,
                    suppressButton);
            }

            if (prompt == MessageBoxResult.Cancel) return false;

            if (prompt == MessageBoxResult.Yes)
            {
                var result = TrySaveModlist(null, out var savedFilePath);
                if (result)
                {
                    if (!string.IsNullOrWhiteSpace(savedFilePath))
                        RefreshLocalModlists(true, new[] { savedFilePath });
                    else
                        RefreshLocalModlists(true);
                }

                return result;
            }

            return true;
        }

    private Task CreateAutomaticBackupAsync(string trigger)
        {
            return CreateBackupAsync(
                trigger,
                "Backup",
                true,
                false);
        }

}
