// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private Task SaveModlistToCloudAsync()
        {
            return ExecuteCloudOperationAsync(async store =>
            {
                var suggestedName = InstalledModsPdfGenerator.BuildCloudModlistName();
                var configOptions = BuildModConfigOptions(selectByDefault: false);
                var detailsDialog = new CloudModlistDetailsDialog(
                    this,
                    suggestedName,
                    configOptions,
                    _viewModel?.InstalledGameVersion);
                var dialogResult = detailsDialog.ShowDialog();
                if (dialogResult != true) return;

                var uploader = DetermineUploaderName(store);

                var modlistName = detailsDialog.ModlistName;
                var description = detailsDialog.ModlistDescription;
                var version = detailsDialog.ModlistVersion;

                Dictionary<string, IReadOnlyList<ModConfigurationSnapshot>>? includedConfigurations = null;
                var selectedConfigOptions = detailsDialog.GetSelectedConfigOptions();
                includedConfigurations = TryReadModConfigurations(selectedConfigOptions);

                var gameVersion = ResolveGameVersion(detailsDialog.ModlistGameVersion);

                if (!TryBuildCurrentModlistJson(modlistName,
                        description,
                        version,
                        uploader,
                        includedConfigurations,
                        gameVersion,
                        out var json)) return;

                var slots =
                    await CloudModlistSlotService.LoadSlotsAsync(
                        store,
                        true,
                        false);
                var trimmedModlistName = modlistName.Trim();

                CloudModlistSlot? replacementSlot = null;
                string? slotKey = null;

                var matchingSlot = slots.FirstOrDefault(slot =>
                    slot.IsOccupied
                    && string.Equals((slot.Name ?? string.Empty).Trim(), trimmedModlistName,
                        StringComparison.OrdinalIgnoreCase));

                if (matchingSlot is not null)
                {
                    var slotLabel = CloudModlistHelper.FormatCloudSlotLabel(matchingSlot.SlotKey);
                    var replaceExisting = WpfMessageBox.Show(
                        $"A cloud modlist named \"{trimmedModlistName}\" already exists in {slotLabel}. Do you want to replace it?",
                        "Simple VS Manager",
                        MessageBoxButton.YesNo,
                        MessageBoxImage.Question);

                    if (replaceExisting != MessageBoxResult.Yes) return;

                    replacementSlot = matchingSlot;
                    slotKey = matchingSlot.SlotKey;
                }

                CloudModlistSlot? freeSlot = null;
                if (slotKey is null)
                {
                    freeSlot = slots.FirstOrDefault(slot => !slot.IsOccupied);
                    slotKey = freeSlot?.SlotKey;
                }

                if (slotKey is null)
                {
                    replacementSlot = PromptForCloudSaveReplacement(slots);
                    if (replacementSlot is null) return;

                    slotKey = replacementSlot.SlotKey;
                }

                await store.SaveAsync(slotKey, json);

                if (replacementSlot is not null)
                {
                    var replacedName = replacementSlot.Name ?? "existing modlist";
                    var replacedVersion = replacementSlot.Version;
                    if (!string.IsNullOrWhiteSpace(replacedVersion)) replacedName = $"{replacedName} (v{replacedVersion})";

                    _viewModel?.ReportStatus($"Replaced cloud modlist \"{replacedName}\" with \"{modlistName}\".");
                }
                else
                {
                    _viewModel?.ReportStatus($"Saved cloud modlist \"{modlistName}\" to the cloud.");
                }
            }, "save the modlist to the cloud");
        }

    private List<ModConfigOption> BuildModConfigOptions(bool selectByDefault = true)
        {
            var options = new List<ModConfigOption>();

            if (_viewModel is null) return options;

            var mods = _viewModel.GetInstalledModsSnapshot();
            var seenIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            foreach (var mod in mods)
            {
                if (mod is null || string.IsNullOrWhiteSpace(mod.ModId)) continue;

                var normalizedId = mod.ModId.Trim();
                if (!seenIds.Add(normalizedId)) continue;

                var configPaths = _userConfiguration.GetModConfigPaths(normalizedId)
                    .Where(path => !string.IsNullOrWhiteSpace(path) && File.Exists(path))
                    .ToList();

                if (configPaths.Count > 0)
                    options.Add(new ModConfigOption(normalizedId, mod.DisplayName, configPaths, selectByDefault));
            }

            options.Sort((left, right) =>
                string.Compare(left.DisplayName, right.DisplayName, StringComparison.OrdinalIgnoreCase));
            return options;
        }

    private Dictionary<string, IReadOnlyList<ModConfigurationSnapshot>>?
            TryReadModConfigurations(
                IReadOnlyList<ModConfigOption> selectedConfigOptions)
        {
            var requests =
                selectedConfigOptions
                    .Where(option => option is not null)
                    .Select(option =>
                        new ModConfigurationCaptureRequest(
                            option.ModId,
                            option.DisplayName,
                            option.ConfigPaths))
                    .ToList();

            var captureResult =
                ModConfigurationCaptureService.Capture(
                    requests,
                    _dataDirectory);

            if (captureResult.Errors.Count > 0)
            {
                WpfMessageBox.Show(
                    "Some configuration files could not be included:\n" +
                    string.Join("\n", captureResult.Errors),
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
            }

            return captureResult.Configurations is null
                ? null
                : new Dictionary<
                    string,
                    IReadOnlyList<ModConfigurationSnapshot>>(
                        captureResult.Configurations,
                        StringComparer.OrdinalIgnoreCase);
        }

    private string? TryGetRelativeConfigPath(string path, string sanitizedFileName)
        {
            if (string.IsNullOrWhiteSpace(_dataDirectory)) return null;

            var configDirectory = Path.Combine(_dataDirectory, "ModConfig");
            if (!PathRelationshipHelper.IsPathWithinDirectory(configDirectory, path)) return null;

            try
            {
                var relativePath = Path.GetRelativePath(Path.GetFullPath(configDirectory), Path.GetFullPath(path));
                return ModConfigPathHelper.NormalizeRelativeConfigPath(relativePath, sanitizedFileName);
            }
            catch (Exception)
            {
                return null;
            }
        }

    private async void SaveModlistToCloudMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            await SaveModlistToCloudAsync();
            if (_viewModel?.IsViewingModlistTab == true)
                await RefreshCloudModlistsAsync(true);
            else
                _cloudModlistsLoaded = false;
        }

    private async void SaveCloudModlistButton_OnClick(object sender, RoutedEventArgs e)
        {
            await SaveModlistToCloudAsync();
            if (_viewModel?.IsViewingModlistTab == true) await RefreshCloudModlistsAsync(true);
        }

    private async void ModifyCloudModlistsButton_OnClick(object sender, RoutedEventArgs e)
        {
            await ExecuteCloudOperationAsync(async store => { await ShowCloudModlistManagementDialogAsync(store); },
                "manage your cloud modlists");
        }

    private async Task<bool> IsCloudUploaderNameAvailableAsync(FirebaseModlistStore store, string uploader)
        {
            if (string.IsNullOrWhiteSpace(uploader)) return true;

            var trimmedUploader = uploader.Trim();
            var currentUserId = store.CurrentUserId;
            var registryEntries = await store.GetRegistryEntriesAsync();

            foreach (var entry in registryEntries)
            {
                if (!string.IsNullOrEmpty(currentUserId) &&
                    string.Equals(entry.OwnerId, currentUserId, StringComparison.Ordinal))
                    continue;

                var metadata = ModlistMetadataParser.ExtractModlistMetadata(entry.ContentJson);
                if (metadata.Uploader is not null &&
                    string.Equals(metadata.Uploader, trimmedUploader, StringComparison.OrdinalIgnoreCase))
                    return false;
            }

            return true;
        }

    private async Task ExecuteCloudOperationAsync(Func<FirebaseModlistStore, Task> operation, string actionDescription)
        {
            try
            {
                InternetAccessManager.ThrowIfInternetAccessDisabled();
            }
            catch (InternetAccessDisabledException ex)
            {
                WpfMessageBox.Show(ex.Message,
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
                return;
            }

            FirebaseModlistStore store;
            try
            {
                store = await EnsureCloudStoreInitializedAsync();
            }
            catch (Exception ex)
            {
                StatusLogService.AppendStatus($"Failed to initialize cloud storage: {ex}", true);
                WpfMessageBox.Show($"Failed to initialize cloud storage:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return;
            }

            try
            {
                await operation(store);
                EnsureFirebaseAuthBackedUpIfAvailable();
            }
            catch (InternetAccessDisabledException ex)
            {
                WpfMessageBox.Show(ex.Message,
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
            }
            catch (Exception ex) when (ex is HttpRequestException or TaskCanceledException)
            {
                StatusLogService.AppendStatus($"Network error while attempting to {actionDescription}: {ex.Message}", true);
                WpfMessageBox.Show($"Failed to {actionDescription}:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
            catch (InvalidOperationException ex)
            {
                StatusLogService.AppendStatus(
                    $"Cloud operation failed while attempting to {actionDescription}: {ex.Message}", true);
                WpfMessageBox.Show($"Failed to {actionDescription}:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
            catch (Exception ex)
            {
                StatusLogService.AppendStatus($"Unexpected error while attempting to {actionDescription}: {ex}", true);
                WpfMessageBox.Show($"An unexpected error occurred while attempting to {actionDescription}:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }

    private async Task MigrateLegacyFirebaseDataIfNeededAsync()
        {
            if (_firebaseMigrationAttempted) return;

            var playerUid = _viewModel?.PlayerUid;
            if (string.IsNullOrWhiteSpace(playerUid)) return;

            _firebaseMigrationAttempted = true;

            try
            {
                var migrationService = new FirebaseModlistMigrationService();
                var migrationSucceeded = await migrationService
                    .TryMigrateAsync(playerUid, _viewModel?.PlayerName, _userConfiguration, CancellationToken.None)
                    .ConfigureAwait(true);

                if (migrationSucceeded)
                    await Dispatcher.InvokeAsync(() =>
                        WpfMessageBox.Show(
                            this,
                            "Due to bandwidth issues, the manager is changing to another database. Your modlists will be saved and moved to the new database. Each user's modlists will appear in the Online Modlists tab when they update. All compatibility votes have been reset. Thank you for using the manager and voting!",
                            "Simple VS Manager",
                            MessageBoxButton.OK,
                            MessageBoxImage.Information));
            }
            catch (Exception ex)
            {
                StatusLogService.AppendStatus($"Failed to migrate cloud modlists to the new Firebase project: {ex.Message}",
                    true);
            }
        }

    private async Task<FirebaseModlistStore> EnsureCloudStoreInitializedAsync()
        {
            if (_cloudModlistStore is { } existingStore)
            {
                ApplyPlayerIdentityToCloudStore(existingStore);
                return existingStore;
            }

            await _cloudStoreLock.WaitAsync();
            try
            {
                if (_cloudModlistStore is { } cached)
                {
                    ApplyPlayerIdentityToCloudStore(cached);
                    return cached;
                }

                // Migration is only attempted once (see _firebaseMigrationAttempted flag).
                // The dialog is shown from the primary call in MainWindow_Loaded.
                await MigrateLegacyFirebaseDataIfNeededAsync().ConfigureAwait(false);

                var store = new FirebaseModlistStore();
                ApplyPlayerIdentityToCloudStore(store);
                _cloudModlistStore = store;
                return store;
            }
            finally
            {
                _cloudStoreLock.Release();
            }
        }

    private CloudModlistSlot? PromptForCloudSaveReplacement(IReadOnlyList<CloudModlistSlot> slots)
        {
            if (slots is null) return null;

            var occupiedSlots = slots.Where(slot => slot.IsOccupied).ToList();
            if (occupiedSlots.Count == 0) return null;

            var dialog = new CloudSlotSelectionDialog(this,
                occupiedSlots,
                "Replace Cloud Modlist",
                "Select a cloud modlist to replace.");
            var dialogResult = dialog.ShowDialog();
            return dialogResult == true ? dialog.SelectedSlot : null;
        }

    private async Task ShowCloudModlistManagementDialogAsync(FirebaseModlistStore store)
        {
            var entries = await BuildCloudModlistManagementEntriesAsync(store);
            if (entries.Count == 0)
            {
                WpfMessageBox.Show(
                    "You do not have any cloud modlists saved.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            var dialog = new CloudModlistManagementDialog(
                this,
                entries,
                () => BuildCloudModlistManagementEntriesAsync(store),
                (entry, newName) => RenameCloudModlistAsync(store, entry, newName),
                entry => DeleteCloudModlistAsync(store, entry));

            dialog.ShowDialog();
        }

    private async Task<IReadOnlyList<CloudModlistManagementEntry>> BuildCloudModlistManagementEntriesAsync(
            FirebaseModlistStore store)
        {
            var slots =
                await CloudModlistSlotService.LoadSlotsAsync(
                    store,
                    false,
                    true);
            var list = new List<CloudModlistManagementEntry>(slots.Count);

            foreach (var slot in slots)
            {
                var slotLabel = CloudModlistHelper.FormatCloudSlotLabel(slot.SlotKey);
                list.Add(new CloudModlistManagementEntry(
                    slot.SlotKey,
                    slotLabel,
                    slot.Name,
                    slot.Version,
                    slot.DisplayName,
                    slot.CachedContent));
            }

            return list;
        }

    private async Task<bool> RenameCloudModlistAsync(
            FirebaseModlistStore store,
            CloudModlistManagementEntry entry,
            string newName)
        {
            if (string.IsNullOrWhiteSpace(newName)) return false;

            var trimmedName = newName.Trim();
            var json = entry.CachedContent;

            if (string.IsNullOrWhiteSpace(json))
                try
                {
                    json = await store.LoadAsync(entry.SlotKey);
                }
                catch (Exception ex) when (ex is HttpRequestException or TaskCanceledException)
                {
                    StatusLogService.AppendStatus($"Failed to load cloud modlist for rename: {ex.Message}", true);
                    WpfMessageBox.Show($"Failed to load the cloud modlist before renaming:\n{ex.Message}",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Error);
                    return false;
                }

            if (string.IsNullOrWhiteSpace(json))
            {
                WpfMessageBox.Show(
                    "The selected cloud modlist could not be loaded.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
                return false;
            }

            string updatedJson;
            try
            {
                updatedJson = CloudModlistHelper.ReplaceCloudModlistName(json, trimmedName);
            }
            catch (Exception ex) when (ex is JsonException or InvalidOperationException)
            {
                StatusLogService.AppendStatus($"Failed to update cloud modlist name: {ex.Message}", true);
                WpfMessageBox.Show($"The cloud modlist data is invalid and could not be renamed:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return false;
            }

            try
            {
                await store.SaveAsync(entry.SlotKey, updatedJson);
            }
            catch (Exception ex) when (ex is HttpRequestException or TaskCanceledException)
            {
                StatusLogService.AppendStatus($"Failed to rename cloud modlist: {ex.Message}", true);
                WpfMessageBox.Show($"Failed to rename the cloud modlist:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return false;
            }

            var slotLabel = CloudModlistHelper.FormatCloudSlotLabel(entry.SlotKey);
            _viewModel?.ReportStatus($"Renamed cloud modlist in {slotLabel} to \"{trimmedName}\".");

            await UpdateCloudModlistsAfterChangeAsync();
            return true;
        }

    private async Task<bool> DeleteCloudModlistAsync(FirebaseModlistStore store, CloudModlistManagementEntry entry)
        {
            try
            {
                await store.DeleteAsync(entry.SlotKey);
            }
            catch (Exception ex) when (ex is HttpRequestException or TaskCanceledException)
            {
                StatusLogService.AppendStatus($"Failed to delete cloud modlist: {ex.Message}", true);
                WpfMessageBox.Show($"Failed to delete the cloud modlist:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return false;
            }
            catch (InvalidOperationException ex)
            {
                StatusLogService.AppendStatus($"Invalid request while deleting cloud modlist: {ex.Message}", true);
                WpfMessageBox.Show($"Failed to delete the cloud modlist:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return false;
            }

            var slotLabel = CloudModlistHelper.FormatCloudSlotLabel(entry.SlotKey);
            _viewModel?.ReportStatus($"Deleted cloud modlist from {slotLabel}.");

            await UpdateCloudModlistsAfterChangeAsync();
            return true;
        }

    private async Task DeleteAllCloudModlistsAndAuthorizationAsync(FirebaseModlistStore store,
            bool showCompletionMessage = true)
        {
            await store.DeleteAllUserDataAsync();
            await store.Authenticator.DeleteAccountAsync(CancellationToken.None);

            DeleteFirebaseAuthFiles();

            _cloudModlistStore = null;
            _cloudModlistsLoaded = false;

            SetCloudModlistSelection(null);
            _viewModel?.ReplaceCloudModlists(null);
            if (CloudModlistsDataGrid is not null) CloudModlistsDataGrid.SelectedItem = null;

            StatusLogService.AppendStatus("Deleted all cloud modlists and Firebase authorization.", false);
            _viewModel?.ReportStatus("Deleted all cloud modlists and Firebase authorization.");

            if (showCompletionMessage)
                WpfMessageBox.Show(
                    this,
                    "Cloud modlists and Firebase authorization have been deleted.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
        }

    private async Task UpdateCloudModlistsAfterChangeAsync()
        {
            if (_viewModel?.IsViewingModlistTab == true)
                await RefreshCloudModlistsAsync(true);
            else
                _cloudModlistsLoaded = false;
        }
}
