// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private void ModsDataGrid_OnSorting(object sender, DataGridSortingEventArgs e)
        {
            if (_viewModel is null) return;

            var sortMemberPath = e.Column.SortMemberPath;
            if (string.IsNullOrWhiteSpace(sortMemberPath))
            {
                e.Handled = true;
                return;
            }

            e.Handled = true;

            var direction = e.Column.SortDirection == ListSortDirection.Ascending
                ? ListSortDirection.Descending
                : ListSortDirection.Ascending;

            ApplyModListSort(sortMemberPath, direction, true);
        }

    private void ModsDataGrid_OnSelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            // We use custom selection tracking via _selectedMods list instead of DataGrid's native selection.
            // Clear any DataGrid selection to prevent it from interfering with our custom selection.
            // With IsSynchronizedWithCurrentItem=False, this should only fire on direct user clicks,
            // which we handle in PreviewMouseLeftButtonDown.
            if (sender is DataGrid dataGrid)
            {
                dataGrid.SelectedIndex = -1;
                dataGrid.UnselectAll();
                dataGrid.UnselectAllCells();
            }
        }

    private async void ModsDataGrid_OnPreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (await TryHandleModListKeyDownAsync(e)) e.Handled = true;
        }

    private async void MainWindow_OnPreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (await TryHandleModListKeyDownAsync(e)) e.Handled = true;
        }

    private async Task<bool> TryHandleModListKeyDownAsync(KeyEventArgs e)
        {
            if (_isApplyingPreset) return true;

            if (e.Key == Key.A && Keyboard.Modifiers.HasFlag(ModifierKeys.Control))
            {
                // Allow CTRL+A to select text when a TextBox has focus
                if (Keyboard.FocusedElement is TextBox)
                    return false;

                if (ModsDataGrid?.IsVisible == true)
                {
                    SelectAllModsInCurrentView();
                    return true;
                }

                return false;
            }

            if (e.Key == Key.Delete)
            {
                var modifiers = Keyboard.Modifiers;
                if ((modifiers & (ModifierKeys.Control | ModifierKeys.Alt | ModifierKeys.Windows)) == ModifierKeys.None &&
                    _selectedMods.Count > 0)
                {
                    await DeleteSelectedModsAsync();
                    return true;
                }
            }

            return false;
        }

    private void ModsDataGrid_OnPreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (_isApplyingPreset)
            {
                e.Handled = true;
                return;
            }

            if (e.Handled) return;

            if (sender is not DataGrid) return;

            if (ShouldIgnoreRowSelection(e.OriginalSource as DependencyObject)) return;

            var source = e.OriginalSource as DependencyObject;
            if (FindAncestor<DataGridRow>(source) != null) return;

            if (FindAncestor<DataGridColumnHeader>(source) != null) return;

            if (FindAncestor<ScrollBar>(source) != null) return;

            ClearSelection(true);
        }

    private void ModsDataGridRow_OnPreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (_isApplyingPreset)
            {
                e.Handled = true;
                return;
            }

            if (ShouldIgnoreRowSelection(e.OriginalSource as DependencyObject)) return;

            if (sender is not DataGridRow row || row.DataContext is not ModListItemViewModel mod) return;

            row.Focus();
            HandleModRowSelection(mod);
            e.Handled = true;
        }

    private void ModDatabaseCard_OnPreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (_isApplyingPreset)
            {
                e.Handled = true;
                return;
            }

            if (ShouldIgnoreRowSelection(e.OriginalSource as DependencyObject)) return;

            if (sender is not ListViewItem item || item.DataContext is not ModListItemViewModel mod) return;

            item.Focus();
            HandleModRowSelection(mod);
            e.Handled = true;
        }

    private void ModDatabasePageButton_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is WpfButton { DataContext: ModListItemViewModel mod }
                && mod.OpenModDatabasePageCommand is ICommand command
                && command.CanExecute(null))
                command.Execute(null);

            e.Handled = true;
        }

    private void UpdateServerOptionsState(bool isEnabled)
        {
            if (EnableServerOptionsMenuItem is not null) EnableServerOptionsMenuItem.IsChecked = isEnabled;

            // Control visibility of server-related menu items
            var visibility = isEnabled ? Visibility.Visible : Visibility.Collapsed;
            if (ManageServerTargetsMenuItem is not null) ManageServerTargetsMenuItem.Visibility = visibility;
            if (SyncToServerMenuItem is not null) SyncToServerMenuItem.Visibility = visibility;
            if (ServerOptionsSeparator1 is not null) ServerOptionsSeparator1.Visibility = visibility;
            if (ServerOptionsSeparator2 is not null) ServerOptionsSeparator2.Visibility = visibility;

            var singleSelection = _selectedMods.Count == 1 ? _selectedMods[0] : null;
            UpdateSelectedModCopyForServerButton(isEnabled ? singleSelection : null);
        }

    private bool ShouldIgnoreRowSelection(DependencyObject? source)
        {
            while (source != null)
            {
                if (source is ButtonBase or ToggleButton || source is ToggleSwitch) return true;

                if (source is FrameworkElement { TemplatedParent: ToggleSwitch }) return true;

                if (source is DataGridCell cell && ReferenceEquals(cell.Column, ActiveColumn)) return true;

                source = VisualTreeHelper.GetParent(source);
            }

            return false;
        }

}
