// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private void SelectedModCopyForServerButton_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not WpfButton { DataContext: ModListItemViewModel mod }) return;

            var command = ServerCommandBuilder.TryBuildInstallCommand(mod.ModId, mod.Version);
            if (string.IsNullOrWhiteSpace(command)) return;

            try
            {
                WinForms.Clipboard.SetDataObject(command, true, 10, 100);
                var trimmedCommand = command.Trim();
                var statusMessage = $"Copied {trimmedCommand}";
                _viewModel?.ReportStatus(statusMessage);
            }
            catch (ExternalException ex)
            {
                var errorMessage = $"Failed to copy server install command for {mod.DisplayName}: {ex.Message}";
                _viewModel?.ReportStatus(errorMessage, true);
                WpfMessageBox.Show(
                    this,
                    "Failed to copy the server install command. Please try again.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }

    private void EditConfigButton_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not WpfButton { DataContext: ModListItemViewModel mod }) return;

            e.Handled = true;

            if (string.IsNullOrWhiteSpace(mod.ModId)) return;

            var configPaths = _userConfiguration
                .GetModConfigPaths(mod.ModId)
                .Where(path => !string.IsNullOrWhiteSpace(path))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();

            try
            {
                for (var i = configPaths.Count - 1; i >= 0; i--)
                {
                    var path = configPaths[i];
                    if (File.Exists(path)) continue;

                    configPaths.RemoveAt(i);
                    _userConfiguration.RemoveModConfigPath(mod.ModId, path);
                }

                if (configPaths.Count == 0)
                {
                    var primaryPath = PromptForConfigFile(mod, configPaths.FirstOrDefault());
                    if (primaryPath is null) return;

                    configPaths.Add(primaryPath);
                    _userConfiguration.SetModConfigPaths(mod.ModId, configPaths);
                    UpdateSelectedModEditConfigButton(mod);
                }
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or ArgumentException)
            {
                WpfMessageBox.Show($"Failed to store the configuration path:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return;
            }

            try
            {
                var editorViewModel = new ModConfigEditorViewModel(mod.DisplayName, configPaths);
                var editorWindow = new ModConfigEditorWindow(editorViewModel)
                {
                    Owner = this
                };

                var result = editorWindow.ShowDialog();
                if (result == true)
                {
                    var updatedPaths = editorViewModel.ConfigPaths.Where(path => !string.IsNullOrWhiteSpace(path)).ToList();

                    try
                    {
                        if (updatedPaths.Count == 0)
                            _userConfiguration.RemoveModConfigPath(mod.ModId);
                        else
                            _userConfiguration.SetModConfigPaths(mod.ModId, updatedPaths);

                        UpdateSelectedModEditConfigButton(mod);
                        _viewModel?.ReportStatus($"Saved config for {mod.DisplayName}.");
                    }
                    catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or ArgumentException)
                    {
                        WpfMessageBox.Show($"Failed to store the configuration path:\n{ex.Message}",
                            "Simple VS Manager",
                            MessageBoxButton.OK,
                            MessageBoxImage.Error);
                    }
                }
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or JsonException or YamlException)
            {
                WpfMessageBox.Show($"Failed to open the configuration file:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                _userConfiguration.RemoveModConfigPath(mod.ModId);
                UpdateSelectedModEditConfigButton(mod);
            }
        }

    private void CloseModInfoButton_OnClick(object sender, RoutedEventArgs e)
        {
            ClearSelection(resetAnchor: true);
            e.Handled = true;
        }

    private async void InstallModButton_OnClick(object sender, RoutedEventArgs e)
        {
            if (_isModUpdateInProgress) return;

            if (sender is not WpfButton { DataContext: ModListItemViewModel mod }) return;

            e.Handled = true;

            if (!mod.HasDownloadableRelease)
            {
                WpfMessageBox.Show("No downloadable releases are available for this mod.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            var release = SelectReleaseForInstall(mod);
            if (release is null)
            {
                WpfMessageBox.Show("No downloadable releases are available for this mod.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            if (!TryGetInstallTargetPath(mod, release, out var targetPath, out var errorMessage))
            {
                if (!string.IsNullOrWhiteSpace(errorMessage))
                    WpfMessageBox.Show(errorMessage!,
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Error);

                return;
            }

            await CreateAutomaticBackupAsync("ModsUpdated").ConfigureAwait(true);

            _isModUpdateInProgress = true;
            UpdateSelectedModButtons();

            try
            {
                var descriptor = new ModUpdateDescriptor(
                    mod.ModId,
                    mod.DisplayName,
                    release.DownloadUri,
                    targetPath,
                    false,
                    release.FileName,
                    release.Version,
                    mod.Version);

                var progress = new Progress<ModUpdateProgress>(p =>
                    _viewModel?.ReportStatus($"{mod.DisplayName}: {p.Message}"));

                var result = await _modUpdateService
                    .UpdateAsync(descriptor, _userConfiguration.CacheAllVersionsLocally, progress)
                    .ConfigureAwait(true);

                if (!result.Success)
                {
                    var message = string.IsNullOrWhiteSpace(result.ErrorMessage)
                        ? "The installation failed."
                        : result.ErrorMessage!;
                    _viewModel?.ReportStatus($"Failed to install {mod.DisplayName}: {message}", true);
                    WpfMessageBox.Show($"Failed to install {mod.DisplayName}:{Environment.NewLine}{message}",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Error);
                    return;
                }

                var versionText = string.IsNullOrWhiteSpace(release.Version) ? string.Empty : $" {release.Version}";
                _viewModel?.ReportStatus($"Installed {mod.DisplayName}{versionText}.");
                _modActivityLoggingService.LogModInstall(mod.DisplayName ?? mod.ModId ?? "Unknown", release.Version);

                await RefreshModsAsync().ConfigureAwait(true);

                if (mod.IsSelected) RemoveFromSelection(mod);

                _viewModel?.RemoveSearchResult(mod);
            }
            catch (OperationCanceledException)
            {
                _viewModel?.ReportStatus("Installation cancelled.");
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or InvalidOperationException)
            {
                _viewModel?.ReportStatus($"Failed to install {mod.DisplayName}: {ex.Message}", true);
                WpfMessageBox.Show($"Failed to install {mod.DisplayName}:{Environment.NewLine}{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
            finally
            {
                _isModUpdateInProgress = false;
                UpdateSelectedModButtons();
            }
        }

    private static ModReleaseInfo? SelectReleaseForInstall(ModListItemViewModel mod)
        {
            if (mod.LatestRelease?.IsCompatibleWithInstalledGame == true) return mod.LatestRelease;

            if (mod.LatestCompatibleRelease != null) return mod.LatestCompatibleRelease;

            return mod.LatestRelease;
        }

    private async void UpdateModButton_OnClick(object sender, RoutedEventArgs e)
        {
            if (_isModUpdateInProgress) return;

            if (sender is not WpfButton { DataContext: ModListItemViewModel mod }) return;

            e.Handled = true;

            IReadOnlyDictionary<ModListItemViewModel, ModReleaseInfo>? overrides = null;
            if (mod.SelectedVersionOption is { Release: { } selectedRelease, IsInstalled: false })
                overrides = new Dictionary<ModListItemViewModel, ModReleaseInfo>
                {
                    [mod] = selectedRelease
                };

            await UpdateModsAsync(new[] { mod }, false, overrides);
        }

    private async void SelectedModVersionComboBox_OnSelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (_isModUpdateInProgress) return;

            if (sender is not ComboBox comboBox) return;

            if (!comboBox.IsDropDownOpen && !comboBox.IsKeyboardFocusWithin) return;

            if (_viewModel?.SelectedMod is not ModListItemViewModel mod) return;

            if (comboBox.SelectedItem is not ModVersionOptionViewModel option) return;

            if (option.IsInstalled || option.Release is null) return;

            if (string.Equals(mod.Version, option.Version, StringComparison.OrdinalIgnoreCase)) return;

            var overrides = new Dictionary<ModListItemViewModel, ModReleaseInfo>
            {
                [mod] = option.Release
            };

            // Use isBulk=true to leverage the modlist install UI overlay for smooth progress feedback
            // and to prevent UI freezing. Pass showSummary=false to skip the bulk changelog dialog.
            await UpdateModsAsync(new[] { mod }, isBulk: true, overrides, showSummary: false);
        }

    private void SelectedModVersionComboBox_OnDropDownOpened(object sender, EventArgs e)
        {
            if (sender is not ComboBox comboBox) return;

            void ScrollToTop()
            {
                ScrollViewer? scrollViewer = null;

                if (comboBox.Template?.FindName("Popup", comboBox) is Popup popup)
                    scrollViewer = FindDescendantScrollViewer(popup.Child);

                scrollViewer ??= FindDescendantScrollViewer(comboBox);
                if (scrollViewer != null)
                {
                    scrollViewer.ScrollToHome();
                    scrollViewer.ScrollToVerticalOffset(0);
                }
            }

            comboBox.Dispatcher.BeginInvoke((Action)ScrollToTop, DispatcherPriority.Background);
        }

    private async void UpdateAllModsMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (_isApplyingPreset) return;

            if (_isModUpdateInProgress || _viewModel?.ModsView == null) return;

            var mods = _viewModel.ModsView.Cast<ModListItemViewModel>()
                .Where(mod => mod.CanUpdate)
                .ToList();

            Dictionary<ModListItemViewModel, ModReleaseInfo>? overrides = null;
            foreach (var mod in mods)
                if (mod.SelectedVersionOption is { Release: { } selectedRelease, IsInstalled: false })
                {
                    overrides ??= new Dictionary<ModListItemViewModel, ModReleaseInfo>();
                    overrides[mod] = selectedRelease;
                }

            if (mods.Count == 0)
            {
                WpfMessageBox.Show("All mods are already up to date.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            var dialog = new UpdateModsDialog(_userConfiguration, mods, overrides)
            {
                Owner = this
            };

            var dialogResult = dialog.ShowDialog();
            if (dialogResult != true) return;

            var selectedMods = dialog.SelectedMods;
            if (selectedMods.Count == 0) return;

            Dictionary<ModListItemViewModel, ModReleaseInfo>? selectedOverrides = null;
            if (overrides != null)
                foreach (var mod in selectedMods)
                    if (overrides.TryGetValue(mod, out var release) && release != null)
                    {
                        selectedOverrides ??= new Dictionary<ModListItemViewModel, ModReleaseInfo>();
                        selectedOverrides[mod] = release;
                    }

            await CreateAutomaticBackupAsync("ModsUpdated").ConfigureAwait(true);
            await UpdateModsAsync(selectedMods, true, selectedOverrides).ConfigureAwait(true);
        }

}
