// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private async Task OnActiveGameProfileChangedAsync()
        {
            TryInitializePaths();
            RefreshDeveloperProfilesMenuEntries();
            UpdateGameVersionMenuItem(VintageStoryVersionLocator.GetInstalledVersion(_gameDirectory));
            await ReloadViewModelAsync();
            UpdateActiveGameProfileDisplay();
            UpdateSyncToServerMenuState();
        }

    private void GameProfilesMenuItem_OnSubmenuOpened(object sender, RoutedEventArgs e)
        {
            RefreshGameProfileMenuItems();
            UpdateGameProfileMenuChecks();
        }

    private async void CreateGameProfileMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (!_userConfiguration.GameProfileCreationWarningAcknowledged)
            {
                var confirmation = WpfMessageBox.Show(
                    this,
                    "Game Profiles are specifically made to manage different Vintage Story installations, using different Data and Game folders. If you are looking for a way to easily switch between mod lists, use Modlists to swap between different mod sets. This dialog will not be shown again.",
                    "Simple VS Manager",
                    MessageBoxButton.OKCancel,
                    MessageBoxImage.Warning);

                if (confirmation != MessageBoxResult.OK) return;

                _userConfiguration.SetGameProfileCreationWarningAcknowledged(true);
            }

            var dialog = new GameProfileDialog(
                this,
                _serverTargetService,
                TestServerConnectionAsync,
                ShowHostKeyVerificationAsync,
                _userConfiguration.EnableServerOptions);
            var result = dialog.ShowDialog();
            if (result != true) return;

            var profileName = dialog.ProfileName;

            if (!_userConfiguration.TryCreateGameProfile(profileName, out var normalizedName, out var errorMessage))
            {
                if (!string.IsNullOrWhiteSpace(errorMessage))
                    WpfMessageBox.Show(errorMessage, "Simple VS Manager", MessageBoxButton.OK, MessageBoxImage.Information);

                return;
            }

            if (normalizedName is not null)
            {
                _userConfiguration.TrySetActiveGameProfile(normalizedName);

                // Set profile type and server target if this is a server profile
                _userConfiguration.SetActiveProfileType(dialog.SelectedProfileType);
                if (dialog.SelectedProfileType == ProfileType.Server && dialog.SelectedServerTargetId != null)
                {
                    _userConfiguration.SetActiveServerTargetId(dialog.SelectedServerTargetId);
                }
            }

            await OnActiveGameProfileChangedAsync().ConfigureAwait(true);
            RefreshGameProfileMenuItems();
            UpdateGameProfileMenuChecks();
        }

    private void EditGameProfileMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            var profileName = _userConfiguration.ActiveGameProfileName;
            if (string.IsNullOrEmpty(profileName))
            {
                WpfMessageBox.Show("No active profile to edit.", "Simple VS Manager", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }

            var currentProfileType = _userConfiguration.GetActiveProfileType();
            var currentServerTargetId = _userConfiguration.GetActiveServerTargetId();

            var dialog = new EditGameProfileDialog(
                this,
                profileName,
                currentProfileType,
                currentServerTargetId,
                _serverTargetService,
                TestServerConnectionAsync,
                ShowHostKeyVerificationAsync,
                _userConfiguration.EnableServerOptions);

            var result = dialog.ShowDialog();
            if (result != true) return;

            // Update profile type and server target
            _userConfiguration.SetActiveProfileType(dialog.SelectedProfileType);
            _userConfiguration.SetActiveServerTargetId(dialog.SelectedServerTargetId);

            UpdateSyncToServerMenuState();
        }

    private async void DeleteGameProfileMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            var profiles = _userConfiguration.GetGameProfileNames();
            if (profiles.Count == 0) return;

            var activeProfile = _userConfiguration.ActiveGameProfileName;
            var dialog = new DeleteGameProfilesDialog(profiles, activeProfile);
            var result = dialog.ShowDialog();
            if (result != true) return;

            var selectedProfiles = dialog.SelectedProfileNames;
            if (selectedProfiles.Count == 0) return;

            if (!_userConfiguration.TryDeleteGameProfiles(selectedProfiles, out var errorMessage,
                    out var activeProfileChanged))
            {
                if (!string.IsNullOrWhiteSpace(errorMessage))
                    WpfMessageBox.Show(errorMessage, "Simple VS Manager", MessageBoxButton.OK, MessageBoxImage.Information);

                return;
            }

            if (activeProfileChanged) await OnActiveGameProfileChangedAsync().ConfigureAwait(true);

            RefreshGameProfileMenuItems();
            UpdateGameProfileMenuChecks();
        }

    private async void GameProfileMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not MenuItem menuItem || menuItem.Tag is not string profileName) return;

            if (string.Equals(profileName, _userConfiguration.ActiveGameProfileName, StringComparison.OrdinalIgnoreCase))
            {
                menuItem.IsChecked = true;
                return;
            }

            if (!_userConfiguration.TrySetActiveGameProfile(profileName)) return;

            await OnActiveGameProfileChangedAsync().ConfigureAwait(true);
            UpdateGameProfileMenuChecks();
        }

    private async void SelectDataFolderMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            var selected = PromptForDirectory(
                "Select your VintagestoryData folder",
                _dataDirectory,
                InstallationPathValidator.TryValidateDataDirectory,
                true);

            if (selected is null) return;

            if (string.Equals(selected, _dataDirectory, StringComparison.OrdinalIgnoreCase)) return;

            _dataDirectory = selected;
            _userConfiguration.SetDataDirectory(selected);
            DeveloperProfileManager.UpdateOriginalProfile(selected);
            RefreshDeveloperProfilesMenuEntries();
            await ReloadViewModelAsync();
        }

    private void SelectGameFolderMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            var selected = PromptForDirectory(
                "Select your Vintage Story installation folder",
                _gameDirectory,
                InstallationPathValidator.TryValidateGameDirectory,
                true);

            if (selected is null) return;

            if (string.Equals(selected, _gameDirectory, StringComparison.OrdinalIgnoreCase)) return;

            _gameDirectory = selected;
            _userConfiguration.SetGameDirectory(selected);
            UpdateGameVersionMenuItem(VintageStoryVersionLocator.GetInstalledVersion(_gameDirectory));
        }

    private void RefreshDeveloperProfilesMenuEntries()
        {
            if (DeveloperProfilesMenuItem is null) return;

            foreach (var item in _developerProfileMenuItems) item.Click -= DeveloperProfileMenuItem_OnClick;

            _developerProfileMenuItems.Clear();
            DeveloperProfilesMenuItem.Items.Clear();

            if (!DeveloperProfileManager.DevDebug)
            {
                DeveloperProfilesMenuItem.Visibility = Visibility.Collapsed;
                return;
            }

            var profiles = DeveloperProfileManager.GetProfiles();
            if (profiles.Count == 0)
            {
                DeveloperProfilesMenuItem.Visibility = Visibility.Collapsed;
                return;
            }

            foreach (var profile in profiles)
            {
                var menuItem = new MenuItem
                {
                    Header = profile.DisplayName,
                    Tag = profile,
                    IsCheckable = true
                };

                menuItem.Click += DeveloperProfileMenuItem_OnClick;
                DeveloperProfilesMenuItem.Items.Add(menuItem);
                _developerProfileMenuItems.Add(menuItem);
            }

            DeveloperProfilesMenuItem.Visibility = Visibility.Visible;
            UpdateDeveloperProfileMenuChecks();
        }

    private void RefreshGameProfileMenuItems()
        {
            if (GameProfilesMenuItem is null || CreateGameProfileMenuItem is null) return;

            foreach (var item in _gameProfileMenuItems) item.Click -= GameProfileMenuItem_OnClick;

            _gameProfileMenuItems.Clear();

            GameProfilesMenuItem.Items.Clear();
            GameProfilesMenuItem.Items.Add(CreateGameProfileMenuItem);

            if (EditGameProfileMenuItem is not null) GameProfilesMenuItem.Items.Add(EditGameProfileMenuItem);

            if (DeleteGameProfileMenuItem is not null) GameProfilesMenuItem.Items.Add(DeleteGameProfileMenuItem);

            var profiles = _userConfiguration.GetGameProfileNames();
            if (DeleteGameProfileMenuItem is not null)
                DeleteGameProfileMenuItem.IsEnabled = profiles.Any(name => !_userConfiguration.IsDefaultGameProfile(name));

            if (profiles.Count > 0) GameProfilesMenuItem.Items.Add(new Separator());

            var activeName = _userConfiguration.ActiveGameProfileName;

            foreach (var profileName in profiles)
            {
                var menuItem = new MenuItem
                {
                    Header = profileName,
                    Tag = profileName,
                    IsCheckable = true,
                    Height = 35,
                    IsChecked = string.Equals(profileName, activeName, StringComparison.OrdinalIgnoreCase)
                };

                menuItem.Click += GameProfileMenuItem_OnClick;
                GameProfilesMenuItem.Items.Add(menuItem);
                _gameProfileMenuItems.Add(menuItem);
            }

            UpdateActiveGameProfileDisplay();
        }

    private void UpdateGameProfileMenuChecks()
        {
            var activeName = _userConfiguration.ActiveGameProfileName;

            foreach (var item in _gameProfileMenuItems)
                if (item.Tag is string profileName)
                    item.IsChecked = string.Equals(profileName, activeName, StringComparison.OrdinalIgnoreCase);
        }

    private void UpdateActiveGameProfileDisplay()
        {
            if (ActiveGameProfileTextBlock is null) return;

            var profiles = _userConfiguration.GetGameProfileNames();
            var hasAdditionalProfiles = profiles.Any(name => !_userConfiguration.IsDefaultGameProfile(name));
            if (!hasAdditionalProfiles)
            {
                ActiveGameProfileTextBlock.Visibility = Visibility.Collapsed;
                return;
            }

            var activeName = _userConfiguration.ActiveGameProfileName;
            if (string.IsNullOrWhiteSpace(activeName)) activeName = UserConfigurationService.DefaultProfileName;

            ActiveGameProfileTextBlock.Text = $"Profile: {activeName}";
            ActiveGameProfileTextBlock.Visibility = Visibility.Visible;
        }

    private void UpdateDeveloperProfileMenuChecks()
        {
            if (!DeveloperProfileManager.DevDebug) return;

            var current = DeveloperProfileManager.CurrentProfile;

            foreach (var menuItem in _developerProfileMenuItems)
            {
                if (menuItem.Tag is not DeveloperProfile profile)
                {
                    menuItem.IsChecked = false;
                    continue;
                }

                var isSelected = current is not null
                                 && string.Equals(profile.Id, current.Id, StringComparison.OrdinalIgnoreCase);
                menuItem.IsChecked = isSelected;
            }
        }

    private async void DeveloperProfileMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not MenuItem { Tag: DeveloperProfile profile }) return;

            var changed = DeveloperProfileManager.TrySetCurrentProfile(profile.Id);
            if (!changed)
            {
                UpdateDeveloperProfileMenuChecks();
                return;
            }

            var profileDirectory = profile.DataDirectory;

            if (string.Equals(_dataDirectory, profileDirectory, StringComparison.OrdinalIgnoreCase))
            {
                UpdateDeveloperProfileMenuChecks();
                return;
            }

            _dataDirectory = profileDirectory;

            if (profile.IsOriginal)
            {
                _userConfiguration.SetDataDirectory(profileDirectory);
                DeveloperProfileManager.UpdateOriginalProfile(profileDirectory);
            }

            _cloudModlistStore = null;
            await ReloadViewModelAsync();
            UpdateDeveloperProfileMenuChecks();
        }

    private void DeveloperProfileManager_OnCurrentProfileChanged(object? sender, DeveloperProfileChangedEventArgs e)
        {
            if (!DeveloperProfileManager.DevDebug) return;

            if (!Dispatcher.CheckAccess())
            {
                Dispatcher.Invoke(() => DeveloperProfileManager_OnCurrentProfileChanged(sender, e));
                return;
            }

            if (e.ProfilesUpdated)
                RefreshDeveloperProfilesMenuEntries();
            else
                UpdateDeveloperProfileMenuChecks();
        }

    private void ExitMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            Close();
        }
}
