// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private void RefreshModDetailsOnly()
        {
            if (_viewModel == null) return;

            _viewModel.ForceNextRefreshToLoadDetails();
            _viewModel.RefreshInstalledModDetails();
        }

    private bool TryInitializePaths()
        {
            var dataResolved = TryResolveDataDirectory();
            var gameResolved = TryResolveGameDirectory();
            TryResolveCustomShortcut();

            if (dataResolved)
            {
                _userConfiguration.SetDataDirectory(_dataDirectory!);
                DeveloperProfileManager.UpdateOriginalProfile(_dataDirectory!);
            }

            if (gameResolved) _userConfiguration.SetGameDirectory(_gameDirectory!);

            return dataResolved && gameResolved;
        }

    private bool TryResolveDataDirectory()
        {
            var requiresSelection = _userConfiguration.RequiresDataDirectorySelection;
            var storedPath = _userConfiguration.DataDirectory;
            if (!requiresSelection && InstallationPathValidator.TryValidateDataDirectory(storedPath, out _dataDirectory, out _)) return true;

            if (!string.IsNullOrWhiteSpace(storedPath)) _userConfiguration.ClearDataDirectory();

            var defaultPath = DataDirectoryLocator.Resolve();
            if (!requiresSelection && InstallationPathValidator.TryValidateDataDirectory(defaultPath, out _dataDirectory, out _)) return true;

            var promptMessage = requiresSelection
                ? "Select the Vintage Story data folder for this profile to enable mod management."
                : "The Vintage Story data folder could not be located. Please select it to enable mod management.";

            WpfMessageBox.Show(promptMessage,
                "Simple VS Manager",
                MessageBoxButton.OK,
                MessageBoxImage.Information);

            _dataDirectory = PromptForDirectory(
                "Select your VintagestoryData folder",
                _userConfiguration.DataDirectory ?? defaultPath,
                InstallationPathValidator.TryValidateDataDirectory,
                true);

            if (_dataDirectory is null)
            {
                WpfMessageBox.Show(
                    "Mods cannot be managed until a VintagestoryData folder is selected. You can set it later from File > Set Data Folder.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return false;
            }

            return true;
        }

    private bool TryResolveGameDirectory()
        {
            var requiresSelection = _userConfiguration.RequiresGameDirectorySelection;
            var storedPath = _userConfiguration.GameDirectory;
            if (!requiresSelection && InstallationPathValidator.TryValidateGameDirectory(storedPath, out _gameDirectory, out _)) return true;

            if (!string.IsNullOrWhiteSpace(storedPath)) _userConfiguration.ClearGameDirectory();

            var defaultPath = GameDirectoryLocator.Resolve();
            if (!requiresSelection
                && !string.IsNullOrWhiteSpace(defaultPath)
                && InstallationPathValidator.TryValidateGameDirectory(defaultPath, out _gameDirectory, out _))
                return true;

            var promptMessage = requiresSelection
                ? "Select the Vintage Story installation folder for this profile to enable game-related features."
                : "The Vintage Story installation folder could not be located. Please select it to enable game-related features.";

            WpfMessageBox.Show(promptMessage,
                "Simple VS Manager",
                MessageBoxButton.OK,
                MessageBoxImage.Information);

            _gameDirectory = PromptForDirectory(
                "Select your Vintage Story installation folder",
                _userConfiguration.GameDirectory ?? (string.IsNullOrWhiteSpace(defaultPath) ? null : defaultPath),
                InstallationPathValidator.TryValidateGameDirectory,
                true);

            if (_gameDirectory is null)
            {
                WpfMessageBox.Show(
                    "Game-related features will be unavailable until a Vintage Story installation folder is selected. You can set it later from File > Set Game Folder.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return false;
            }

            return true;
        }

    private void TryResolveCustomShortcut()
        {
            var storedPath = _userConfiguration.CustomShortcutPath;
            if (string.IsNullOrWhiteSpace(storedPath))
            {
                _customShortcutPath = null;
                return;
            }

            if (File.Exists(storedPath))
            {
                _customShortcutPath = storedPath;
                return;
            }

            _customShortcutPath = null;
            _userConfiguration.ClearCustomShortcutPath();

            WpfMessageBox.Show(
                "The previously selected Vintage Story shortcut could not be found and has been cleared.",
                "Simple VS Manager",
                MessageBoxButton.OK,
                MessageBoxImage.Information);
        }

    private void HandleViewModelInitializationFailure(Exception exception)
        {
            _modActivityLoggingService.LogError("Failed to initialize view model", exception);
            DisposeCurrentViewModel();

            if (_dataDirectory != null) _userConfiguration.ClearDataDirectory();

            _dataDirectory = null;

            var message = $"Failed to initialize the mod manager:\n{exception.Message}\n\n" +
                          "You can set the Vintage Story folders from the File menu once the application has loaded.";

            WpfMessageBox.Show(message,
                "Simple VS Manager",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
        }

    private async Task ReloadViewModelAsync()
        {
            if (string.IsNullOrWhiteSpace(_dataDirectory))
            {
                await RefreshDeleteCachedModsMenuHeaderAsync();
                return;
            }

            StopModsWatcher();
            StopGameSessionMonitor();

            var previousViewModel = _viewModel;
            if (previousViewModel is not null)
            {
                previousViewModel.PropertyChanged -= ViewModelOnPropertyChanged;
                previousViewModel.UserReportVoteSubmitted -= OnUserReportVoteSubmitted;
            }

            MainViewModel? newViewModel = null;

            try
            {
                newViewModel = new MainViewModel(
                    _dataDirectory,
                    _userConfiguration,
                    _gameDirectory);
                newViewModel.IsCompactView = _userConfiguration.IsCompactView;
                newViewModel.UseModDbDesignView = _userConfiguration.UseModDbDesignView;
                newViewModel.PropertyChanged += ViewModelOnPropertyChanged;
                newViewModel.UserReportVoteSubmitted += OnUserReportVoteSubmitted;
                _viewModel = newViewModel;
                ApplyColumnVisibilityPreferencesToViewModel();
                UpdateGameVersionMenuItem(newViewModel.InstalledGameVersion);
                DataContext = newViewModel;
                ApplyPlayerIdentityToUiAndCloudStore();
                AttachToModsView(newViewModel.CurrentModsView);
                await InitializeViewModelAsync(newViewModel);

                DisposeViewModel(previousViewModel);
            }
            catch (Exception ex)
            {
                DisposeViewModel(newViewModel);

                if (previousViewModel is not null)
                {
                    _viewModel = previousViewModel;
                    previousViewModel.PropertyChanged += ViewModelOnPropertyChanged;
                    previousViewModel.UserReportVoteSubmitted += OnUserReportVoteSubmitted;
                    DataContext = previousViewModel;
                    ApplyPlayerIdentityToUiAndCloudStore();
                    AttachToModsView(previousViewModel.CurrentModsView);
                    StartModsWatcher();
                }

                WpfMessageBox.Show($"Failed to reload mods:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }

            await RefreshDeleteCachedModsMenuHeaderAsync();
        }

}
