// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private void InternetAccessManager_OnInternetAccessChanged(object? sender, EventArgs e)
        {
            void Update()
            {
                UpdateCloudModlistControlsEnabledState();
                _ = RefreshManagerUpdateLinkAsync();
            }

            if (Dispatcher.CheckAccess())
                Update();
            else
                Dispatcher.BeginInvoke(DispatcherPriority.Normal, (Action)Update);
        }

    private bool EnsureCloudModlistsConsent()
        {
            var message =
                "In this tab you can easily save and load Modlists from an online database (Google Firebase), for free." +
                Environment.NewLine + Environment.NewLine +
                "When you continue, Simple VS Manager will create a firebase-auth.json (basically just a code that identifies you as the owner of your uploaded modlists) file in its configuration folder. " +
                "If you lose this file you will not be able to delete or modify your uploaded online modlists." +
                Environment.NewLine + Environment.NewLine +
                "You will not need to sign in or provide any account information or do anything really :) Press OK to continue and never show this again!";

            return EnsureFirebaseAuthConsent(message);
        }

    private bool EnsureFirebaseAuthConsent(string message)
        {
            var stateFilePath = FirebaseAnonymousAuthenticator.GetStateFilePath();
            if (string.IsNullOrWhiteSpace(stateFilePath)) return true;

            if (File.Exists(stateFilePath))
            {
                EnsureFirebaseAuthBackedUpIfAvailable();
                return true;
            }

            var buttonOverrides = new MessageDialogButtonContentOverrides
            {
                Cancel = "No thanks"
            };

            var result = WpfMessageBox.Show(
                this,
                message,
                "Simple VS Manager",
                MessageBoxButton.OKCancel,
                MessageBoxImage.Information,
                buttonContentOverrides: buttonOverrides);

            return result == MessageBoxResult.OK;
        }

    private bool EnsureUserReportVotingConsent()
        {
            var message =
                "To enable voting, Simple VS Manager will create a firebase-auth.json (basically just a code that identifies you as the owner of your mod compatibility votes) file in its configuration folder. " +
                "If you lose this file you will not be able to manage or remove your mod compatibility votes." +
                Environment.NewLine + Environment.NewLine +
                "You will not need to sign in or provide any account information or do anything really :) Press OK to continue and never show this again!";

            return EnsureFirebaseAuthConsent(message);
        }

    private void EnsureFirebaseAuthBackedUpIfAvailable()
        {
            var stateFilePath = FirebaseAnonymousAuthenticator.GetStateFilePath();
            if (string.IsNullOrWhiteSpace(stateFilePath) || !File.Exists(stateFilePath)) return;

            var dataDirectory = _dataDirectory;
            if (string.IsNullOrWhiteSpace(dataDirectory)) return;

            var modDataDirectory = Path.Combine(dataDirectory, "ModData");
            var backupDirectory = Path.Combine(modDataDirectory, "SimpleVSManager");
            var backupPath = Path.Combine(backupDirectory, "firebase-auth.json");

            try
            {
                Directory.CreateDirectory(backupDirectory);
                File.Copy(stateFilePath, backupPath, true);
            }
            catch (IOException ex)
            {
                _modActivityLoggingService.LogError("Failed to back up Firebase auth state", ex);
                StatusLogService.AppendStatus($"Failed to back up Firebase auth state: {ex.Message}", true);
            }
            catch (UnauthorizedAccessException ex)
            {
                _modActivityLoggingService.LogError("Failed to back up Firebase auth state", ex);
                StatusLogService.AppendStatus($"Failed to back up Firebase auth state: {ex.Message}", true);
            }
            catch (NotSupportedException ex)
            {
                _modActivityLoggingService.LogError("Failed to back up Firebase auth state", ex);
                StatusLogService.AppendStatus($"Failed to back up Firebase auth state: {ex.Message}", true);
            }
        }

    private void DeleteFirebaseAuthFiles()
        {
            var stateFilePath = FirebaseAnonymousAuthenticator.GetStateFilePath();
            if (!string.IsNullOrWhiteSpace(stateFilePath)) FirebaseAuthFileService.TryDeleteFirebaseAuthFile(stateFilePath);

            var dataDirectory = _dataDirectory;
            if (string.IsNullOrWhiteSpace(dataDirectory)) return;

            var backupDirectory = Path.Combine(dataDirectory, "ModData", "SimpleVSManager");
            var backupPath = Path.Combine(backupDirectory, "firebase-auth.json");
            FirebaseAuthFileService.TryDeleteFirebaseAuthFile(backupPath);
        }

    private void RestoreFirebaseAuthBackupMenuItem_OnClick(
        object sender,
        RoutedEventArgs e)
    {
        const string confirmationMessage =
            "This will copy the firebase-auth.json file from the SVSM Backup folder " +
            "(AppData/Local/SVSM Backup) into the Simple VS Manager folder and replace the current file.\n\n" +
            "Use this if you lost access to online modlists or votes after moving or deleting files.\n\n" +
            "Continue?";

        var confirmation = WpfMessageBox.Show(
            this,
            confirmationMessage,
            "Simple VS Manager",
            MessageBoxButton.OKCancel,
            MessageBoxImage.Question);

        if (confirmation != MessageBoxResult.OK) return;

        try
        {
            var restoreResult =
                FirebaseAuthFileService.RestoreFirebaseAuthBackup();

            switch (restoreResult)
            {
                case FirebaseAuthRestoreResult.BackupLocationUnavailable:
                    WpfMessageBox.Show(
                        this,
                        "Could not determine the location of the firebase-auth.json backup.",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Error);
                    break;

                case FirebaseAuthRestoreResult.BackupNotFound:
                    WpfMessageBox.Show(
                        this,
                        "No firebase-auth.json backup was found in the SVSM Backup folder.",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Warning);
                    break;

                case FirebaseAuthRestoreResult.StateLocationUnavailable:
                    WpfMessageBox.Show(
                        this,
                        "Could not determine the Simple VS Manager folder for firebase-auth.json.",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Error);
                    break;

                case FirebaseAuthRestoreResult.Restored:
                    WpfMessageBox.Show(
                        this,
                        "Restored firebase-auth.json from the SVSM Backup folder.",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Information);
                    break;

                default:
                    throw new ArgumentOutOfRangeException();
            }
        }
        catch (Exception ex) when (
            ex is IOException or
            UnauthorizedAccessException or
            NotSupportedException or
            SecurityException)
        {
            WpfMessageBox.Show(
                this,
                $"Failed to restore firebase-auth.json: {ex.Message}",
                "Simple VS Manager",
                MessageBoxButton.OK,
                MessageBoxImage.Error);
        }
    }
}
