// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private void HelpMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            var managerDirectory = _userConfiguration.GetConfigurationDirectory();
            var cachedModsDirectory = ModCacheLocator.GetCachedModsDirectory();

            var dialog = new HelpDialogWindow(managerDirectory, cachedModsDirectory)
            {
                Owner = this
            };

            _ = dialog.ShowDialog();
        }

    private void GuideMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            var managerDirectory = _userConfiguration.GetConfigurationDirectory();
            var configurationFilePath = Path.Combine(managerDirectory, "SimpleVSManagerConfiguration.json");
            var cachedModsDirectory = ModCacheLocator.GetCachedModsDirectory();

            var dialog = new GuideDialogWindow(managerDirectory, cachedModsDirectory, configurationFilePath)
            {
                Owner = this
            };

            _ = dialog.ShowDialog();
        }

    private async void ScanForModConfigsMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (_viewModel is null)
            {
                WpfMessageBox.Show(
                    "Mods have not been loaded yet. Load mods before scanning for configuration files.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            if (_viewModel.IsBusy)
            {
                WpfMessageBox.Show(
                    "Please wait for the current operation to finish before scanning for configuration files.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            if (string.IsNullOrWhiteSpace(_dataDirectory))
            {
                WpfMessageBox.Show(
                    "The Vintage Story data directory is not set, so mod configuration files cannot be located.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            var configDirectory = Path.Combine(_dataDirectory, "ModConfig");
            if (!Directory.Exists(configDirectory))
            {
                WpfMessageBox.Show(
                    $"No mod configuration directory was found at:\n{configDirectory}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            try
            {
                var results =
                    await ScanForModConfigFilesAsync(_viewModel).ConfigureAwait(true);

                if (results.Count == 0)
                {
                    _viewModel.ReportStatus("No missing mod configuration files were found.");
                    WpfMessageBox.Show(
                        "No missing mod configuration files were found.",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Information);
                    return;
                }

                _viewModel.ReportStatus($"Assigned configuration files for {results.Count} mod(s).");

                var builder = new StringBuilder();
                builder.AppendLine("Assigned configuration files for the following mods:");
                foreach (var result in results
                             .OrderBy(r => r.DisplayName, StringComparer.CurrentCultureIgnoreCase))
                {
                    builder.Append(" • ");
                    builder.Append(result.DisplayName);
                    if (!string.Equals(result.DisplayName, result.ModId, StringComparison.OrdinalIgnoreCase))
                    {
                        builder.Append(" (");
                        builder.Append(result.ModId);
                        builder.Append(')');
                    }

                    builder.AppendLine();
                    builder.Append("    ");
                    var configFileName = Path.GetFileName(result.ConfigPath);
                    builder.AppendLine(string.IsNullOrEmpty(configFileName) ? result.ConfigPath : configFileName);
                }

                WpfMessageBox.Show(
                    builder.ToString(),
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
            }
            catch (Exception ex)
            {
                WpfMessageBox.Show(
                    $"Failed to scan for mod configuration files:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }

    private void ManagerUpdateLink_OnRequestNavigate(object sender, RequestNavigateEventArgs e)
        {
            e.Handled = true;
            OpenManagerModDatabasePage();
        }

    private void DiscordButton_OnClick(object sender, RoutedEventArgs e)
        {
            if (e is not null)
            {
                e.Handled = true;
            }

            if (InternetAccessManager.IsInternetAccessDisabled)
            {
                WpfMessageBox.Show(
                    "Enable Internet Access in the File menu to open Discord.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            try
            {
                Process.Start(new ProcessStartInfo
                {
                    FileName = DiscordInviteUrl,
                    UseShellExecute = true
                });
            }
            catch (Exception ex)
            {
                WpfMessageBox.Show(
                    $"Failed to open Discord:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }

    private async void ModUsagePromptLink_OnClick(object sender, RoutedEventArgs e)
        {
            if (e is not null) e.Handled = true;

            await ShowModUsagePromptDialogAsync().ConfigureAwait(true);
        }

    private void OpenManagerModDatabasePage()
        {
            if (InternetAccessManager.IsInternetAccessDisabled)
            {
                WpfMessageBox.Show(
                    "Internet access is disabled. Enable Internet Access in the File menu to open the mod database page.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            try
            {
                Process.Start(new ProcessStartInfo
                {
                    FileName = ManagerModDatabaseUrl,
                    UseShellExecute = true
                });
            }
            catch (Exception ex)
            {
                WpfMessageBox.Show(
                    $"Failed to open the mod database page:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }
}
