// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private void BeginModlistInstallUi(int totalSteps, string message)
        {
            _modlistInstallTotalSteps = Math.Max(1, totalSteps);
            _modlistInstallCompletedSteps = 0;
            ModlistInstallProgress = 0;
            ModlistInstallStatusMessage = message;
            UpdateModlistDownloadSpeed(null);
            IsModlistInstallInProgress = true;
        }

    private void UpdateModlistInstallUi(string status, double? stepPercent, double? bytesPerSecond)
        {
            if (!IsModlistInstallInProgress) return;

            var clampedPercent = ClampPercent(stepPercent);
            var progress = (_modlistInstallCompletedSteps + clampedPercent / 100d) / _modlistInstallTotalSteps * 100d;

            ModlistInstallProgress = Math.Clamp(progress, 0, 100);
            ModlistInstallStatusMessage = status;
            UpdateModlistDownloadSpeed(bytesPerSecond);
        }

    private void CompleteModlistInstallStep(string status)
        {
            if (!IsModlistInstallInProgress) return;

            _modlistInstallCompletedSteps = Math.Min(_modlistInstallCompletedSteps + 1, _modlistInstallTotalSteps);
            ModlistInstallProgress = (double)_modlistInstallCompletedSteps / _modlistInstallTotalSteps * 100d;
            ModlistInstallStatusMessage = status;
            UpdateModlistDownloadSpeed(null);
        }

    private void EndModlistInstallUi()
        {
            IsModlistInstallInProgress = false;
            ModlistInstallProgress = 0;
            ModlistInstallStatusMessage = string.Empty;
            UpdateModlistDownloadSpeed(null);
            _modlistInstallCompletedSteps = 0;
            _modlistInstallTotalSteps = 0;
        }

    private static double ClampPercent(double? value)
        {
            if (!value.HasValue || double.IsNaN(value.Value)) return 0;
            return Math.Clamp(value.Value, 0, 100);
        }

    private void UpdateModlistDownloadSpeed(double? bytesPerSecond)
        {
            if (bytesPerSecond.HasValue && bytesPerSecond.Value > 0)
            {
                ModlistDownloadSpeed = ProgressDisplayFormatter.FormatDownloadSpeed(bytesPerSecond.Value);
                HasModlistDownloadSpeed = true;
                return;
            }

            ModlistDownloadSpeed = string.Empty;
            HasModlistDownloadSpeed = false;
        }

    private IProgress<ModUpdateProgress> CreateModlistInstallProgressReporter(string modDisplayName)
        {
            var display = string.IsNullOrWhiteSpace(modDisplayName) ? "Mod" : modDisplayName;

            return new Progress<ModUpdateProgress>(p =>
            {
                var status = $"{display}: {p.Message}";
                var bytesPerSecond = p.Stage == ModUpdateStage.Downloading ? p.BytesPerSecond : null;
                UpdateModlistInstallUi(status, p.Percent, bytesPerSecond);
            });
        }

    private IProgress<ModUpdateProgress> CreateModUpdateProgressReporter(string modDisplayName,
            IProgress<ModUpdateProgress>? additionalProgress = null)
        {
            var display = string.IsNullOrWhiteSpace(modDisplayName) ? "Mod" : modDisplayName;

            return new Progress<ModUpdateProgress>(p =>
            {
                additionalProgress?.Report(p);
                _viewModel?.ReportStatus($"{display}: {p.Message}");
            });
        }
}
