// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{



    private void ManagerModDbPageMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            OpenManagerModDatabasePage();
        }






    private async void DeleteAllManagerFilesMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            const string confirmationMessage =
                "This will move every file Simple VS Manager created to the Recycle Bin, including its configuration folder, any ModData backups, cached mods, presets, and Firebase authentication tokens.\n\n" +
                "You can restore them from the Recycle Bin if needed. Continue?";

            var confirmation = WpfMessageBox.Show(
                this,
                confirmationMessage,
                "Simple VS Manager",
                MessageBoxButton.OKCancel,
                MessageBoxImage.Warning);

            if (confirmation != MessageBoxResult.OK) return;

            await ExecuteCloudOperationAsync(
                store => DeleteAllCloudModlistsAndAuthorizationAsync(store, false),
                "delete the Firebase user and cloud data");

            var dataDirectory = _dataDirectory;
            var deletionResult = await Task.Run(() => ManagerDataDeletionService.DeleteAllManagerFiles(dataDirectory)).ConfigureAwait(true);

            if (deletionResult.DeletedPaths.Count == 0 && deletionResult.FailedPaths.Count == 0)
            {
                WpfMessageBox.Show(
                    this,
                    "No Simple VS Manager files were found.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                SwitchToInstalledModsTab();
                return;
            }

            var builder = new StringBuilder();

            if (deletionResult.DeletedPaths.Count > 0)
            {
                builder.AppendLine("Moved the following locations to the Recycle Bin:");
                foreach (var path in deletionResult.DeletedPaths) builder.AppendLine($"• {path}");
            }

            if (deletionResult.FailedPaths.Count == 0)
            {
                var message = builder.Length > 0
                    ? builder.ToString()
                    : "Finished moving Simple VS Manager files to the Recycle Bin.";

                WpfMessageBox.Show(
                    this,
                    message,
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                SwitchToInstalledModsTab();
                return;
            }

            if (builder.Length > 0) builder.AppendLine();

            builder.AppendLine(
                "The following locations could not be moved to the Recycle Bin. Please remove them manually:");
            foreach (var path in deletionResult.FailedPaths) builder.AppendLine($"• {path}");

            WpfMessageBox.Show(
                this,
                builder.ToString(),
                "Simple VS Manager",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
            SwitchToInstalledModsTab();
        }



    private async Task RefreshModsWithErrorHandlingAsync()
        {
            if (_viewModel == null) return;

            if (Dispatcher.CheckAccess())
                await Dispatcher.Yield(DispatcherPriority.Background);
            else
                await Task.Yield();

            if (_userConfiguration.DisableAutoRefresh)
                _viewModel.EnableUserReportFetching(true);

            try
            {
                RefreshModDetailsOnly();
            }
            catch (Exception ex)
            {
                WpfMessageBox.Show(
                    $"Failed to refresh mod details:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }

}
