// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private async void CheckModsCompatibilityMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            var viewModel = _viewModel;
            if (viewModel is null) return;

            if (InternetAccessManager.IsInternetAccessDisabled)
            {
                WpfMessageBox.Show(
                    "Enable Internet Access in the File menu to check mod compatibility.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
                return;
            }

            IReadOnlyList<string> recentVersions;
            try
            {
                recentVersions = await VintageStoryGameVersionService
                    .GetRecentReleaseVersionsAsync(10)
                    .ConfigureAwait(true);
            }
            catch (HttpRequestException ex)
            {
                WpfMessageBox.Show(
                    $"Failed to retrieve Vintage Story versions:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return;
            }
            catch (TaskCanceledException)
            {
                return;
            }
            catch (Exception ex)
            {
                WpfMessageBox.Show(
                    $"Failed to retrieve Vintage Story versions:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return;
            }

            if (recentVersions is not { Count: > 0 })
            {
                WpfMessageBox.Show(
                    "Could not determine recent Vintage Story versions.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
                return;
            }

            var versionSelectionDialog = new VintageStoryVersionSelectionDialog(
                this,
                recentVersions,
                viewModel.InstalledGameVersion);
            var selectionResult = versionSelectionDialog.ShowDialog();
            if (selectionResult != true) return;

            var targetVersion = versionSelectionDialog.SelectedVersion;
            if (string.IsNullOrWhiteSpace(targetVersion)) return;

            targetVersion = targetVersion.Trim();

            var mods = viewModel.GetInstalledModsSnapshot();
            if (mods.Count == 0)
            {
                WpfMessageBox.Show(
                    $"Vintage Story version: {targetVersion}.\n\nNo installed mods were found.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            var incompatible = new List<string>();
            var unknown = new List<string>();

            foreach (var mod in mods)
            {
                if (mod is null) continue;

                var displayName = string.IsNullOrWhiteSpace(mod.DisplayName)
                    ? mod.ModId ?? "Unknown mod"
                    : mod.DisplayName!;

                var evaluation = EvaluateCompatibility(mod, targetVersion, displayName,
                    _userConfiguration.RequireExactVsVersionMatch);
                if (evaluation.IsCompatible) continue;

                if (evaluation.IsUnknown)
                    unknown.Add(displayName);
                else
                    incompatible.Add(displayName);
            }

            incompatible.Sort(StringComparer.CurrentCultureIgnoreCase);
            unknown.Sort(StringComparer.CurrentCultureIgnoreCase);

            var resultsDialog = new CompatibilityResultsDialog(this, targetVersion, incompatible, unknown);
            _ = resultsDialog.ShowDialog();
        }

    private static CompatibilityEvaluation EvaluateCompatibility(
            ModListItemViewModel mod,
            string targetVersion,
            string displayName,
            bool requireExactMatch)
        {
            var installedVersion = string.IsNullOrWhiteSpace(mod.Version)
                ? "Unknown"
                : mod.Version!;

            var installedOption = mod.VersionOptions
                .FirstOrDefault(option => option is { IsInstalled: true });
            var installedRelease = installedOption?.Release;

            var releases = mod.VersionOptions
                .Select(option => option.Release)
                .Where(release => release != null)
                .GroupBy(release => release!.Version, StringComparer.OrdinalIgnoreCase)
                .Select(group => group.First()!)
                .ToList();

            var compatibleRelease = releases
                .FirstOrDefault(release => ReleaseSupportsVersion(release, targetVersion, requireExactMatch));

            if (installedRelease != null)
            {
                if (ReleaseSupportsVersion(installedRelease, targetVersion, requireExactMatch))
                    return CompatibilityEvaluation.Compatible;

                if (compatibleRelease != null
                    && !string.Equals(compatibleRelease.Version, installedRelease.Version,
                        StringComparison.OrdinalIgnoreCase))
                {
                    var message =
                        $"{displayName}: Installed version {installedRelease.Version} is not marked as compatible with Vintage Story {targetVersion}. Update to version {compatibleRelease.Version} or later.";
                    return CompatibilityEvaluation.Incompatible(message);
                }

                if (installedRelease.GameVersionTags is { Count: > 0 })
                {
                    var message =
                        $"{displayName}: Installed version {installedVersion} is not marked as compatible with Vintage Story {targetVersion}. No compatible update was found.";
                    return CompatibilityEvaluation.Incompatible(message);
                }
            }

            if (compatibleRelease != null)
            {
                var message =
                    $"{displayName}: Installed version {installedVersion} is not marked as compatible with Vintage Story {targetVersion}. Update to version {compatibleRelease.Version} or later.";
                return CompatibilityEvaluation.Incompatible(message);
            }

            var dependencies = mod.Dependencies ?? Array.Empty<ModDependencyInfo>();
            var hasGameDependency = false;

            foreach (var dependency in dependencies)
            {
                if (dependency is null || !dependency.IsGameOrCoreDependency ||
                    string.IsNullOrWhiteSpace(dependency.Version)) continue;

                hasGameDependency = true;
                if (!VersionStringUtility.SatisfiesMinimumVersion(dependency.Version, targetVersion))
                {
                    var message =
                        $"{displayName}: Requires Vintage Story {dependency.Version} or newer.";
                    return CompatibilityEvaluation.Incompatible(message);
                }
            }

            if (hasGameDependency) return CompatibilityEvaluation.Compatible;

            var unknownMessage =
                $"{displayName}: No compatibility metadata is available for Vintage Story {targetVersion}.";
            return CompatibilityEvaluation.Unknown(unknownMessage);
        }

    private static bool ReleaseSupportsVersion(ModReleaseInfo release, string targetVersion, bool requireExactMatch)
        {
            if (release.GameVersionTags is not { Count: > 0 }) return false;

            foreach (var tag in release.GameVersionTags)
            {
                if (string.IsNullOrWhiteSpace(tag)) continue;

                if (VersionStringUtility.SupportsVersion(tag, targetVersion, requireExactMatch)) return true;
            }

            return false;
        }

    private async void ModsMenuItem_OnSubmenuOpened(object sender, RoutedEventArgs e)
        {
            await RefreshDeleteCachedModsMenuHeaderAsync();
        }

    private async void ExperimentalCompReviewMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (_viewModel?.SelectedMod is not ModListItemViewModel selectedMod)
            {
                WpfMessageBox.Show(
                    "Select a mod first!",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            var modSlug = ResolveExperimentalCompReviewIdentifier(selectedMod);
            var latestVersion = string.IsNullOrWhiteSpace(_viewModel?.InstalledGameVersion)
                ? null
                : _viewModel!.InstalledGameVersion;

            try
            {
                Mouse.OverrideCursor = Cursors.Wait;

                var result = await _modCompatibilityCommentsService
                    .GetTop3CommentsAsync(modSlug, latestVersion)
                    .ConfigureAwait(true);

                var messageText = BuildExperimentalCompReviewMessage(result);
                if (string.IsNullOrWhiteSpace(messageText))
                    messageText = result.Reason ?? "No relevant comments were found.";

                var title = string.Format(
                    CultureInfo.CurrentCulture,
                    "Compatibility comments for {0}",
                    selectedMod.DisplayName);

                WpfMessageBox.Show(
                    messageText,
                    title,
                    MessageBoxButton.OK,
                    result.Top3.Count > 0 ? MessageBoxImage.Information : MessageBoxImage.Warning);
            }
            catch (InternetAccessDisabledException ex)
            {
                WpfMessageBox.Show(
                    ex.Message,
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
            }
            catch (Exception ex)
            {
                WpfMessageBox.Show(
                    $"The experimental compatibility review failed:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
            finally
            {
                Mouse.OverrideCursor = null;
            }
        }

    private static string BuildExperimentalCompReviewMessage(
            ModCompatibilityCommentsService.ExperimentalCompReviewResult result)
        {
            if (result.Top3 is not { Count: > 0 }) return result.Reason ?? string.Empty;

            var builder = new StringBuilder();
            for (var index = 0; index < result.Top3.Count; index++)
            {
                var comment = result.Top3[index];
                var totalScore = comment.ScoreBreakdown?.Values.Sum() ?? 0;
                var scoreText = FormatExperimentalCompReviewScore(totalScore);

                builder.Append(index + 1);
                builder.Append(". [");
                builder.Append(scoreText);
                builder.Append("] ");
                builder.AppendLine(comment.Snippet);
            }

            return builder.ToString().TrimEnd();
        }

    private static string FormatExperimentalCompReviewScore(double score)
        {
            var rounded = Math.Round(score, 2);
            return rounded.ToString("+0.##;-0.##;0", CultureInfo.CurrentCulture);
        }

    private async void DeleteCloudAuthMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            const string confirmationMessage =
                "This will remove all your online modlists and delete your authorization - good for resetting if something has gone wrong. Visit the Modlists (Beta) tab again to get a fresh firebase-auth";

            var result = WpfMessageBox.Show(
                this,
                confirmationMessage,
                "Simple VS Manager",
                MessageBoxButton.OKCancel,
                MessageBoxImage.Warning);

            if (result != MessageBoxResult.OK) return;

            await ExecuteCloudOperationAsync(
                store => DeleteAllCloudModlistsAndAuthorizationAsync(store),
                "delete all cloud modlists and Firebase authorization");
        }

    private static string ResolveExperimentalCompReviewIdentifier(ModListItemViewModel selectedMod)
        {
            var fromUrl = TryExtractModSlug(selectedMod.ModDatabasePageUrl);
            if (!string.IsNullOrWhiteSpace(fromUrl)) return fromUrl!;

            if (!string.IsNullOrWhiteSpace(selectedMod.ModDatabaseAssetId)) return selectedMod.ModDatabaseAssetId!;

            return selectedMod.ModId;
        }

    private static string? TryExtractModSlug(string? modDatabasePageUrl)
        {
            if (string.IsNullOrWhiteSpace(modDatabasePageUrl)) return null;

            if (Uri.TryCreate(modDatabasePageUrl, UriKind.Absolute, out var uri))
            {
                var fromUri = ExtractSlugFromPath(uri.AbsolutePath);
                if (!string.IsNullOrWhiteSpace(fromUri)) return fromUri;
            }

            return ExtractSlugFromPath(modDatabasePageUrl);

            static string? ExtractSlugFromPath(string? path)
            {
                if (string.IsNullOrWhiteSpace(path)) return null;

                var trimmed = path.Trim();

                var fragmentIndex = trimmed.IndexOf('#');
                if (fragmentIndex >= 0) trimmed = trimmed[..fragmentIndex];

                var queryIndex = trimmed.IndexOf('?');
                if (queryIndex >= 0) trimmed = trimmed[..queryIndex];

                trimmed = trimmed.Trim('/');

                if (string.IsNullOrWhiteSpace(trimmed)) return null;

                var lastSlash = trimmed.LastIndexOf('/');
                if (lastSlash >= 0) trimmed = trimmed[(lastSlash + 1)..];

                return string.IsNullOrWhiteSpace(trimmed) ? null : trimmed;
            }
        }

    private readonly struct CompatibilityEvaluation
        {
            private CompatibilityEvaluation(bool isCompatible, bool isUnknown, string? message)
            {
                IsCompatible = isCompatible;
                IsUnknown = isUnknown;
                Message = message;
            }

            public bool IsCompatible { get; }

            public bool IsUnknown { get; }

            public string? Message { get; }

            public static CompatibilityEvaluation Compatible { get; } = new(true, false, null);

            public static CompatibilityEvaluation Incompatible(string message)
            {
                return new CompatibilityEvaluation(false, false, message);
            }

            public static CompatibilityEvaluation Unknown(string message)
            {
                return new CompatibilityEvaluation(false, true, message);
            }
        }
}
