// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private void SelectedModCopyForServerButton_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not WpfButton { DataContext: ModListItemViewModel mod }) return;

            var command = ServerCommandBuilder.TryBuildInstallCommand(mod.ModId, mod.Version);
            if (string.IsNullOrWhiteSpace(command)) return;

            try
            {
                WinForms.Clipboard.SetDataObject(command, true, 10, 100);
                var trimmedCommand = command.Trim();
                var statusMessage = $"Copied {trimmedCommand}";
                _viewModel?.ReportStatus(statusMessage);
            }
            catch (ExternalException ex)
            {
                var errorMessage = $"Failed to copy server install command for {mod.DisplayName}: {ex.Message}";
                _viewModel?.ReportStatus(errorMessage, true);
                WpfMessageBox.Show(
                    this,
                    "Failed to copy the server install command. Please try again.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }

    private void EditConfigButton_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not WpfButton { DataContext: ModListItemViewModel mod }) return;

            e.Handled = true;

            if (string.IsNullOrWhiteSpace(mod.ModId)) return;

            var configPaths = _userConfiguration
                .GetModConfigPaths(mod.ModId)
                .Where(path => !string.IsNullOrWhiteSpace(path))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList();

            try
            {
                for (var i = configPaths.Count - 1; i >= 0; i--)
                {
                    var path = configPaths[i];
                    if (File.Exists(path)) continue;

                    configPaths.RemoveAt(i);
                    _userConfiguration.RemoveModConfigPath(mod.ModId, path);
                }

                if (configPaths.Count == 0)
                {
                    var primaryPath = PromptForConfigFile(mod, configPaths.FirstOrDefault());
                    if (primaryPath is null) return;

                    configPaths.Add(primaryPath);
                    _userConfiguration.SetModConfigPaths(mod.ModId, configPaths);
                    UpdateSelectedModEditConfigButton(mod);
                }
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or ArgumentException)
            {
                WpfMessageBox.Show($"Failed to store the configuration path:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return;
            }

            try
            {
                var editorViewModel = new ModConfigEditorViewModel(mod.DisplayName, configPaths);
                var editorWindow = new ModConfigEditorWindow(editorViewModel)
                {
                    Owner = this
                };

                var result = editorWindow.ShowDialog();
                if (result == true)
                {
                    var updatedPaths = editorViewModel.ConfigPaths.Where(path => !string.IsNullOrWhiteSpace(path)).ToList();

                    try
                    {
                        if (updatedPaths.Count == 0)
                            _userConfiguration.RemoveModConfigPath(mod.ModId);
                        else
                            _userConfiguration.SetModConfigPaths(mod.ModId, updatedPaths);

                        UpdateSelectedModEditConfigButton(mod);
                        _viewModel?.ReportStatus($"Saved config for {mod.DisplayName}.");
                    }
                    catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or ArgumentException)
                    {
                        WpfMessageBox.Show($"Failed to store the configuration path:\n{ex.Message}",
                            "Simple VS Manager",
                            MessageBoxButton.OK,
                            MessageBoxImage.Error);
                    }
                }
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or JsonException or YamlException)
            {
                WpfMessageBox.Show($"Failed to open the configuration file:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                _userConfiguration.RemoveModConfigPath(mod.ModId);
                UpdateSelectedModEditConfigButton(mod);
            }
        }

    private void CloseModInfoButton_OnClick(object sender, RoutedEventArgs e)
        {
            ClearSelection(resetAnchor: true);
            e.Handled = true;
        }

    private async void FixModButton_OnClick(object sender, RoutedEventArgs e)
        {
            if (_isModUpdateInProgress) return;

            if (sender is not WpfButton { DataContext: ModListItemViewModel mod }) return;

            e.Handled = true;

            var dependencies = mod.Dependencies;
            if (dependencies.Count == 0)
            {
                WpfMessageBox.Show("This mod does not declare dependencies that can be fixed automatically.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            var errorSourcePathsBeforeFix =
                _viewModel?.GetSourcePathsForModsWithErrors() ?? [];
            var modsToRefresh = new HashSet<string>(errorSourcePathsBeforeFix, StringComparer.OrdinalIgnoreCase);

            if (!string.IsNullOrWhiteSpace(mod.SourcePath)) modsToRefresh.Add(mod.SourcePath);

            _isModUpdateInProgress = true;
            UpdateSelectedModButtons();

            var failures = new List<string>();
            var anySuccess = false;
            var processedDependencies = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            try
            {
                foreach (var dependency in dependencies)
                {
                    if (dependency.IsGameOrCoreDependency || !processedDependencies.Add(dependency.ModId)) continue;

                    var installedDependency = _viewModel?.FindInstalledModById(dependency.ModId);

                    var isMissing = mod.MissingDependencies.Any(d =>
                        string.Equals(d.ModId, dependency.ModId, StringComparison.OrdinalIgnoreCase));
                    if (!isMissing && installedDependency is null) isMissing = true;

                    if (!isMissing && installedDependency != null)
                    {
                        var satisfies =
                            VersionStringUtility.SatisfiesMinimumVersion(dependency.Version, installedDependency.Version);
                        if (!satisfies) isMissing = true;
                    }

                    if (isMissing)
                    {
                        var result = await InstallOrUpdateDependencyAsync(dependency, installedDependency)
                            .ConfigureAwait(true);
                        if (!result.Success)
                        {
                            failures.Add($"{dependency.Display}: {result.Message}");
                            _viewModel?.ReportStatus($"Failed to install dependency {dependency.Display}: {result.Message}",
                                true);
                        }
                        else
                        {
                            anySuccess = true;
                            _viewModel?.ReportStatus(result.Message);
                        }

                        continue;
                    }

                    if (installedDependency != null && !installedDependency.IsActive)
                    {
                        installedDependency.IsActive = true;
                        anySuccess = true;
                        _viewModel?.ReportStatus($"Activated dependency {installedDependency.DisplayName}.");
                    }
                }
            }
            finally
            {
                _isModUpdateInProgress = false;
                UpdateSelectedModButtons();
            }

            if (_viewModel is { } viewModel && modsToRefresh.Count > 0)
            {
                try
                {
                    await viewModel.RefreshModsWithErrorsAsync(modsToRefresh).ConfigureAwait(true);
                }
                catch (Exception ex)
                {
                    WpfMessageBox.Show(
                        $"The mods with errors could not be refreshed after fixing dependencies:{Environment.NewLine}{ex.Message}",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Error);
                }

                UpdateSelectedModButtons();
            }

            if (failures.Count > 0)
            {
                var message = string.Join(Environment.NewLine, failures);
                WpfMessageBox.Show($"Some dependencies could not be resolved:{Environment.NewLine}{message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                _viewModel?.ReportStatus($"Failed to resolve all dependencies for {mod.DisplayName}.", true);
            }
            else if (anySuccess)
            {
                _viewModel?.ReportStatus($"Resolved dependencies for {mod.DisplayName}.");
            }
            else
            {
                _viewModel?.ReportStatus($"Dependencies for {mod.DisplayName} are already satisfied.");
            }
        }

    private async void InstallModButton_OnClick(object sender, RoutedEventArgs e)
        {
            if (_isModUpdateInProgress) return;

            if (sender is not WpfButton { DataContext: ModListItemViewModel mod }) return;

            e.Handled = true;

            if (!mod.HasDownloadableRelease)
            {
                WpfMessageBox.Show("No downloadable releases are available for this mod.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            var release = SelectReleaseForInstall(mod);
            if (release is null)
            {
                WpfMessageBox.Show("No downloadable releases are available for this mod.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            if (!TryGetInstallTargetPath(mod, release, out var targetPath, out var errorMessage))
            {
                if (!string.IsNullOrWhiteSpace(errorMessage))
                    WpfMessageBox.Show(errorMessage!,
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Error);

                return;
            }

            await CreateAutomaticBackupAsync("ModsUpdated").ConfigureAwait(true);

            _isModUpdateInProgress = true;
            UpdateSelectedModButtons();

            try
            {
                var descriptor = new ModUpdateDescriptor(
                    mod.ModId,
                    mod.DisplayName,
                    release.DownloadUri,
                    targetPath,
                    false,
                    release.FileName,
                    release.Version,
                    mod.Version);

                var progress = new Progress<ModUpdateProgress>(p =>
                    _viewModel?.ReportStatus($"{mod.DisplayName}: {p.Message}"));

                var result = await _modUpdateService
                    .UpdateAsync(descriptor, _userConfiguration.CacheAllVersionsLocally, progress)
                    .ConfigureAwait(true);

                if (!result.Success)
                {
                    var message = string.IsNullOrWhiteSpace(result.ErrorMessage)
                        ? "The installation failed."
                        : result.ErrorMessage!;
                    _viewModel?.ReportStatus($"Failed to install {mod.DisplayName}: {message}", true);
                    WpfMessageBox.Show($"Failed to install {mod.DisplayName}:{Environment.NewLine}{message}",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Error);
                    return;
                }

                var versionText = string.IsNullOrWhiteSpace(release.Version) ? string.Empty : $" {release.Version}";
                _viewModel?.ReportStatus($"Installed {mod.DisplayName}{versionText}.");
                _modActivityLoggingService.LogModInstall(mod.DisplayName ?? mod.ModId ?? "Unknown", release.Version);

                await RefreshModsAsync().ConfigureAwait(true);

                if (mod.IsSelected) RemoveFromSelection(mod);

                _viewModel?.RemoveSearchResult(mod);
            }
            catch (OperationCanceledException)
            {
                _viewModel?.ReportStatus("Installation cancelled.");
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or InvalidOperationException)
            {
                _viewModel?.ReportStatus($"Failed to install {mod.DisplayName}: {ex.Message}", true);
                WpfMessageBox.Show($"Failed to install {mod.DisplayName}:{Environment.NewLine}{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
            finally
            {
                _isModUpdateInProgress = false;
                UpdateSelectedModButtons();
            }
        }

    private async Task<(bool Success, string Message)> InstallOrUpdateDependencyAsync(
            ModDependencyInfo dependency,
            ModListItemViewModel? installedMod)
        {
            try
            {
                var info = await _modDatabaseService
                    .TryLoadDatabaseInfoAsync(dependency.ModId, installedMod?.Version, _viewModel?.InstalledGameVersion,
                        _userConfiguration.RequireExactVsVersionMatch)
                    .ConfigureAwait(true);

                if (info is null) return (false, "Mod not found on the mod database.");

                var release = SelectReleaseForDependency(dependency, info);
                if (release is null) return (false, "No compatible releases were found.");

                string targetPath;
                bool targetIsDirectory;
                string? existingPath = null;

                if (installedMod != null)
                {
                    if (!TryGetManagedModPath(installedMod, out targetPath, out var pathError))
                        return (false, pathError ?? "The mod path could not be determined.");

                    targetIsDirectory = Directory.Exists(targetPath);
                    if (!targetIsDirectory && !File.Exists(targetPath) && installedMod.SourceKind == ModSourceKind.Folder)
                        targetIsDirectory = true;

                    if (!targetIsDirectory)
                    {
                        if (!TryGetUpdateTargetPath(installedMod, release, targetPath, out var resolvedPath,
                                out var targetError))
                            return (false, targetError ?? "The mod path could not be determined.");

                        existingPath = targetPath;
                        targetPath = resolvedPath;
                    }
                }
                else
                {
                    if (!TryGetDependencyInstallTargetPath(dependency.ModId, release, out targetPath, out var errorMessage))
                        return (false, errorMessage ?? "The Mods folder is not available.");

                    targetIsDirectory = false;
                }

                var wasActive = installedMod?.IsActive == true;

                var descriptor = new ModUpdateDescriptor(
                    dependency.ModId,
                    dependency.Display,
                    release.DownloadUri,
                    targetPath,
                    targetIsDirectory,
                    release.FileName,
                    release.Version,
                    installedMod?.Version)
                {
                    ExistingPath = existingPath
                };

                var progress = new Progress<ModUpdateProgress>(p =>
                    _viewModel?.ReportStatus($"{dependency.ModId}: {p.Message}"));

                var updateResult = await _modUpdateService
                    .UpdateAsync(descriptor, _userConfiguration.CacheAllVersionsLocally, progress)
                    .ConfigureAwait(true);

                if (!updateResult.Success)
                {
                    var message = string.IsNullOrWhiteSpace(updateResult.ErrorMessage)
                        ? "The installation failed."
                        : updateResult.ErrorMessage!;
                    return (false, message);
                }

                if (installedMod != null && _viewModel != null)
                    await _viewModel.PreserveActivationStateAsync(
                        dependency.ModId,
                        installedMod.Version,
                        release.Version,
                        wasActive).ConfigureAwait(true);

                var action = installedMod != null ? "Updated" : "Installed";
                var versionSuffix = string.IsNullOrWhiteSpace(release.Version) ? string.Empty : $" {release.Version}";
                return (true, $"{action} dependency {dependency.Display}{versionSuffix}.");
            }
            catch (OperationCanceledException)
            {
                return (false, "The operation was cancelled.");
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or InvalidOperationException)
            {
                return (false, ex.Message);
            }
        }

    private static ModReleaseInfo? SelectReleaseForDependency(ModDependencyInfo dependency, ModDatabaseInfo info)
        {
            if (info is null) return null;

            var releases = info.Releases ?? Array.Empty<ModReleaseInfo>();
            if (releases.Count == 0) return null;

            foreach (var release in releases)
                if (release.IsCompatibleWithInstalledGame
                    && VersionStringUtility.SatisfiesMinimumVersion(dependency.Version, release.Version))
                    return release;

            foreach (var release in releases)
                if (VersionStringUtility.SatisfiesMinimumVersion(dependency.Version, release.Version))
                    return release;

            var fallback = releases.FirstOrDefault(r => r.IsCompatibleWithInstalledGame)
                           ?? releases[0];

            var availableVersion = string.IsNullOrWhiteSpace(fallback.Version)
                ? "the latest available release"
                : $"version {fallback.Version}";

            var requirement = string.IsNullOrWhiteSpace(dependency.Version)
                ? dependency.ModId
                : $"{dependency.ModId} {dependency.Version} or newer";

            var message =
                $"No release that satisfies the required minimum version for {dependency.Display} could be found.{Environment.NewLine}{Environment.NewLine}" +
                $"The mod database only provides {availableVersion}, which may not resolve the dependency requirement for {requirement}.{Environment.NewLine}{Environment.NewLine}" +
                "Do you want to install this older release anyway?";

            var confirmation = WpfMessageBox.Show(
                message,
                "Simple VS Manager",
                MessageBoxButton.YesNo,
                MessageBoxImage.Warning);

            return confirmation == MessageBoxResult.Yes ? fallback : null;
        }

    private static ModReleaseInfo? SelectReleaseForInstall(ModListItemViewModel mod)
        {
            if (mod.LatestRelease?.IsCompatibleWithInstalledGame == true) return mod.LatestRelease;

            if (mod.LatestCompatibleRelease != null) return mod.LatestCompatibleRelease;

            return mod.LatestRelease;
        }

    private async void UpdateModButton_OnClick(object sender, RoutedEventArgs e)
        {
            if (_isModUpdateInProgress) return;

            if (sender is not WpfButton { DataContext: ModListItemViewModel mod }) return;

            e.Handled = true;

            IReadOnlyDictionary<ModListItemViewModel, ModReleaseInfo>? overrides = null;
            if (mod.SelectedVersionOption is { Release: { } selectedRelease, IsInstalled: false })
                overrides = new Dictionary<ModListItemViewModel, ModReleaseInfo>
                {
                    [mod] = selectedRelease
                };

            await UpdateModsAsync(new[] { mod }, false, overrides);
        }

    private async void SelectedModVersionComboBox_OnSelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (_isModUpdateInProgress) return;

            if (sender is not ComboBox comboBox) return;

            if (!comboBox.IsDropDownOpen && !comboBox.IsKeyboardFocusWithin) return;

            if (_viewModel?.SelectedMod is not ModListItemViewModel mod) return;

            if (comboBox.SelectedItem is not ModVersionOptionViewModel option) return;

            if (option.IsInstalled || option.Release is null) return;

            if (string.Equals(mod.Version, option.Version, StringComparison.OrdinalIgnoreCase)) return;

            var overrides = new Dictionary<ModListItemViewModel, ModReleaseInfo>
            {
                [mod] = option.Release
            };

            // Use isBulk=true to leverage the modlist install UI overlay for smooth progress feedback
            // and to prevent UI freezing. Pass showSummary=false to skip the bulk changelog dialog.
            await UpdateModsAsync(new[] { mod }, isBulk: true, overrides, showSummary: false);
        }

    private void SelectedModVersionComboBox_OnDropDownOpened(object sender, EventArgs e)
        {
            if (sender is not ComboBox comboBox) return;

            void ScrollToTop()
            {
                ScrollViewer? scrollViewer = null;

                if (comboBox.Template?.FindName("Popup", comboBox) is Popup popup)
                    scrollViewer = FindDescendantScrollViewer(popup.Child);

                scrollViewer ??= FindDescendantScrollViewer(comboBox);
                if (scrollViewer != null)
                {
                    scrollViewer.ScrollToHome();
                    scrollViewer.ScrollToVerticalOffset(0);
                }
            }

            comboBox.Dispatcher.BeginInvoke((Action)ScrollToTop, DispatcherPriority.Background);
        }

    private async void UpdateAllModsMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (_isApplyingPreset) return;

            if (_isModUpdateInProgress || _viewModel?.ModsView == null) return;

            var mods = _viewModel.ModsView.Cast<ModListItemViewModel>()
                .Where(mod => mod.CanUpdate)
                .ToList();

            Dictionary<ModListItemViewModel, ModReleaseInfo>? overrides = null;
            foreach (var mod in mods)
                if (mod.SelectedVersionOption is { Release: { } selectedRelease, IsInstalled: false })
                {
                    overrides ??= new Dictionary<ModListItemViewModel, ModReleaseInfo>();
                    overrides[mod] = selectedRelease;
                }

            if (mods.Count == 0)
            {
                WpfMessageBox.Show("All mods are already up to date.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            var dialog = new UpdateModsDialog(_userConfiguration, mods, overrides)
            {
                Owner = this
            };

            var dialogResult = dialog.ShowDialog();
            if (dialogResult != true) return;

            var selectedMods = dialog.SelectedMods;
            if (selectedMods.Count == 0) return;

            Dictionary<ModListItemViewModel, ModReleaseInfo>? selectedOverrides = null;
            if (overrides != null)
                foreach (var mod in selectedMods)
                    if (overrides.TryGetValue(mod, out var release) && release != null)
                    {
                        selectedOverrides ??= new Dictionary<ModListItemViewModel, ModReleaseInfo>();
                        selectedOverrides[mod] = release;
                    }

            await CreateAutomaticBackupAsync("ModsUpdated").ConfigureAwait(true);
            await UpdateModsAsync(selectedMods, true, selectedOverrides).ConfigureAwait(true);
        }

    private void ActiveToggle_OnPreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (sender is not ToggleSwitch toggleSwitch) return;

            if (!toggleSwitch.IsEnabled) return;

            e.Handled = true;

            toggleSwitch.Focus();
            toggleSwitch.IsOn = !toggleSwitch.IsOn;
        }

    private void ActiveToggle_OnPreviewMouseLeftButtonUp(object sender, MouseButtonEventArgs e)
        {
            if (sender is ToggleSwitch) e.Handled = true;
        }

    private void ActiveToggle_OnPreviewMouseMove(object sender, MouseEventArgs e)
        {
            if (sender is not ToggleSwitch || e.LeftButton != MouseButtonState.Pressed) return;

            e.Handled = true;
        }

    private void ActiveToggle_OnToggled(object sender, RoutedEventArgs e)
        {
            if (_isApplyingMultiToggle) return;

            if (sender is not ToggleSwitch { DataContext: ModListItemViewModel mod }) return;

            if (!_selectedMods.Contains(mod) || _selectedMods.Count <= 1) return;

            var desiredState = mod.IsActive;

            try
            {
                _isApplyingMultiToggle = true;

                foreach (var selected in _selectedMods)
                {
                    if (ReferenceEquals(selected, mod)) continue;

                    if (!selected.CanToggle || selected.IsActive == desiredState) continue;

                    selected.IsActive = desiredState;
                }
            }
            finally
            {
                _isApplyingMultiToggle = false;
            }
        }
}
