// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private async Task ApplyPresetAsync(ModPreset preset, bool importConfigurations = true)
        {
            var viewModel = _viewModel;
            if (viewModel is null || _isApplyingPreset) return;

            using var busyScope = viewModel.EnterBusyScope();

            _recentLocalModBackupDirectory = null;
            _recentLocalModBackupModNames = null;

            var scheduleRefreshAfterLoad = false;
            _isApplyingPreset = true;
            UpdateModlistLoadingUiState();
            try
            {
                if (preset.IncludesModVersions && preset.ModStates.Count > 0)
                    scheduleRefreshAfterLoad = await ApplyPresetModVersionsAsync(preset).ConfigureAwait(true);

                var applied = await viewModel.ApplyPresetAsync(preset).ConfigureAwait(true);
                if (applied)
                {
                    if (preset.IsExclusive) await ApplyExclusivePresetAsync(preset).ConfigureAwait(true);

                    viewModel.SelectedSortOption?.Apply(viewModel.ModsView);
                    viewModel.ModsView.Refresh();
                }

                if (importConfigurations) await ImportPresetConfigsAsync(preset).ConfigureAwait(true);
            }
            finally
            {
                _isApplyingPreset = false;
                UpdateModlistLoadingUiState();

                if (scheduleRefreshAfterLoad)
                {
                    _refreshAfterModlistLoadPending = true;
                    ScheduleRefreshAfterModlistLoadIfReady();
                }
            }
        }

    private async Task ImportPresetConfigsAsync(ModPreset preset)
    {
        if (preset.ModStates.Count == 0) return;

        var configurations =
            PresetConfigurationImportService.CollectConfigurations(preset);

        if (configurations.Count == 0) return;

        var modDisplayNames =
            new Dictionary<string, string>(
                StringComparer.OrdinalIgnoreCase);
        var promptNames = new List<string>(configurations.Count);

        foreach (var configuration in configurations)
        {
            var displayName = configuration.ModId;

            if (_viewModel?.TryGetInstalledModDisplayName(
                    configuration.ModId,
                    out var resolvedName) == true &&
                !string.IsNullOrWhiteSpace(resolvedName))
            {
                displayName = resolvedName.Trim();
            }

            if (!modDisplayNames.ContainsKey(configuration.ModId))
                modDisplayNames.Add(configuration.ModId, displayName);

            promptNames.Add(displayName);
        }

        promptNames = promptNames
            .Where(name => !string.IsNullOrWhiteSpace(name))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .OrderBy(name => name, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var summary = promptNames.Count == 0
            ? string.Empty
            : string.Join(
                "\n",
                promptNames.Select(name => $"• {name}"));

        var message =
            "This modlist includes configuration files for the following mods:";

        if (!string.IsNullOrEmpty(summary))
            message += $"\n\n{summary}";

        message +=
            "\n\nImporting these configurations will overwrite your existing " +
            "settings for these mods if they are already installed. " +
            "Do you want to import them?";

        var prompt = WpfMessageBox.Show(
            this,
            message,
            "Import Mod Configurations",
            MessageBoxButton.YesNo,
            MessageBoxImage.Question);

        if (prompt != MessageBoxResult.Yes) return;

        if (string.IsNullOrWhiteSpace(_dataDirectory))
        {
            WpfMessageBox.Show(
                "The Vintage Story data directory is not set, so the " +
                "configuration files could not be imported.",
                "Simple VS Manager",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
            return;
        }

        PresetConfigurationImportResult importResult;

        try
        {
            importResult =
                await PresetConfigurationImportService.ImportAsync(
                        configurations,
                        _dataDirectory,
                        _userConfiguration,
                        modDisplayNames)
                    .ConfigureAwait(true);
        }
        catch (Exception ex) when (
            ex is IOException or UnauthorizedAccessException)
        {
            WpfMessageBox.Show(
                $"Failed to prepare the configuration directory:\n{ex.Message}",
                "Simple VS Manager",
                MessageBoxButton.OK,
                MessageBoxImage.Error);
            return;
        }

        if (importResult.ImportedCount > 0)
        {
            _viewModel?.ReportStatus(
                $"Imported configuration files for " +
                $"{importResult.ImportedCount} mod(s).");

            UpdateSelectedModButtons();
        }

        if (importResult.Errors.Count > 0)
        {
            WpfMessageBox.Show(
                "Some configuration files could not be imported:\n" +
                string.Join("\n", importResult.Errors),
                "Simple VS Manager",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
        }
    }

    private async Task<bool> ApplyPresetModVersionsAsync(ModPreset preset)
        {
            if (_viewModel?.ModsView is null) return false;

            var mods = _viewModel.ModsView.Cast<ModListItemViewModel>().ToList();
            var modLookup = mods.ToDictionary(mod => mod.ModId, StringComparer.OrdinalIgnoreCase);
            var overrides = new Dictionary<ModListItemViewModel, ModReleaseInfo>();
            var missingVersions = new List<string>();
            var missingMods = new List<string>();
            var installFailures = new List<string>();
            var installCandidates = new List<ModPresetModState>();

            foreach (var state in preset.ModStates)
            {
                if (!modLookup.TryGetValue(state.ModId, out var mod))
                {
                    installCandidates.Add(state);
                    continue;
                }

                var desiredVersion = string.IsNullOrWhiteSpace(state.Version) ? null : state.Version!.Trim();
                if (string.IsNullOrWhiteSpace(desiredVersion)) continue;

                var installedVersion = string.IsNullOrWhiteSpace(mod.Version) ? null : mod.Version!.Trim();

                if (VersionStringUtility.VersionsMatch(desiredVersion, installedVersion)) continue;

                var desiredNormalized = VersionStringUtility.Normalize(desiredVersion);

                var option = mod.VersionOptions.FirstOrDefault(opt =>
                    (!string.IsNullOrWhiteSpace(desiredVersion)
                     && string.Equals(opt.Version, desiredVersion, StringComparison.OrdinalIgnoreCase))
                    || (!string.IsNullOrWhiteSpace(desiredNormalized)
                        && !string.IsNullOrWhiteSpace(opt.NormalizedVersion)
                        && string.Equals(opt.NormalizedVersion, desiredNormalized, StringComparison.OrdinalIgnoreCase)));

                if (option is null)
                {
                    missingVersions.Add($"{mod.DisplayName} ({desiredVersion})");
                    continue;
                }

                if (option.IsInstalled) continue;

                if (!option.HasRelease || option.Release is null)
                {
                    var display = !string.IsNullOrWhiteSpace(option.Version)
                        ? option.Version
                        : desiredVersion ?? "Unknown";
                    missingVersions.Add($"{mod.DisplayName} ({display})");
                    continue;
                }

                overrides[mod] = option.Release;
            }

            var totalInstallOperations = installCandidates.Count + overrides.Count;
            var showInstallOverlay = totalInstallOperations > 0;
            var hasOverrides = overrides.Count > 0;

            if (showInstallOverlay)
                BeginModlistInstallUi(totalInstallOperations, "Installing mods from the modlist...");

            try
            {
                if (installCandidates.Count > 0)
                {
                    foreach (var candidate in installCandidates)
                    {
                        var progress = showInstallOverlay
                            ? CreateModlistInstallProgressReporter(candidate.ModId)
                            : null;

                        var installResult = await TryInstallPresetModAsync(candidate, progress).ConfigureAwait(true);
                        if (installResult.Success)
                        {
                            if (showInstallOverlay)
                            {
                                var display = string.IsNullOrWhiteSpace(candidate.ModId) ? "mod" : candidate.ModId!;
                                CompleteModlistInstallStep($"Installed {display}.");
                            }

                            continue;
                        }

                        var desiredVersion = string.IsNullOrWhiteSpace(candidate.Version)
                            ? "Unknown"
                            : candidate.Version!.Trim();

                        if (installResult.ModMissing)
                        {
                            var modDisplay = string.IsNullOrWhiteSpace(candidate.ModId)
                                ? "<unknown mod>"
                                : candidate.ModId!;
                            var display = string.IsNullOrWhiteSpace(installResult.ErrorMessage)
                                ? modDisplay
                                : $"{modDisplay} — {installResult.ErrorMessage}";
                            missingMods.Add(display);

                            if (showInstallOverlay)
                                CompleteModlistInstallStep($"{modDisplay} was not found.");

                            continue;
                        }

                        if (installResult.VersionMissing)
                        {
                            var modDisplay = string.IsNullOrWhiteSpace(candidate.ModId)
                                ? "<unknown mod>"
                                : candidate.ModId!;
                            missingVersions.Add($"{modDisplay} ({desiredVersion})");

                            if (showInstallOverlay)
                                CompleteModlistInstallStep($"{modDisplay} {desiredVersion} unavailable.");

                            continue;
                        }

                        if (!string.IsNullOrWhiteSpace(installResult.ErrorMessage))
                            installFailures.Add($"{candidate.ModId}: {installResult.ErrorMessage}");

                        if (showInstallOverlay)
                        {
                            var displayName = string.IsNullOrWhiteSpace(candidate.ModId) ? "Mod" : candidate.ModId!;
                            var failureMessage = string.IsNullOrWhiteSpace(installResult.ErrorMessage)
                                ? "Installation failed."
                                : installResult.ErrorMessage!;
                            CompleteModlistInstallStep($"{displayName}: {failureMessage}");
                        }
                    }

                }

                if (hasOverrides)
                {
                    Func<ModListItemViewModel, ModReleaseInfo, IProgress<ModUpdateProgress>?>? progressFactory = null;
                    Action<ModListItemViewModel, ModReleaseInfo, ModUpdateResult>? completionCallback = null;

                    if (showInstallOverlay)
                    {
                        progressFactory = (mod, _) => CreateModlistInstallProgressReporter(mod.DisplayName ?? mod.ModId);
                        completionCallback = (mod, release, result) =>
                        {
                            var displayName = string.IsNullOrWhiteSpace(mod.DisplayName)
                                ? mod.ModId ?? "Mod"
                                : mod.DisplayName!;
                            var versionSuffix = string.IsNullOrWhiteSpace(release.Version)
                                ? string.Empty
                                : $" {release.Version}";
                            var message = result.Success
                                ? $"Updated {displayName}{versionSuffix}."
                                : $"{displayName}: {(!string.IsNullOrWhiteSpace(result.ErrorMessage)
                                    ? result.ErrorMessage
                                    : "Update failed.")}";

                            CompleteModlistInstallStep(message);
                        };
                    }

                    await UpdateModsAsync(overrides.Keys.ToList(), true, overrides, false, progressFactory,
                            completionCallback)
                        .ConfigureAwait(true);
                }
            }
            finally
            {
                if (showInstallOverlay) EndModlistInstallUi();
            }

            if (missingMods.Count > 0 || missingVersions.Count > 0 || installFailures.Count > 0)
            {
                var builder = new StringBuilder();

                if (missingMods.Count > 0)
                {
                    builder.AppendLine("The following mods from the preset could not be installed:");
                    foreach (var modId in missingMods.Distinct(StringComparer.OrdinalIgnoreCase))
                        builder.AppendLine($" • {modId}");
                }

                if (missingVersions.Count > 0)
                {
                    if (builder.Length > 0) builder.AppendLine();

                    builder.AppendLine("The following mod versions could not be located:");
                    foreach (var entry in missingVersions.Distinct(StringComparer.OrdinalIgnoreCase))
                        builder.AppendLine($" • {entry}");
                }

                if (installFailures.Count > 0)
                {
                    if (builder.Length > 0) builder.AppendLine();

                    builder.AppendLine("Some mods failed to install:");
                    foreach (var failure in installFailures.Distinct(StringComparer.OrdinalIgnoreCase))
                        builder.AppendLine($" • {failure}");
                }

                if (missingMods.Count > 0
                    && !string.IsNullOrWhiteSpace(_recentLocalModBackupDirectory)
                    && _recentLocalModBackupModNames is { Count: > 0 })
                {
                    if (builder.Length > 0)
                    {
                        builder.AppendLine();
                        builder.AppendLine();
                    }

                    builder.AppendLine("Local copies of mods that are not on the mod database were saved to:");
                    builder.AppendLine($" • {_recentLocalModBackupDirectory}");

                    var distinctBackups = _recentLocalModBackupModNames
                        .Where(name => !string.IsNullOrWhiteSpace(name))
                        .Distinct(StringComparer.OrdinalIgnoreCase)
                        .OrderBy(name => name, StringComparer.OrdinalIgnoreCase)
                        .ToList();

                    if (distinctBackups.Count > 0)
                    {
                        builder.AppendLine("Backed up mods:");
                        foreach (var backupName in distinctBackups) builder.AppendLine($"   • {backupName}");
                    }
                }

                var message = builder.ToString().Trim();
                if (!string.IsNullOrWhiteSpace(message))
                    WpfMessageBox.Show(message,
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Warning);
            }

            return showInstallOverlay;
        }

    private async Task<PresetModInstallResult> TryInstallPresetModAsync(ModPresetModState state,
            IProgress<ModUpdateProgress>? installProgress = null)
        {
            if (_viewModel is null)
                return new PresetModInstallResult(false, false, false, "The mod view model is not available.");

            var modId = state.ModId?.Trim() ?? string.Empty;
            if (string.IsNullOrWhiteSpace(modId))
                return new PresetModInstallResult(false, false, false, "The preset entry is missing a mod identifier.");

            var desiredVersion = string.IsNullOrWhiteSpace(state.Version) ? null : state.Version!.Trim();
            if (string.IsNullOrWhiteSpace(desiredVersion))
                return new PresetModInstallResult(false, false, true, "No version was recorded for this mod.");

            var info = await _modDatabaseService
                .TryLoadDatabaseInfoAsync(modId, desiredVersion, _viewModel.InstalledGameVersion,
                    _userConfiguration.RequireExactVsVersionMatch)
                .ConfigureAwait(true);

            if (info is null) return new PresetModInstallResult(false, true, false, "Mod not found on the mod database.");

            var desiredNormalized = VersionStringUtility.Normalize(desiredVersion);
            var releases = info.Releases ?? Array.Empty<ModReleaseInfo>();
            var release = releases.FirstOrDefault(r =>
                (!string.IsNullOrWhiteSpace(r.Version)
                 && string.Equals(r.Version.Trim(), desiredVersion, StringComparison.OrdinalIgnoreCase))
                || (!string.IsNullOrWhiteSpace(desiredNormalized)
                    && !string.IsNullOrWhiteSpace(r.NormalizedVersion)
                    && string.Equals(r.NormalizedVersion, desiredNormalized, StringComparison.OrdinalIgnoreCase)));

            if (release is null)
                return new PresetModInstallResult(false, false, true,
                    "The specified version could not be found on the mod database.");

            if (!TryGetDependencyInstallTargetPath(modId, release, out var targetPath, out var pathError))
                return new PresetModInstallResult(false, false, false, pathError);

            var descriptor = new ModUpdateDescriptor(
                modId,
                modId,
                release.DownloadUri,
                targetPath,
                false,
                release.FileName,
                release.Version,
                null);

            var progress = CreateModUpdateProgressReporter(modId, installProgress);

            var result = await _modUpdateService
                .UpdateAsync(descriptor, _userConfiguration.CacheAllVersionsLocally, progress)
                .ConfigureAwait(true);

            if (!result.Success)
            {
                var message = string.IsNullOrWhiteSpace(result.ErrorMessage)
                    ? "The installation failed."
                    : result.ErrorMessage!;
                return new PresetModInstallResult(false, false, false, message);
            }

            var versionSuffix = string.IsNullOrWhiteSpace(release.Version) ? string.Empty : $" {release.Version}";
            _viewModel.ReportStatus($"Installed {modId}{versionSuffix}.");
            _modActivityLoggingService.LogModInstall(modId, release.Version);

            return new PresetModInstallResult(true, false, false, null);
        }

    private async Task ApplyExclusivePresetAsync(ModPreset preset)
        {
            if (_viewModel?.ModsView is null) return;

            if (preset.ModStates.Count == 0) return;

            var keepSet = new HashSet<string>(
                preset.ModStates.Select(state => state.ModId),
                StringComparer.OrdinalIgnoreCase);

            if (keepSet.Count == 0) return;

            var installedMods = _viewModel.ModsView.Cast<ModListItemViewModel>().ToList();
            if (installedMods.Count == 0) return;

            var failures = new List<string>();
            var removedCount = 0;
            string? localBackupSessionDirectory = null;
            List<string>? backedUpModNames = null;
            var localBackupInitializationFailed = false;

            foreach (var mod in installedMods)
            {
                if (!mod.IsInstalled) continue;

                if (keepSet.Contains(mod.ModId)) continue;

                if (!TryGetManagedModPath(mod, out var modPath, out var errorMessage))
                {
                    if (!string.IsNullOrWhiteSpace(errorMessage)) failures.Add($"{mod.DisplayName}: {errorMessage}");

                    continue;
                }

                var sourceExists = Directory.Exists(modPath) || File.Exists(modPath);
                if (!mod.HasModDatabasePageLink && sourceExists && !localBackupInitializationFailed)
                {
                    if (string.IsNullOrWhiteSpace(localBackupSessionDirectory))
                        try
                        {
                            localBackupSessionDirectory = CreateLocalModBackupSessionDirectory();
                        }
                        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or NotSupportedException
                                                       or PathTooLongException)
                        {
                            failures.Add($"Failed to prepare the local mod backup directory: {ex.Message}");
                            localBackupInitializationFailed = true;
                        }

                    if (!localBackupInitializationFailed && !string.IsNullOrWhiteSpace(localBackupSessionDirectory))
                        try
                        {
                            var entryDirectory = GetLocalModBackupEntryDirectory(localBackupSessionDirectory, mod);
                            LocalModBackupService.BackupLocalModAtPath(modPath, entryDirectory);

                            var name = string.IsNullOrWhiteSpace(mod.DisplayName)
                                ? mod.ModId
                                : mod.DisplayName;

                            if (!string.IsNullOrWhiteSpace(name))
                            {
                                backedUpModNames ??= new List<string>();
                                backedUpModNames.Add(name.Trim());
                            }
                        }
                        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or NotSupportedException
                                                       or PathTooLongException)
                        {
                            failures.Add(
                                $"{mod.DisplayName}: Failed to backup the local copy before deletion — {ex.Message}");
                        }
                }

                try
                {
                    if (Directory.Exists(modPath))
                    {
                        Directory.Delete(modPath, true);
                        removedCount++;
                    }
                    else if (File.Exists(modPath))
                    {
                        File.Delete(modPath);
                        removedCount++;
                    }
                    else
                    {
                        continue;
                    }
                }
                catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
                {
                    failures.Add($"{mod.DisplayName}: {ex.Message}");
                    continue;
                }

                _userConfiguration.RemoveModConfigPath(mod.ModId, true);
            }

            if (!string.IsNullOrWhiteSpace(localBackupSessionDirectory) && backedUpModNames is { Count: > 0 })
            {
                _recentLocalModBackupDirectory = localBackupSessionDirectory;
                _recentLocalModBackupModNames = backedUpModNames;
            }

            if (removedCount > 0)
            {
                await RefreshModsAsync(true).ConfigureAwait(true);

                var status = removedCount == 1
                    ? "Removed 1 mod not in the preset."
                    : $"Removed {removedCount} mods not in the preset.";
                _viewModel?.ReportStatus(status);
            }

            if (failures.Count > 0)
            {
                var builder = new StringBuilder();
                builder.AppendLine("Some mods could not be removed:");
                foreach (var failure in failures.Distinct(StringComparer.OrdinalIgnoreCase))
                    builder.AppendLine($" • {failure}");

                WpfMessageBox.Show(builder.ToString().Trim(),
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
            }
        }

}
