#nullable enable

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Runtime.InteropServices;
using System.Security;
using System.Text;
using System.Windows;
using VintageStoryModManager.Services;

using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using WinForms = System.Windows.Forms;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{
    private void GenerateServerInstallMacroMenuItem_OnClick(object sender, RoutedEventArgs e)
    {
        if (_viewModel is null)
        {
            WpfMessageBox.Show(
                this,
                "The manager is still initializing. Please try again once the installed mods have finished loading.",
                "Simple VS Manager",
                MessageBoxButton.OK,
                MessageBoxImage.Information);
            return;
        }

        var installedMods = _viewModel.GetInstalledModsSnapshot();
        var installEntries = new List<(string ModId, string Version)>();
        foreach (var mod in installedMods)
        {
            if (mod is null || !mod.IsInstalled) continue;

            if (string.IsNullOrWhiteSpace(mod.ModId) || string.IsNullOrWhiteSpace(mod.Version)) continue;

            installEntries.Add((mod.ModId.Trim(), mod.Version.Trim()));
        }

        if (installEntries.Count == 0)
        {
            WpfMessageBox.Show(
                this,
                "No installed mods with a known version were found. Install mods before generating a server macro.",
                "Simple VS Manager",
                MessageBoxButton.OK,
                MessageBoxImage.Information);
            return;
        }

        var macroName = ServerMacroGenerator.CreateDefaultMacroName();
        var saveDialog = new SaveFileDialog
        {
            Title = "Save server macro",
            Filter = "Server macro (*.json)|*.json|All files (*.*)|*.*",
            AddExtension = true,
            DefaultExt = ".json",
            FileName = macroName + ".json"
        };

        try
        {
            var managerDirectory = _userConfiguration.GetConfigurationDirectory();
            if (!string.IsNullOrWhiteSpace(managerDirectory))
            {
                Directory.CreateDirectory(managerDirectory);
                saveDialog.InitialDirectory = managerDirectory;
            }
        }
        catch (Exception)
        {
            // Ignore failures when determining the initial directory.
        }

        var result = saveDialog.ShowDialog(this);
        if (result != true) return;

        var targetPath = saveDialog.FileName;
        var description = string.Format(
            CultureInfo.InvariantCulture,
            "Install {0} mods generated by Simple VS Manager on {1:yyyy-MM-dd HH:mm} UTC.",
            installEntries.Count,
            DateTime.UtcNow);

        ServerMacroGenerator.ServerMacroGenerationResult generationResult;
        try
        {
            generationResult = ServerMacroGenerator.CreateInstallMacro(
                targetPath,
                macroName,
                installEntries,
                description);
        }
        catch (Exception ex) when (ex is IOException
                                   || ex is UnauthorizedAccessException
                                   || ex is ArgumentException
                                   || ex is NotSupportedException
                                   || ex is SecurityException)
        {
            StatusLogService.AppendStatus($"Failed to create server macro: {ex.Message}", true);
            WpfMessageBox.Show(
                this,
                $"Failed to create the server macro:\n{ex.Message}",
                "Simple VS Manager",
                MessageBoxButton.OK,
                MessageBoxImage.Error);
            return;
        }

        if (!generationResult.HasMacro)
        {
            WpfMessageBox.Show(
                this,
                "Unable to generate server commands for the installed mods.",
                "Simple VS Manager",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
            return;
        }

        var command = generationResult.Command;
        var commandCopied = false;
        try
        {
            WinForms.Clipboard.SetText(command);
            commandCopied = true;
        }
        catch (ExternalException)
        {
            // Ignore clipboard errors; the command will still be shown to the user.
        }

        StatusLogService.AppendStatus(
            $"Created server macro '{generationResult.MacroName}' with {generationResult.CommandCount} install commands.",
            false);

        var messageBuilder = new StringBuilder();
        messageBuilder.AppendLine("Saved server macro file:");
        messageBuilder.AppendLine(targetPath);
        messageBuilder.AppendLine();
        messageBuilder.AppendLine(
            string.Format(
                CultureInfo.InvariantCulture,
                "Place this file in your server's config directory as servermacros.json (or merge it with your existing macros) and run {0} to install {1} mods.",
                command,
                generationResult.CommandCount));

        if (commandCopied)
        {
            messageBuilder.AppendLine();
            messageBuilder.Append("The command was copied to your clipboard.");
        }
        else
        {
            messageBuilder.AppendLine();
            messageBuilder.Append("Copy this command before running it.");
        }

        WpfMessageBox.Show(
            this,
            messageBuilder.ToString(),
            "Simple VS Manager",
            MessageBoxButton.OK,
            MessageBoxImage.Information);
    }
}
