// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private void ModsDataGrid_OnSorting(object sender, DataGridSortingEventArgs e)
        {
            if (_viewModel is null) return;

            var sortMemberPath = e.Column.SortMemberPath;
            if (string.IsNullOrWhiteSpace(sortMemberPath))
            {
                e.Handled = true;
                return;
            }

            e.Handled = true;

            var direction = e.Column.SortDirection == ListSortDirection.Ascending
                ? ListSortDirection.Descending
                : ListSortDirection.Ascending;

            ApplyModListSort(sortMemberPath, direction, true);
        }

    private void ModsDataGrid_OnSelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            // We use custom selection tracking via _selectedMods list instead of DataGrid's native selection.
            // Clear any DataGrid selection to prevent it from interfering with our custom selection.
            // With IsSynchronizedWithCurrentItem=False, this should only fire on direct user clicks,
            // which we handle in PreviewMouseLeftButtonDown.
            if (sender is DataGrid dataGrid)
            {
                dataGrid.SelectedIndex = -1;
                dataGrid.UnselectAll();
                dataGrid.UnselectAllCells();
            }
        }

    private async void ModsDataGrid_OnPreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (await TryHandleModListKeyDownAsync(e)) e.Handled = true;
        }

    private async void MainWindow_OnPreviewKeyDown(object sender, KeyEventArgs e)
        {
            if (await TryHandleModListKeyDownAsync(e)) e.Handled = true;
        }

    private async void UserReportsButton_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not WpfButton { DataContext: ModListItemViewModel mod }) return;

            e.Handled = true;

            if (_viewModel is null) return;

            if (!mod.CanSubmitUserReport)
            {
                WpfMessageBox.Show(
                    "User reports are unavailable because the mod version or Vintage Story version could not be determined.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            if (!EnsureUserReportVotingConsent()) return;

            _viewModel.EnableUserReportFetching();

            try
            {
                var summary = await _viewModel
                    .RefreshUserReportAsync(mod)
                    .ConfigureAwait(true);

                summary ??= mod.UserReportSummary;

                if (summary is null)
                    summary = new ModVersionVoteSummary(
                        mod.ModId,
                        mod.Version ?? string.Empty,
                        _viewModel.InstalledGameVersion,
                        ModVersionVoteCounts.Empty,
                        ModVersionVoteComments.Empty,
                        null,
                        null);

                var dialog = new ModVoteDialog(
                    mod,
                    summary,
                    (option, comment) => _viewModel.SubmitUserReportVoteAsync(mod, option, comment));

                dialog.Owner = this;
                dialog.ShowDialog();
            }
            catch (InternetAccessDisabledException ex)
            {
                WpfMessageBox.Show(
                    ex.Message,
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
            }
            catch (Exception ex)
            {
                WpfMessageBox.Show(
                    $"Failed to load user reports:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }

    private async Task<bool> TryHandleModListKeyDownAsync(KeyEventArgs e)
        {
            if (_isApplyingPreset) return true;

            if (e.Key == Key.A && Keyboard.Modifiers.HasFlag(ModifierKeys.Control))
            {
                // Allow CTRL+A to select text when a TextBox has focus
                if (Keyboard.FocusedElement is TextBox)
                    return false;

                if (ModsDataGrid?.IsVisible == true)
                {
                    SelectAllModsInCurrentView();
                    return true;
                }

                return false;
            }

            if (e.Key == Key.Delete)
            {
                var modifiers = Keyboard.Modifiers;
                if ((modifiers & (ModifierKeys.Control | ModifierKeys.Alt | ModifierKeys.Windows)) == ModifierKeys.None &&
                    _selectedMods.Count > 0)
                {
                    await DeleteSelectedModsAsync();
                    return true;
                }
            }

            return false;
        }

    private void ModsDataGrid_OnPreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (_isApplyingPreset)
            {
                e.Handled = true;
                return;
            }

            if (e.Handled) return;

            if (sender is not DataGrid) return;

            if (ShouldIgnoreRowSelection(e.OriginalSource as DependencyObject)) return;

            var source = e.OriginalSource as DependencyObject;
            if (FindAncestor<DataGridRow>(source) != null) return;

            if (FindAncestor<DataGridColumnHeader>(source) != null) return;

            if (FindAncestor<ScrollBar>(source) != null) return;

            ClearSelection(true);
        }

    private void ModsDataGridRow_OnPreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (_isApplyingPreset)
            {
                e.Handled = true;
                return;
            }

            if (ShouldIgnoreRowSelection(e.OriginalSource as DependencyObject)) return;

            if (sender is not DataGridRow row || row.DataContext is not ModListItemViewModel mod) return;

            row.Focus();
            HandleModRowSelection(mod);
            e.Handled = true;
        }

    private void ModDatabaseCard_OnPreviewMouseLeftButtonDown(object sender, MouseButtonEventArgs e)
        {
            if (_isApplyingPreset)
            {
                e.Handled = true;
                return;
            }

            if (ShouldIgnoreRowSelection(e.OriginalSource as DependencyObject)) return;

            if (sender is not ListViewItem item || item.DataContext is not ModListItemViewModel mod) return;

            item.Focus();
            HandleModRowSelection(mod);
            e.Handled = true;
        }

    private void ModDatabasePageButton_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is WpfButton { DataContext: ModListItemViewModel mod }
                && mod.OpenModDatabasePageCommand is ICommand command
                && command.CanExecute(null))
                command.Execute(null);

            e.Handled = true;
        }

    private void LatestVersionTextBlock_OnToolTipOpening(object sender, ToolTipEventArgs e)
        {
            if (sender is not FrameworkElement frameworkElement) return;

            if (frameworkElement.ToolTip is not WpfToolTip toolTip) return;

            toolTip.PreviewMouseWheel -= ChangelogToolTip_OnPreviewMouseWheel;
            toolTip.PreviewMouseWheel += ChangelogToolTip_OnPreviewMouseWheel;
        }

    private void LatestVersionTextBlock_OnToolTipClosing(object sender, ToolTipEventArgs e)
        {
            if (sender is not FrameworkElement frameworkElement) return;

            if (frameworkElement.ToolTip is not WpfToolTip toolTip) return;

            toolTip.PreviewMouseWheel -= ChangelogToolTip_OnPreviewMouseWheel;
        }

    private void ChangelogToolTip_OnPreviewMouseWheel(object sender, MouseWheelEventArgs e)
        {
            if (e.Handled || e.Delta == 0 || sender is not WpfToolTip toolTip) return;

            if (toolTip.Content is not ScrollViewer scrollViewer) return;

            double lines = Math.Max(1, SystemParameters.WheelScrollLines);
            var deltaMultiplier = e.Delta / (double)Mouse.MouseWheelDeltaForOneLine;
            var offsetChange = deltaMultiplier * lines * GetCurrentScrollMultiplier();
            if (Math.Abs(offsetChange) < double.Epsilon) return;

            var targetOffset = scrollViewer.VerticalOffset - offsetChange;
            var clampedOffset = Math.Max(0, Math.Min(targetOffset, scrollViewer.ScrollableHeight));
            scrollViewer.ScrollToVerticalOffset(clampedOffset);
            e.Handled = true;
        }

    private void ModsDataGrid_OnPreviewMouseWheel(object sender, MouseWheelEventArgs e)
        {
            if (e.Handled || e.Delta == 0) return;

            if (e.OriginalSource is DependencyObject originalSource && IsDescendantOfToolTip(originalSource)) return;

            if (sender is not DependencyObject dependencyObject) return;

            var isModListGrid = ReferenceEquals(dependencyObject, ModsDataGrid);

            var scrollViewer = GetModsScrollViewer(); ;

            if (scrollViewer is null) return;

            double lines = Math.Max(1, SystemParameters.WheelScrollLines);
            var deltaMultiplier = e.Delta / (double)Mouse.MouseWheelDeltaForOneLine;
            var offsetChange = deltaMultiplier * lines * GetCurrentScrollMultiplier();
            if (Math.Abs(offsetChange) < double.Epsilon) return;

            var targetOffset = scrollViewer.VerticalOffset - offsetChange;
            var clampedOffset = Math.Max(0, Math.Min(targetOffset, scrollViewer.ScrollableHeight));
            scrollViewer.ScrollToVerticalOffset(clampedOffset);
            e.Handled = true;
        }

    private static bool IsDescendantOfToolTip(DependencyObject? source)
        {
            while (source != null)
            {
                if (source is WpfToolTip || source is Popup) return true;

                source = GetParent(source);
            }

            return false;
        }

    private static DependencyObject? GetParent(DependencyObject current)
        {
            if (current is Visual visual)
            {
                var parent = VisualTreeHelper.GetParent(visual);
                if (parent != null) return parent;

                if (visual is FrameworkElement frameworkElement) return frameworkElement.Parent;
            }

            if (current is FrameworkContentElement contentElement)
                return contentElement.Parent ?? contentElement.TemplatedParent;

            return LogicalTreeHelper.GetParent(current);
        }

    private static T? FindAncestor<T>(DependencyObject? source)
            where T : DependencyObject
        {
            while (source != null)
            {
                if (source is T match) return match;

                source = GetParent(source);
            }

            return null;
        }

    private double GetCurrentScrollMultiplier()
        {
            return ModListScrollMultiplier;
        }

    private bool ShouldPreserveModsViewState(ICollectionView? previousView, ICollectionView? nextView)
        {
            if (_viewModel is null || previousView is null || nextView is null) return false;

            var previousIsInstalled = ReferenceEquals(previousView, _viewModel.ModsView);
            var previousIsModDb = ReferenceEquals(previousView, _viewModel.SearchResultsView);
            var nextIsInstalled = ReferenceEquals(nextView, _viewModel.ModsView);

            // When leaving the Installed mods tab, always clear selection
            if (previousIsInstalled) return false;

            // When coming back to Installed mods from ModDB, preserve selection
            return previousIsModDb && nextIsInstalled;
        }

    private void AttachToModsView(ICollectionView? modsView, bool preserveState = false)
        {
            if (modsView is null)
            {
                if (_modsCollection != null)
                {
                    _modsCollection.CollectionChanged -= ModsView_OnCollectionChanged;
                    _modsCollection = null;
                }

                if (!preserveState) ClearSelection(true);

                _currentModsView = null;
                return;
            }

            if (_modsCollection != null)
            {
                _modsCollection.CollectionChanged -= ModsView_OnCollectionChanged;
                _modsCollection = null;
            }

            if (modsView is INotifyCollectionChanged notify)
            {
                _modsCollection = notify;
                notify.CollectionChanged += ModsView_OnCollectionChanged;
            }

            if (!preserveState) ClearSelection(true);

            _currentModsView = modsView;
        }

    private void ModsView_OnCollectionChanged(object? sender, NotifyCollectionChangedEventArgs e)
        {
            if (!ReferenceEquals(sender, _viewModel?.ModsView)) return;

            // Don't clear selection during mod loading or mod details loading to allow user interaction
            if (_viewModel?.IsLoadingMods == true || _viewModel?.IsLoadingModDetails == true) return;

            Dispatcher.Invoke(() => ClearSelection(true));
        }

    private void HandleModRowSelection(ModListItemViewModel mod)
        {
            if (_isApplyingPreset) return;

            var isShiftPressed = Keyboard.Modifiers.HasFlag(ModifierKeys.Shift);
            var isCtrlPressed = Keyboard.Modifiers.HasFlag(ModifierKeys.Control);

            if (isShiftPressed)
            {
                if (_selectionAnchor is not { } anchor)
                {
                    if (!isCtrlPressed) ClearSelection();

                    AddToSelection(mod);
                    _selectionAnchor = mod;
                    return;
                }

                var anchorApplied = ApplyRangeSelection(anchor, mod, isCtrlPressed);
                if (!anchorApplied) _selectionAnchor = mod;

                return;
            }

            if (isCtrlPressed)
            {
                if (_selectedMods.Contains(mod))
                {
                    RemoveFromSelection(mod);
                    _selectionAnchor = mod;
                }
                else
                {
                    AddToSelection(mod);
                    _selectionAnchor = mod;
                }

                return;
            }

            ClearSelection();
            AddToSelection(mod);
            _selectionAnchor = mod;
        }

    private void SelectAllModsInCurrentView()
        {
            if (_isApplyingPreset) return;

            var mods = GetModsInViewOrder();
            ClearSelection(true);

            if (mods.Count == 0) return;

            foreach (var mod in mods) AddToSelection(mod);

            _selectionAnchor = mods[mods.Count - 1];
        }

    private bool ApplyRangeSelection(ModListItemViewModel start, ModListItemViewModel end, bool preserveExisting)
        {
            var mods = GetModsInViewOrder();
            var startIndex = mods.IndexOf(start);
            var endIndex = mods.IndexOf(end);

            if (startIndex < 0 || endIndex < 0)
            {
                if (!preserveExisting) ClearSelection();

                AddToSelection(end);
                return false;
            }

            if (!preserveExisting) ClearSelection();

            if (startIndex > endIndex) (startIndex, endIndex) = (endIndex, startIndex);

            for (var i = startIndex; i <= endIndex; i++) AddToSelection(mods[i]);

            return true;
        }

    private List<ModListItemViewModel> GetModsInViewOrder()
        {
            var view = _viewModel?.CurrentModsView;
            if (view == null) return new List<ModListItemViewModel>();

            return view.Cast<ModListItemViewModel>().ToList();
        }

    private void AddToSelection(ModListItemViewModel mod)
        {
            if (_selectedMods.Contains(mod)) return;

            _selectedMods.Add(mod);
            SubscribeToSelectedMod(mod);
            mod.IsSelected = true;
            UpdateSelectedModButtons();
        }

    private void RemoveFromSelection(ModListItemViewModel mod)
        {
            if (!_selectedMods.Remove(mod)) return;

            mod.IsSelected = false;
            UnsubscribeFromSelectedMod(mod);
            UpdateSelectedModButtons();
        }

    private void ClearSelection(bool resetAnchor = false)
        {
            if (_selectedMods.Count > 0)
            {
                foreach (var mod in _selectedMods)
                {
                    mod.IsSelected = false;
                    UnsubscribeFromSelectedMod(mod);
                }

                _selectedMods.Clear();
            }

            if (resetAnchor) _selectionAnchor = null;

            UpdateSelectedModButtons();
        }

    private void ClearModDatabaseSelections()
        {
            if (_selectedMods.Count > 0)
            {
                var removedAny = false;

                for (var i = _selectedMods.Count - 1; i >= 0; i--)
                {
                    var mod = _selectedMods[i];
                    if (!mod.IsModDatabaseEntry) continue;

                    _selectedMods.RemoveAt(i);
                    mod.IsSelected = false;
                    UnsubscribeFromSelectedMod(mod);
                    removedAny = true;
                }

                if (removedAny)
                {
                    if (_selectionAnchor is { } anchor && anchor.IsModDatabaseEntry) _selectionAnchor = null;
                    UpdateSelectedModButtons();
                }
            }
        }

    private void RestoreSelectionFromSourcePaths(IReadOnlyList<string> sourcePaths, string? anchorSourcePath)
        {
            if (_viewModel is null) return;

            var resolved = new List<ModListItemViewModel>(sourcePaths.Count);
            foreach (var path in sourcePaths)
            {
                if (string.IsNullOrWhiteSpace(path)) continue;

                var current = _viewModel.FindModBySourcePath(path);
                if (current != null && !resolved.Contains(current)) resolved.Add(current);
            }

            var selectionChanged = resolved.Count != _selectedMods.Count;
            if (!selectionChanged)
                for (var i = 0; i < resolved.Count; i++)
                    if (!ReferenceEquals(resolved[i], _selectedMods[i]))
                    {
                        selectionChanged = true;
                        break;
                    }

            if (!selectionChanged)
            {
                UpdateSelectionAnchorAfterRestore(resolved, anchorSourcePath);
                return;
            }

            foreach (var mod in _selectedMods)
            {
                mod.IsSelected = false;
                UnsubscribeFromSelectedMod(mod);
            }

            _selectedMods.Clear();

            foreach (var mod in resolved)
            {
                _selectedMods.Add(mod);
                mod.IsSelected = true;
                SubscribeToSelectedMod(mod);
            }

            UpdateSelectionAnchorAfterRestore(resolved, anchorSourcePath);
            UpdateSelectedModButtons();
        }

    private void UpdateSelectionAnchorAfterRestore(IReadOnlyList<ModListItemViewModel> selection,
            string? anchorSourcePath)
        {
            if (selection.Count == 0)
            {
                _selectionAnchor = null;
                return;
            }

            if (!string.IsNullOrWhiteSpace(anchorSourcePath))
                foreach (var mod in selection)
                    if (string.Equals(mod.SourcePath, anchorSourcePath, StringComparison.OrdinalIgnoreCase))
                    {
                        _selectionAnchor = mod;
                        return;
                    }

            _selectionAnchor = selection[selection.Count - 1];
        }

    private void SubscribeToSelectedMod(ModListItemViewModel mod)
        {
            if (_selectedModPropertyHandlers.ContainsKey(mod)) return;

            PropertyChangedEventHandler handler = (_, args) =>
            {
                var shouldRefreshFixButton = string.IsNullOrEmpty(args.PropertyName)
                                             || args.PropertyName == nameof(ModListItemViewModel.CanFixDependencyIssues)
                                             || args.PropertyName == nameof(ModListItemViewModel.HasDependencyIssues)
                                             || args.PropertyName == nameof(ModListItemViewModel.MissingDependencies)
                                             || args.PropertyName == nameof(ModListItemViewModel.DependencyHasErrors);

                var shouldRefreshCopyButton = string.IsNullOrEmpty(args.PropertyName)
                                              || args.PropertyName == nameof(ModListItemViewModel.Version);

                if (!shouldRefreshFixButton && !shouldRefreshCopyButton) return;

                void RefreshButtons()
                {
                    if (shouldRefreshFixButton) RefreshSelectedModFixButton(mod);

                    if (shouldRefreshCopyButton) RefreshSelectedModCopyForServerButton(mod);
                }

                if (Dispatcher.CheckAccess())
                    RefreshButtons();
                else
                    Dispatcher.Invoke(RefreshButtons);
            };

            mod.PropertyChanged += handler;
            _selectedModPropertyHandlers[mod] = handler;
        }

    private void UnsubscribeFromSelectedMod(ModListItemViewModel mod)
        {
            if (_selectedModPropertyHandlers.TryGetValue(mod, out var handler))
            {
                mod.PropertyChanged -= handler;
                _selectedModPropertyHandlers.Remove(mod);
            }
        }

    private void RefreshSelectedModFixButton(ModListItemViewModel mod)
        {

            if (_selectedMods.Count == 1 && ReferenceEquals(_selectedMods[0], mod)) UpdateSelectedModFixButton(mod);
        }

    private void RefreshSelectedModCopyForServerButton(ModListItemViewModel mod)
        {

            if (_selectedMods.Count == 1 && ReferenceEquals(_selectedMods[0], mod))
                UpdateSelectedModCopyForServerButton(mod);
        }

    private void UpdateSelectedModButtons()
        {
            var selectionCount = _selectedMods.Count;
            var singleSelection = selectionCount == 1 ? _selectedMods[0] : null;
            var hasMultipleSelection = selectionCount > 1;

            if (hasMultipleSelection)
            {
                UpdateSelectedModButton(SelectedModDatabasePageButton, null, true);
                UpdateSelectedModButton(SelectedModUpdateButton, null, false, true);
                UpdateSelectedModEditConfigButton(null);
                UpdateSelectedModFixButton(null);
                UpdateSelectedModCopyForServerButton(null);

                if (SelectedModDeleteButton is not null)
                {
                    var allowDeletion = true;
                    SelectedModDeleteButton.DataContext = null;
                    SelectedModDeleteButton.Visibility = allowDeletion ? Visibility.Visible : Visibility.Collapsed;
                    SelectedModDeleteButton.IsEnabled = allowDeletion;
                }
            }
            else
            {
                UpdateSelectedModButton(SelectedModDatabasePageButton, singleSelection, true);
                UpdateSelectedModButton(SelectedModUpdateButton, singleSelection, false, true);
                UpdateSelectedModEditConfigButton(singleSelection);
                UpdateSelectedModButton(SelectedModDeleteButton, singleSelection, false);
                UpdateSelectedModFixButton(singleSelection);
                UpdateSelectedModCopyForServerButton(singleSelection);
            }

            _viewModel?.SetSelectedMod(singleSelection, selectionCount);
        }

    private void UpdateServerOptionsState(bool isEnabled)
        {
            if (EnableServerOptionsMenuItem is not null) EnableServerOptionsMenuItem.IsChecked = isEnabled;

            // Control visibility of server-related menu items
            var visibility = isEnabled ? Visibility.Visible : Visibility.Collapsed;
            if (ManageServerTargetsMenuItem is not null) ManageServerTargetsMenuItem.Visibility = visibility;
            if (SyncToServerMenuItem is not null) SyncToServerMenuItem.Visibility = visibility;
            if (ServerOptionsSeparator1 is not null) ServerOptionsSeparator1.Visibility = visibility;
            if (ServerOptionsSeparator2 is not null) ServerOptionsSeparator2.Visibility = visibility;

            var singleSelection = _selectedMods.Count == 1 ? _selectedMods[0] : null;
            UpdateSelectedModCopyForServerButton(isEnabled ? singleSelection : null);
        }

    private void UpdateSelectedModFixButton(ModListItemViewModel? mod)
        {
            if (SelectedModFixButton is null) return;

            if (mod is null || !mod.CanFixDependencyIssues || _isModUpdateInProgress)
            {
                SelectedModFixButton.DataContext = null;
                SelectedModFixButton.Visibility = Visibility.Collapsed;
                SelectedModFixButton.IsEnabled = false;
                return;
            }

            SelectedModFixButton.DataContext = mod;
            SelectedModFixButton.Visibility = Visibility.Visible;
            SelectedModFixButton.IsEnabled = true;
        }

    private void UpdateSelectedModCopyForServerButton(ModListItemViewModel? mod)
        {
            if (SelectedModCopyForServerButton is null) return;

            if (!_userConfiguration.EnableServerOptions || mod is null)
            {
                SelectedModCopyForServerButton.DataContext = null;
                SelectedModCopyForServerButton.Visibility = Visibility.Collapsed;
                SelectedModCopyForServerButton.IsEnabled = false;
                return;
            }

            var command = ServerCommandBuilder.TryBuildInstallCommand(mod.ModId, mod.Version);
            if (string.IsNullOrWhiteSpace(command))
            {
                SelectedModCopyForServerButton.DataContext = null;
                SelectedModCopyForServerButton.Visibility = Visibility.Collapsed;
                SelectedModCopyForServerButton.IsEnabled = false;
                return;
            }

            SelectedModCopyForServerButton.DataContext = mod;
            SelectedModCopyForServerButton.Visibility = Visibility.Visible;
            SelectedModCopyForServerButton.IsEnabled = true;
        }

    private static void UpdateSelectedModButton(WpfButton? button, ModListItemViewModel? mod,
            bool requireModDatabaseLink, bool requireUpdate = false)
        {
            if (button is null) return;

            if (mod is null
                || (requireModDatabaseLink && !mod.HasModDatabasePageLink)
                || (requireUpdate && !mod.CanUpdate))
            {
                button.DataContext = null;
                button.Visibility = Visibility.Collapsed;
                button.IsEnabled = false;
                return;
            }

            button.DataContext = mod;
            button.Visibility = Visibility.Visible;
            button.IsEnabled = true;
        }

    private void UpdateSelectedModEditConfigButton(ModListItemViewModel? mod)
        {
            if (SelectedModEditConfigButton is null) return;

            UpdateSelectedModButton(SelectedModEditConfigButton, mod, false);

            if (SelectedModEditConfigButton.DataContext is not ModListItemViewModel context)
            {
                SelectedModEditConfigButton.ToolTip = null;
                SelectedModEditConfigButton.Content = "Edit Config";
                return;
            }

            var hasConfigPath = !string.IsNullOrWhiteSpace(context.ModId)
                                && _userConfiguration.TryGetModConfigPath(context.ModId, out var path)
                                && !string.IsNullOrWhiteSpace(path);

            SelectedModEditConfigButton.Content = hasConfigPath ? "Edit Config" : "Set Config...";
            SelectedModEditConfigButton.ToolTip = hasConfigPath
                ? $"Edit Config for {context.DisplayName}"
                : $"Set Config for {context.DisplayName}";
        }

    private bool ShouldIgnoreRowSelection(DependencyObject? source)
        {
            while (source != null)
            {
                if (source is ButtonBase or ToggleButton || source is ToggleSwitch) return true;

                if (source is FrameworkElement { TemplatedParent: ToggleSwitch }) return true;

                if (source is DataGridCell cell && ReferenceEquals(cell.Column, ActiveColumn)) return true;

                source = VisualTreeHelper.GetParent(source);
            }

            return false;
        }

    private ScrollViewer? GetModsScrollViewer()
        {

            var targetGrid = ModsDataGrid;

            if (targetGrid == null) return null;

            if (_modsScrollViewer != null && ReferenceEquals(_modsScrollViewerSource, targetGrid)) return _modsScrollViewer;

            _modsScrollViewer = FindDescendantScrollViewer(targetGrid);
            _modsScrollViewerSource = targetGrid;
            return _modsScrollViewer;
        }

    private void ClearScrollViewerCache()
        {
            _modsScrollViewer = null;
            _modsScrollViewerSource = null;
        }

    private static ScrollViewer? FindDescendantScrollViewer(DependencyObject? current)
        {
            if (current is null) return null;

            if (current is ScrollViewer viewer) return viewer;

            var childCount = VisualTreeHelper.GetChildrenCount(current);
            for (var i = 0; i < childCount; i++)
            {
                var result = FindDescendantScrollViewer(VisualTreeHelper.GetChild(current, i));
                if (result != null) return result;
            }

            return null;
        }
}
