// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private Task SaveModlistToCloudAsync()
        {
            return ExecuteCloudOperationAsync(async store =>
            {
                var suggestedName = InstalledModsPdfGenerator.BuildCloudModlistName();
                var configOptions = BuildModConfigOptions(selectByDefault: false);
                var detailsDialog = new CloudModlistDetailsDialog(
                    this,
                    suggestedName,
                    configOptions,
                    _viewModel?.InstalledGameVersion);
                var dialogResult = detailsDialog.ShowDialog();
                if (dialogResult != true) return;

                var uploader = DetermineUploaderName(store);

                var modlistName = detailsDialog.ModlistName;
                var description = detailsDialog.ModlistDescription;
                var version = detailsDialog.ModlistVersion;

                Dictionary<string, IReadOnlyList<ModConfigurationSnapshot>>? includedConfigurations = null;
                var selectedConfigOptions = detailsDialog.GetSelectedConfigOptions();
                includedConfigurations = TryReadModConfigurations(selectedConfigOptions);

                var gameVersion = ResolveGameVersion(detailsDialog.ModlistGameVersion);

                if (!TryBuildCurrentModlistJson(modlistName,
                        description,
                        version,
                        uploader,
                        includedConfigurations,
                        gameVersion,
                        out var json)) return;

                var savePlan =
                    await CloudModlistSaveService.PrepareSaveAsync(
                        store,
                        modlistName);

                var trimmedModlistName = modlistName.Trim();

                CloudModlistSlot? replacementSlot = null;
                string? slotKey = null;

                if (savePlan.MatchingSlot is { } matchingSlot)
                {
                    var slotLabel =
                        CloudModlistHelper.FormatCloudSlotLabel(
                            matchingSlot.SlotKey);

                    var replaceExisting = WpfMessageBox.Show(
                        $"A cloud modlist named \"{trimmedModlistName}\" " +
                        $"already exists in {slotLabel}. Do you want to " +
                        "replace it?",
                        "Simple VS Manager",
                        MessageBoxButton.YesNo,
                        MessageBoxImage.Question);

                    if (replaceExisting != MessageBoxResult.Yes)
                        return;

                    replacementSlot = matchingSlot;
                    slotKey = matchingSlot.SlotKey;
                }

                if (slotKey is null)
                    slotKey = savePlan.FreeSlot?.SlotKey;

                if (slotKey is null)
                {
                    replacementSlot =
                        PromptForCloudSaveReplacement(
                            savePlan.Slots);

                    if (replacementSlot is null)
                        return;

                    slotKey = replacementSlot.SlotKey;
                }

                await CloudModlistSaveService.SaveAsync(
                    store,
                    slotKey,
                    json);

                if (replacementSlot is not null)
                {
                    var replacedName = replacementSlot.Name ?? "existing modlist";
                    var replacedVersion = replacementSlot.Version;
                    if (!string.IsNullOrWhiteSpace(replacedVersion)) replacedName = $"{replacedName} (v{replacedVersion})";

                    _viewModel?.ReportStatus($"Replaced cloud modlist \"{replacedName}\" with \"{modlistName}\".");
                }
                else
                {
                    _viewModel?.ReportStatus($"Saved cloud modlist \"{modlistName}\" to the cloud.");
                }
            }, "save the modlist to the cloud");
        }

    private async void SaveModlistToCloudMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            await SaveModlistToCloudAsync();
            if (_viewModel?.IsViewingModlistTab == true)
                await RefreshCloudModlistsAsync(true);
            else
                _cloudModlistsLoaded = false;
        }

    private async void SaveCloudModlistButton_OnClick(object sender, RoutedEventArgs e)
        {
            await SaveModlistToCloudAsync();
            if (_viewModel?.IsViewingModlistTab == true) await RefreshCloudModlistsAsync(true);
        }

    private async void ModifyCloudModlistsButton_OnClick(object sender, RoutedEventArgs e)
        {
            await ExecuteCloudOperationAsync(async store => { await ShowCloudModlistManagementDialogAsync(store); },
                "manage your cloud modlists");
        }

    private CloudModlistSlot? PromptForCloudSaveReplacement(IReadOnlyList<CloudModlistSlot> slots)
        {
            if (slots is null) return null;

            var occupiedSlots = slots.Where(slot => slot.IsOccupied).ToList();
            if (occupiedSlots.Count == 0) return null;

            var dialog = new CloudSlotSelectionDialog(this,
                occupiedSlots,
                "Replace Cloud Modlist",
                "Select a cloud modlist to replace.");
            var dialogResult = dialog.ShowDialog();
            return dialogResult == true ? dialog.SelectedSlot : null;
        }

    private async Task ShowCloudModlistManagementDialogAsync(FirebaseModlistStore store)
        {
            var entries =
                await CloudModlistManagementService.LoadEntriesAsync(
                    store);
            if (entries.Count == 0)
            {
                WpfMessageBox.Show(
                    "You do not have any cloud modlists saved.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            var dialog = new CloudModlistManagementDialog(
                this,
                entries,
                () => CloudModlistManagementService.LoadEntriesAsync(store),
                (entry, newName) => RenameCloudModlistAsync(store, entry, newName),
                entry => DeleteCloudModlistAsync(store, entry));

            dialog.ShowDialog();
        }

    private async Task<bool> RenameCloudModlistAsync(
            FirebaseModlistStore store,
            CloudModlistManagementEntry entry,
            string newName)
        {
            var result =
                await CloudModlistManagementService.RenameAsync(
                    store,
                    entry,
                    newName);

            switch (result.Status)
            {
                case CloudModlistRenameStatus.InvalidName:
                    return false;

                case CloudModlistRenameStatus.LoadFailed:
                    StatusLogService.AppendStatus(
                        $"Failed to load cloud modlist for rename: " +
                        $"{result.ErrorMessage}",
                        true);

                    WpfMessageBox.Show(
                        $"Failed to load the cloud modlist before renaming:\n" +
                        result.ErrorMessage,
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Error);

                    return false;

                case CloudModlistRenameStatus.ContentUnavailable:
                    WpfMessageBox.Show(
                        "The selected cloud modlist could not be loaded.",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Warning);

                    return false;

                case CloudModlistRenameStatus.InvalidContent:
                    StatusLogService.AppendStatus(
                        $"Failed to update cloud modlist name: " +
                        $"{result.ErrorMessage}",
                        true);

                    WpfMessageBox.Show(
                        $"The cloud modlist data is invalid and could not " +
                        $"be renamed:\n{result.ErrorMessage}",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Error);

                    return false;

                case CloudModlistRenameStatus.SaveFailed:
                    StatusLogService.AppendStatus(
                        $"Failed to rename cloud modlist: " +
                        $"{result.ErrorMessage}",
                        true);

                    WpfMessageBox.Show(
                        $"Failed to rename the cloud modlist:\n" +
                        result.ErrorMessage,
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Error);

                    return false;

                case CloudModlistRenameStatus.Success:
                    break;

                default:
                    throw new InvalidOperationException(
                        "Unexpected cloud modlist rename result.");
            }

            var slotLabel =
                CloudModlistHelper.FormatCloudSlotLabel(
                    entry.SlotKey);

            _viewModel?.ReportStatus(
                $"Renamed cloud modlist in {slotLabel} to " +
                $"\"{result.Name}\".");

            await UpdateCloudModlistsAfterChangeAsync();
            return true;
        }

    private async Task<bool> DeleteCloudModlistAsync(
            FirebaseModlistStore store,
            CloudModlistManagementEntry entry)
        {
            var result =
                await CloudModlistManagementService.DeleteAsync(
                    store,
                    entry);

            switch (result.Status)
            {
                case CloudModlistDeleteStatus.NetworkFailed:
                    StatusLogService.AppendStatus(
                        $"Failed to delete cloud modlist: " +
                        $"{result.ErrorMessage}",
                        true);

                    WpfMessageBox.Show(
                        $"Failed to delete the cloud modlist:\n" +
                        result.ErrorMessage,
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Error);

                    return false;

                case CloudModlistDeleteStatus.InvalidRequest:
                    StatusLogService.AppendStatus(
                        $"Invalid request while deleting cloud modlist: " +
                        $"{result.ErrorMessage}",
                        true);

                    WpfMessageBox.Show(
                        $"Failed to delete the cloud modlist:\n" +
                        result.ErrorMessage,
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Error);

                    return false;

                case CloudModlistDeleteStatus.Success:
                    break;

                default:
                    throw new InvalidOperationException(
                        "Unexpected cloud modlist delete result.");
            }

            var slotLabel =
                CloudModlistHelper.FormatCloudSlotLabel(
                    entry.SlotKey);

            _viewModel?.ReportStatus(
                $"Deleted cloud modlist from {slotLabel}.");

            await UpdateCloudModlistsAfterChangeAsync();
            return true;
        }

    private async Task DeleteAllCloudModlistsAndAuthorizationAsync(FirebaseModlistStore store,
            bool showCompletionMessage = true)
        {
            await CloudModlistManagementService
                .DeleteAllUserDataAndAuthorizationAsync(
                    store,
                    CancellationToken.None);

            DeleteFirebaseAuthFiles();

            _cloudModlistStore = null;
            _cloudModlistsLoaded = false;

            SetCloudModlistSelection(null);
            _viewModel?.ReplaceCloudModlists(null);
            if (CloudModlistsDataGrid is not null) CloudModlistsDataGrid.SelectedItem = null;

            StatusLogService.AppendStatus("Deleted all cloud modlists and Firebase authorization.", false);
            _viewModel?.ReportStatus("Deleted all cloud modlists and Firebase authorization.");

            if (showCompletionMessage)
                WpfMessageBox.Show(
                    this,
                    "Cloud modlists and Firebase authorization have been deleted.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
        }

    private async Task UpdateCloudModlistsAfterChangeAsync()
        {
            if (_viewModel?.IsViewingModlistTab == true)
                await RefreshCloudModlistsAsync(true);
            else
                _cloudModlistsLoaded = false;
        }
}
