// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private Func<ServerTarget, Func<string, HostKeyVerificationResult, Task<bool>>, Func<string, HostKeyVerificationResult, Task<bool>>> CreateHostKeyVerifierWithStorage()
        {
            return (serverTarget, baseVerifier) => async (fingerprint, result) =>
            {
                var trusted = await baseVerifier(fingerprint, result).ConfigureAwait(false);
                if (trusted && result == HostKeyVerificationResult.NewKey && !string.IsNullOrEmpty(serverTarget.Id))
                {
                    _serverTargetService.TryUpdateHostKeyFingerprint(serverTarget.Id, fingerprint, out _);
                }
                return trusted;
            };
        }

    private void GenerateServerInstallMacroMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (_viewModel is null)
            {
                WpfMessageBox.Show(
                    this,
                    "The manager is still initializing. Please try again once the installed mods have finished loading.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            var installedMods = _viewModel.GetInstalledModsSnapshot();
            var installEntries = new List<(string ModId, string Version)>();
            foreach (var mod in installedMods)
            {
                if (mod is null || !mod.IsInstalled) continue;

                if (string.IsNullOrWhiteSpace(mod.ModId) || string.IsNullOrWhiteSpace(mod.Version)) continue;

                installEntries.Add((mod.ModId.Trim(), mod.Version.Trim()));
            }

            if (installEntries.Count == 0)
            {
                WpfMessageBox.Show(
                    this,
                    "No installed mods with a known version were found. Install mods before generating a server macro.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            var macroName = ServerMacroGenerator.CreateDefaultMacroName();
            var saveDialog = new SaveFileDialog
            {
                Title = "Save server macro",
                Filter = "Server macro (*.json)|*.json|All files (*.*)|*.*",
                AddExtension = true,
                DefaultExt = ".json",
                FileName = macroName + ".json"
            };

            try
            {
                var managerDirectory = _userConfiguration.GetConfigurationDirectory();
                if (!string.IsNullOrWhiteSpace(managerDirectory))
                {
                    Directory.CreateDirectory(managerDirectory);
                    saveDialog.InitialDirectory = managerDirectory;
                }
            }
            catch (Exception)
            {
                // Ignore failures when determining the initial directory.
            }

            var result = saveDialog.ShowDialog(this);
            if (result != true) return;

            var targetPath = saveDialog.FileName;
            var description = string.Format(
                CultureInfo.InvariantCulture,
                "Install {0} mods generated by Simple VS Manager on {1:yyyy-MM-dd HH:mm} UTC.",
                installEntries.Count,
                DateTime.UtcNow);

            ServerMacroGenerator.ServerMacroGenerationResult generationResult;
            try
            {
                generationResult = ServerMacroGenerator.CreateInstallMacro(
                    targetPath,
                    macroName,
                    installEntries,
                    description);
            }
            catch (Exception ex) when (ex is IOException
                                       || ex is UnauthorizedAccessException
                                       || ex is ArgumentException
                                       || ex is NotSupportedException
                                       || ex is SecurityException)
            {
                StatusLogService.AppendStatus($"Failed to create server macro: {ex.Message}", true);
                WpfMessageBox.Show(
                    this,
                    $"Failed to create the server macro:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return;
            }

            if (!generationResult.HasMacro)
            {
                WpfMessageBox.Show(
                    this,
                    "Unable to generate server commands for the installed mods.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
                return;
            }

            var command = generationResult.Command;
            var commandCopied = false;
            try
            {
                WinForms.Clipboard.SetText(command);
                commandCopied = true;
            }
            catch (ExternalException)
            {
                // Ignore clipboard errors; the command will still be shown to the user.
            }

            StatusLogService.AppendStatus(
                $"Created server macro '{generationResult.MacroName}' with {generationResult.CommandCount} install commands.",
                false);

            var messageBuilder = new StringBuilder();
            messageBuilder.AppendLine("Saved server macro file:");
            messageBuilder.AppendLine(targetPath);
            messageBuilder.AppendLine();
            messageBuilder.AppendLine(
                string.Format(
                    CultureInfo.InvariantCulture,
                    "Place this file in your server's config directory as servermacros.json (or merge it with your existing macros) and run {0} to install {1} mods.",
                    command,
                    generationResult.CommandCount));

            if (commandCopied)
            {
                messageBuilder.AppendLine();
                messageBuilder.Append("The command was copied to your clipboard.");
            }
            else
            {
                messageBuilder.AppendLine();
                messageBuilder.Append("Copy this command before running it.");
            }

            WpfMessageBox.Show(
                this,
                messageBuilder.ToString(),
                "Simple VS Manager",
                MessageBoxButton.OK,
                MessageBoxImage.Information);
        }

    private void ManageServerTargetsMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            var dialog = new ManageServerTargetsDialog(
                _serverTargetService,
                TestServerConnectionAsync,
                ShowHostKeyVerificationAsync)
            {
                Owner = this
            };
            dialog.ShowDialog();
            UpdateSyncToServerMenuState();
        }

    private void SyncToServerMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (!_userConfiguration.IsActiveProfileServerProfile())
            {
                WpfMessageBox.Show("This feature is only available for Server profiles.\n\nTo use this feature, create a new profile and set its type to 'Server'.",
                    "Sync to Server", MessageBoxButton.OK, MessageBoxImage.Information);
                return;
            }

            var serverTargetId = _userConfiguration.GetActiveServerTargetId();
            if (string.IsNullOrEmpty(serverTargetId))
            {
                WpfMessageBox.Show("No server target is configured for this profile.",
                    "Sync to Server", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            var target = _serverTargetService.GetTarget(serverTargetId);
            if (target == null)
            {
                WpfMessageBox.Show("The configured server target was not found. It may have been deleted.",
                    "Sync to Server", MessageBoxButton.OK, MessageBoxImage.Error);
                return;
            }

            if (string.IsNullOrWhiteSpace(_dataDirectory))
            {
                WpfMessageBox.Show("No data directory is configured for this profile.",
                    "Sync to Server", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            // Wrap the host key verifier to store trusted fingerprints
            var wrappedHostKeyVerifier = CreateHostKeyVerifierWithStorage()(target, ShowHostKeyVerificationAsync);

            var viewModel = new SyncToServerDialogViewModel(
                target,
                _dataDirectory,
                _serverTargetService,
                _syncEngine,
                CreateSftpClientWrapper,
                wrappedHostKeyVerifier,
                new ConfirmationService());

            var dialog = new SyncToServerDialog(viewModel)
            {
                Owner = this
            };
            dialog.ShowDialog();
        }

    private ISftpClientWrapper CreateSftpClientWrapper(
            ServerTarget target,
            string? password,
            Func<string, HostKeyVerificationResult, Task<bool>> hostKeyVerifier)
        {
            return new SftpClientWrapper();
        }

    private async Task<bool> TestServerConnectionAsync(
            ServerTarget target,
            string? password,
            Func<string, HostKeyVerificationResult, Task<bool>> hostKeyVerifier)
        {
            // Wrap the hostKeyVerifier to store fingerprints
            var wrappedVerifier = CreateHostKeyVerifierWithStorage()(target, hostKeyVerifier);
            using var sftp = new SftpClientWrapper();
            await sftp.ConnectAsync(target, password, wrappedVerifier, CancellationToken.None).ConfigureAwait(false);
            return sftp.IsConnected;
        }

    private async Task<bool> ShowHostKeyVerificationAsync(string fingerprint, HostKeyVerificationResult verificationResult)
        {
            // Ensure we're on the UI thread
            if (!Dispatcher.CheckAccess())
            {
                return await Dispatcher.InvokeAsync(async () =>
                    await ShowHostKeyVerificationAsync(fingerprint, verificationResult)).Result.ConfigureAwait(false);
            }

            var target = _serverTargetService.GetAllTargets().FirstOrDefault();
            var host = target?.Host ?? "Unknown host";

            return await HostKeyConfirmationDialog.ShowAsync(this, host, fingerprint, verificationResult).ConfigureAwait(false);
        }

    private void UpdateSyncToServerMenuState()
        {
            var isServerProfile = _userConfiguration.IsActiveProfileServerProfile();
            var hasServerTarget = !string.IsNullOrEmpty(_userConfiguration.GetActiveServerTargetId());
            SyncToServerMenuItem.IsEnabled = isServerProfile && hasServerTarget;
        }

    private void UpdateServerOptionsState(bool isEnabled)
        {
            if (EnableServerOptionsMenuItem is not null) EnableServerOptionsMenuItem.IsChecked = isEnabled;

            // Control visibility of server-related menu items
            var visibility = isEnabled ? Visibility.Visible : Visibility.Collapsed;
            if (ManageServerTargetsMenuItem is not null) ManageServerTargetsMenuItem.Visibility = visibility;
            if (SyncToServerMenuItem is not null) SyncToServerMenuItem.Visibility = visibility;
            if (ServerOptionsSeparator1 is not null) ServerOptionsSeparator1.Visibility = visibility;
            if (ServerOptionsSeparator2 is not null) ServerOptionsSeparator2.Visibility = visibility;

            var singleSelection = _selectedMods.Count == 1 ? _selectedMods[0] : null;
            UpdateSelectedModCopyForServerButton(isEnabled ? singleSelection : null);
        }
}
