// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private async Task UpdateModsAsync(
            IReadOnlyList<ModListItemViewModel> mods,
            bool isBulk,
            IReadOnlyDictionary<ModListItemViewModel, ModReleaseInfo>? releaseOverrides = null,
            bool showSummary = true,
            Func<ModListItemViewModel, ModReleaseInfo, IProgress<ModUpdateProgress>?>? progressFactory = null,
            Action<ModListItemViewModel, ModReleaseInfo, ModUpdateResult>? completionCallback = null)
        {
            if (_viewModel is null || mods.Count == 0)
            {
                await RefreshDeleteCachedModsMenuHeaderAsync();
                return;
            }

            _isModUpdateInProgress = true;
            UpdateSelectedModButtons();

            // Use the modlist install overlay UI for bulk updates when no custom progress factory is provided
            var useModlistInstallUi = isBulk && progressFactory is null;
            if (useModlistInstallUi)
                BeginModlistInstallUi(mods.Count, "Updating mods...");

            try
            {
                var results = new List<ModUpdateOperationResult>();
                ModUpdateReleasePreference? bulkPreference = null;
                var abortRequested = false;
                var requiresRefresh = false;

                foreach (var mod in mods)
                {
                    var displayName = mod.DisplayName ?? mod.ModId ?? "Mod";
                    ModReleaseInfo? overrideRelease = null;
                    var hasOverride = releaseOverrides != null
                                      && releaseOverrides.TryGetValue(mod, out overrideRelease);

                    if (!hasOverride && !mod.CanUpdate) continue;

                    if (!TryGetManagedModPath(mod, out var modPath, out var pathError))
                    {
                        var message = string.IsNullOrWhiteSpace(pathError)
                            ? "The mod location could not be determined."
                            : pathError!;
                        results.Add(ModUpdateOperationResult.Failure(mod, message));
                        requiresRefresh = true;
                        if (completionCallback != null && hasOverride && overrideRelease != null)
                            completionCallback(mod, overrideRelease, new ModUpdateResult(false, message));
                        if (useModlistInstallUi)
                            CompleteModlistInstallStep($"{displayName}: {message}");
                        continue;
                    }

                    var previousResultCount = results.Count;
                    var release = hasOverride
                        ? overrideRelease
                        : SelectReleaseForMod(mod, isBulk, ref bulkPreference, results, ref abortRequested);
                    if (abortRequested)
                    {
                        requiresRefresh = true;
                        break;
                    }

                    if (release is null)
                    {
                        if (results.Count > previousResultCount) requiresRefresh = true;
                        continue;
                    }

                    var targetIsDirectory = Directory.Exists(modPath);

                    if (!targetIsDirectory && !File.Exists(modPath) && mod.SourceKind == ModSourceKind.Folder)
                        targetIsDirectory = true;

                    var targetPath = modPath;
                    string? existingPath = null;

                    if (!targetIsDirectory)
                    {
                        if (!TryGetUpdateTargetPath(mod, release, modPath, out var resolvedPath, out var targetError))
                        {
                            var failureMessage = string.IsNullOrWhiteSpace(targetError)
                                ? "The mod location could not be determined."
                                : targetError!;
                            results.Add(ModUpdateOperationResult.Failure(mod, failureMessage));
                            requiresRefresh = true;
                            completionCallback?.Invoke(mod, release, new ModUpdateResult(false, failureMessage));
                            if (useModlistInstallUi)
                                CompleteModlistInstallStep($"{displayName}: {failureMessage}");
                            continue;
                        }

                        targetPath = resolvedPath;
                        existingPath = modPath;
                    }

                    var descriptor = new ModUpdateDescriptor(
                        mod.ModId ?? displayName,
                        displayName,
                        release.DownloadUri,
                        targetPath,
                        targetIsDirectory,
                        release.FileName,
                        release.Version,
                        mod.Version)
                    {
                        ExistingPath = existingPath
                    };

                    IProgress<ModUpdateProgress>? progress;
                    if (useModlistInstallUi)
                    {
                        progress = CreateModlistInstallProgressReporter(displayName);
                    }
                    else
                    {
                        var additionalProgress = progressFactory?.Invoke(mod, release);
                        progress = CreateModUpdateProgressReporter(displayName, additionalProgress);
                    }

                    var updateResult = await _modUpdateService
                        .UpdateAsync(descriptor, _userConfiguration.CacheAllVersionsLocally, progress)
                        .ConfigureAwait(true);

                    completionCallback?.Invoke(mod, release, updateResult);

                    if (!updateResult.Success)
                    {
                        var failureMessage = string.IsNullOrWhiteSpace(updateResult.ErrorMessage)
                            ? "The update failed."
                            : updateResult.ErrorMessage!;
                        if (useModlistInstallUi)
                            CompleteModlistInstallStep($"{displayName}: {failureMessage}");
                        else
                            _viewModel.ReportStatus($"Failed to update {displayName}: {failureMessage}", true);
                        results.Add(ModUpdateOperationResult.Failure(mod, failureMessage));
                        requiresRefresh = true;
                        continue;
                    }

                    requiresRefresh = true;
                    if (useModlistInstallUi)
                    {
                        CompleteModlistInstallStep($"Updated {displayName} to {release.Version}.");
                        _modActivityLoggingService.LogModUpdate(mod.DisplayName ?? mod.ModId ?? "Unknown", mod.Version, release.Version);
                    }
                    else
                    {
                        _viewModel.ReportStatus($"Updated {displayName} to {release.Version}.");
                        _modActivityLoggingService.LogModUpdate(mod.DisplayName ?? mod.ModId ?? "Unknown", mod.Version, release.Version);
                    }
                    await _viewModel.PreserveActivationStateAsync(mod.ModId ?? string.Empty, mod.Version, release.Version, mod.IsActive)
                        .ConfigureAwait(true);
                    var appliedChangelogEntries =
                        mod.GetChangelogEntriesForUpgrade(release.Version);
                    var changelogSummary = ModChangelogFormatter.BuildChangelogSummary(appliedChangelogEntries);
                    results.Add(
                        ModUpdateOperationResult.SuccessResult(mod, release.Version, mod.Version, changelogSummary));
                }

                if (requiresRefresh && _viewModel.RefreshCommand != null)
                    try
                    {
                        await RefreshModsAsync().ConfigureAwait(true);
                    }
                    catch (Exception ex)
                    {
                        WpfMessageBox.Show(
                            $"The mod list could not be refreshed after updating mods:{Environment.NewLine}{ex.Message}",
                            "Simple VS Manager",
                            MessageBoxButton.OK,
                            MessageBoxImage.Error);
                    }

                if (abortRequested && !useModlistInstallUi)
                    _viewModel.ReportStatus(isBulk ? "Bulk update cancelled." : "Update cancelled.");

                if (results.Count > 0 && showSummary)
                {
                    if (isBulk) ShowBulkUpdateChangelogDialog(results);

                    ShowUpdateSummary(results, isBulk, abortRequested);
                }
                else if (abortRequested && showSummary)
                {
                    WpfMessageBox.Show(isBulk ? "Bulk update cancelled." : "Update cancelled.",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Information);
                }
            }
            finally
            {
                if (useModlistInstallUi)
                    EndModlistInstallUi();
                _isModUpdateInProgress = false;
                UpdateSelectedModButtons();
            }

            await RefreshDeleteCachedModsMenuHeaderAsync();
        }

    private ModReleaseInfo? SelectReleaseForMod(
            ModListItemViewModel mod,
            bool isBulk,
            ref ModUpdateReleasePreference? bulkPreference,
            List<ModUpdateOperationResult> results,
            ref bool abortRequested)
        {
            var latest = mod.LatestRelease;
            if (latest is null)
            {
                results.Add(ModUpdateOperationResult.SkippedResult(mod, "No downloadable release was found."));
                return null;
            }

            if (bulkPreference.HasValue && bulkPreference.Value == ModUpdateReleasePreference.LatestCompatible)
                if (mod.LatestCompatibleRelease != null)
                    return mod.LatestCompatibleRelease;

            // No compatible release is available; fall back to installing the latest release.
            return latest;
        }

    private void ShowBulkUpdateChangelogDialog(IReadOnlyList<ModUpdateOperationResult> results)
        {
            if (results is not { Count: > 0 }) return;

            var items = new List<BulkUpdateChangelogWindow.BulkUpdateChangelogItem>();

            foreach (var result in results)
            {
                if (!result.Success) continue;

                var fromVersion = string.IsNullOrWhiteSpace(result.OldVersion)
                    ? "Unknown"
                    : result.OldVersion!;
                var toVersion = string.IsNullOrWhiteSpace(result.NewVersion)
                    ? "Unknown"
                    : result.NewVersion!;
                var title = $"{result.Mod.DisplayName} ({fromVersion} → {toVersion})";
                var changelog = string.IsNullOrWhiteSpace(result.ChangelogSummary)
                    ? "No changelog entries were provided for this update."
                    : result.ChangelogSummary!;
                items.Add(new BulkUpdateChangelogWindow.BulkUpdateChangelogItem(title, changelog));
            }

            if (items.Count == 0) return;

            var dialog = new BulkUpdateChangelogWindow(items)
            {
                Owner = this
            };

            dialog.ShowDialog();
        }

    private static void ShowUpdateSummary(IReadOnlyList<ModUpdateOperationResult> results, bool isBulk, bool aborted)
        {
            if (results.Count == 0) return;

            var successCount = results.Count(result => result.Success);
            var failureCount = results.Count(result => !result.Success && !result.Skipped);
            var skippedCount = results.Count(result => result.Skipped);

            if (!isBulk && failureCount == 0 && skippedCount == 0) return;

            if (isBulk && failureCount == 0 && skippedCount == 0 && !aborted) return;

            var builder = new StringBuilder();
            builder.AppendLine(isBulk ? "Bulk update completed." : "Update completed.");
            if (aborted) builder.AppendLine("The operation was cancelled.");

            builder.AppendLine($"Updated: {successCount}");

            if (failureCount > 0) builder.AppendLine($"Failed: {failureCount}");

            if (skippedCount > 0) builder.AppendLine($"Skipped: {skippedCount}");

            if (failureCount > 0)
            {
                builder.AppendLine();
                builder.AppendLine("Failures:");
                foreach (var failure in results.Where(result => !result.Success && !result.Skipped))
                    builder.AppendLine($" • {failure.Mod.DisplayName}: {failure.Message}");
            }

            if (skippedCount > 0)
            {
                builder.AppendLine();
                builder.AppendLine("Skipped:");
                foreach (var skipped in results.Where(result => result.Skipped))
                    builder.AppendLine($" • {skipped.Mod.DisplayName}: {skipped.Message}");
            }

            MessageBoxImage icon;
            if (isBulk)
                icon = MessageBoxImage.None;
            else
                icon = failureCount > 0 ? MessageBoxImage.Warning : MessageBoxImage.Information;
            WpfMessageBox.Show(builder.ToString(), "Simple VS Manager", MessageBoxButton.OK, icon);
        }
}
