// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    public void ReportStatus(string message, bool isError = false)
        {
            _viewModel?.ReportStatus(message, isError);
        }

    private void InitializeColumnVisibilityMenu()
        {
            RegisterColumnMenuItem(ActiveColumnMenuItem, InstalledModsColumn.Active);
            RegisterColumnMenuItem(IconColumnMenuItem, InstalledModsColumn.Icon);
            RegisterColumnMenuItem(NameColumnMenuItem, InstalledModsColumn.Name);
            RegisterColumnMenuItem(VersionColumnMenuItem, InstalledModsColumn.Version);
            RegisterColumnMenuItem(LatestVersionColumnMenuItem, InstalledModsColumn.LatestVersion);
            RegisterColumnMenuItem(AuthorsColumnMenuItem, InstalledModsColumn.Authors);
            RegisterColumnMenuItem(TagsColumnMenuItem, InstalledModsColumn.Tags);
            RegisterColumnMenuItem(UserReportsColumnMenuItem, InstalledModsColumn.UserReports);
            RegisterColumnMenuItem(StatusColumnMenuItem, InstalledModsColumn.Status);
            RegisterColumnMenuItem(SideColumnMenuItem, InstalledModsColumn.Side);
        }

    private void RegisterColumnMenuItem(MenuItem? menuItem, InstalledModsColumn column)
        {
            if (menuItem == null) return;

            menuItem.Tag = column;
            if (_userConfiguration.GetInstalledColumnVisibility(column.ToString()) is bool storedVisibility)
                menuItem.IsChecked = storedVisibility;
            _installedColumnVisibilityPreferences[column] = menuItem.IsChecked;
            NotifyViewModelOfInstalledColumnVisibility(column, menuItem.IsChecked);
            ApplyInstalledColumnVisibility(column, menuItem.IsChecked);
            menuItem.Checked += InstalledModsColumnMenuItem_OnChecked;
            menuItem.Unchecked += InstalledModsColumnMenuItem_OnChecked;
        }

    private void InstalledModsColumnMenuItem_OnChecked(object sender, RoutedEventArgs e)
        {
            if (sender is not MenuItem menuItem || menuItem.Tag is not InstalledModsColumn column) return;

            _installedColumnVisibilityPreferences[column] = menuItem.IsChecked;
            _userConfiguration.SetInstalledColumnVisibility(column.ToString(), menuItem.IsChecked);
            NotifyViewModelOfInstalledColumnVisibility(column, menuItem.IsChecked);
            ApplyInstalledColumnVisibility(column, menuItem.IsChecked);
        }

    private void ApplyInstalledColumnVisibility(InstalledModsColumn columnKey, bool isVisible)
        {
            DataGridColumn? column = columnKey switch
            {
                InstalledModsColumn.Active => ActiveColumn,
                InstalledModsColumn.Icon => IconColumn,
                InstalledModsColumn.Name => NameColumn,
                InstalledModsColumn.Version => VersionColumn,
                InstalledModsColumn.LatestVersion => LatestVersionColumn,
                InstalledModsColumn.Authors => AuthorsColumn,
                InstalledModsColumn.Tags => TagsColumn,
                InstalledModsColumn.UserReports => UserReportsColumn,
                InstalledModsColumn.Status => StatusColumn,
                InstalledModsColumn.Side => SideColumn,
                _ => null
            };

            if (column == null) return;

            column.Visibility = isVisible ? Visibility.Visible : Visibility.Collapsed;
        }

    private void NotifyViewModelOfInstalledColumnVisibility(InstalledModsColumn column, bool isVisible)
        {
            _viewModel?.SetInstalledColumnVisibility(column.ToString(), isVisible);
        }

    private void ApplyColumnVisibilityPreferencesToViewModel()
        {
            if (_viewModel is null) return;

            foreach (var pair in _installedColumnVisibilityPreferences)
                NotifyViewModelOfInstalledColumnVisibility(pair.Key, pair.Value);
        }
}
