// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private void CacheAllVersionsMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not MenuItem menuItem) return;

            _userConfiguration.SetCacheAllVersionsLocally(menuItem.IsChecked);
            menuItem.IsChecked = _userConfiguration.CacheAllVersionsLocally;
        }

    private void RequireExactVsVersionMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not MenuItem menuItem) return;

            _userConfiguration.SetRequireExactVsVersionMatch(menuItem.IsChecked);
            menuItem.IsChecked = _userConfiguration.RequireExactVsVersionMatch;
        }

    private async void ExperimentalModDebuggingMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (_viewModel?.SelectedMod is not ModListItemViewModel selectedMod)
            {
                WpfMessageBox.Show(
                    "Please select a mod before using Experimental Mod Debugging.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            var modId = selectedMod.ModId?.Trim() ?? string.Empty;
            if (string.IsNullOrWhiteSpace(modId))
            {
                WpfMessageBox.Show(
                    "The selected mod does not specify a mod ID to search for in the logs.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
                return;
            }

            if (string.IsNullOrWhiteSpace(_dataDirectory))
            {
                WpfMessageBox.Show(
                    "The manager data directory is not available. Please configure the Vintage Story data folder and try again.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
                return;
            }

            var logsDirectory = Path.Combine(_dataDirectory, "Logs");
            if (!Directory.Exists(logsDirectory))
            {
                WpfMessageBox.Show(
                    "No log files were found in the manager's Logs folder.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
                return;
            }

            List<ExperimentalModDebugLogLine> logLines;
            var busyScope = _viewModel?.EnterBusyScope();
            try
            {
                logLines = await Task.Run(() => ModDebugLogParser.CollectExperimentalModDebugLines(logsDirectory, modId))
                    .ConfigureAwait(true);
            }
            finally
            {
                busyScope?.Dispose();
            }

            if (logLines.Count == 0)
                logLines.Add(ExperimentalModDebugLogLine.FromPlainText(
                    $"No log entries referencing '{modId}' were found in client-debug, client-main, server-debug, or server-main logs."));

            var dialog = new ExperimentalModDebugDialog(modId, logLines)
            {
                Owner = this
            };

            _ = dialog.ShowDialog();
        }

    private async void ExperimentalAllModsDebuggingMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (_viewModel is null)
            {
                WpfMessageBox.Show(
                    "The installed mod list is not available. Please wait for the manager to finish loading and try again.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            var installedMods = _viewModel.GetInstalledModsSnapshot();
            var modIdentifiers = new List<InstalledModLogIdentifier>();
            var seenModIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            foreach (var mod in installedMods)
            {
                if (mod is null) continue;

                var modId = mod.ModId;
                if (string.IsNullOrWhiteSpace(modId)) continue;

                var trimmedModId = modId.Trim();
                if (!seenModIds.Add(trimmedModId)) continue;

                var displayName = mod.DisplayName;
                if (!string.IsNullOrWhiteSpace(displayName)) displayName = displayName.Trim();

                var displayLabel = string.IsNullOrWhiteSpace(displayName)
                    ? trimmedModId
                    : $"{displayName} ({trimmedModId})";

                modIdentifiers.Add(new InstalledModLogIdentifier(trimmedModId, displayLabel));
            }

            if (modIdentifiers.Count == 0)
            {
                WpfMessageBox.Show(
                    "No installed mods with a valid mod ID were found to search for in the logs.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            if (string.IsNullOrWhiteSpace(_dataDirectory))
            {
                WpfMessageBox.Show(
                    "The manager data directory is not available. Please configure the Vintage Story data folder and try again.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
                return;
            }

            var logsDirectory = Path.Combine(_dataDirectory, "Logs");
            if (!Directory.Exists(logsDirectory))
            {
                WpfMessageBox.Show(
                    "No log files were found in the manager's Logs folder.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
                return;
            }

            List<ExperimentalModDebugLogLine> logLines;
            var busyScope = _viewModel.EnterBusyScope();
            try
            {
                await Task.Yield();
                logLines = await Task.Run(() => ModDebugLogParser.CollectInstalledModDebugLines(logsDirectory, modIdentifiers))
                    .ConfigureAwait(true);
            }
            finally
            {
                busyScope.Dispose();
            }

            if (logLines.Count == 0)
                logLines.Add(ExperimentalModDebugLogLine.FromPlainText(
                    "No log entries referencing the installed mods were found in client-debug, client-main, server-debug, or server-main logs."));

            var dialog = new ExperimentalModDebugDialog(
                "Log entries referencing installed mods",
                "No log entries referencing installed mods were found.",
                logLines)
            {
                Owner = this
            };

            _ = dialog.ShowDialog();
        }

}
