// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private void UpdateSearchSortingBehavior(bool isSearchingModDatabase)
        {
            if (ModsDataGrid == null) return;

            if (!isSearchingModDatabase) ModsDataGrid.CanUserSortColumns = true;
        }

    private static bool ShouldRefreshAfterDependencyResolution(string? statusMessage)
        {
            return !string.IsNullOrWhiteSpace(statusMessage)
                   && statusMessage.StartsWith("Resolved dependencies for ", StringComparison.Ordinal);
        }

    private async Task RefreshModsAfterDependencyResolutionAsync()
        {
            if (_isDependencyResolutionRefreshPending) return;

            if (_viewModel?.RefreshCommand == null) return;

            _isDependencyResolutionRefreshPending = true;

            try
            {
                await RefreshModsAsync(true).ConfigureAwait(true);
            }
            catch (Exception ex)
            {
                WpfMessageBox.Show(
                    $"The mod list could not be refreshed after resolving dependencies:{Environment.NewLine}{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
            finally
            {
                _isDependencyResolutionRefreshPending = false;
            }
        }

    private void ScheduleRefreshAfterModlistLoadIfReady()
        {
            if (!_refreshAfterModlistLoadPending || _isRefreshingAfterModlistLoad) return;

            var viewModel = _viewModel;
            if (viewModel?.RefreshCommand == null) return;

            if (viewModel.IsLoadingMods || viewModel.IsLoadingModDetails) return;

            _isRefreshingAfterModlistLoad = true;

            Dispatcher.InvokeAsync(async () =>
            {
                try
                {
                    await RefreshModsAsync(true).ConfigureAwait(true);
                }
                catch (Exception ex)
                {
                    WpfMessageBox.Show(
                        $"Failed to refresh mods after loading the modlist:{Environment.NewLine}{ex.Message}",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Error);
                }
                finally
                {
                    _refreshAfterModlistLoadPending = false;
                    _isRefreshingAfterModlistLoad = false;
                }
            }, DispatcherPriority.Background);
        }

    private void RestoreSortPreference()
        {
            var viewModel = _viewModel;
            if (viewModel is null) return;

            var preference = _userConfiguration.GetModListSortPreference();
            var sortMemberPath = preference.SortMemberPath;
            if (!string.IsNullOrWhiteSpace(sortMemberPath))
                ApplyModListSort(sortMemberPath, preference.Direction, false);
            else
                UpdateSortPreferenceFromSelectedOption(false);
        }

    private void ApplyModListSort(string sortMemberPath, ListSortDirection direction, bool persistPreference)
        {
            if (_viewModel is null) return;

            if (string.IsNullOrWhiteSpace(sortMemberPath)) return;

            sortMemberPath = ModSortHelper.NormalizeSortMemberPath(sortMemberPath.Trim());

            var option = FindMatchingSortOption(sortMemberPath, direction);
            if (option is null)
            {
                var sorts = ModSortHelper.BuildSortDescriptions(sortMemberPath, direction);
                var displayName = ModSortHelper.BuildSortDisplayName(sortMemberPath, direction);
                option = new SortOption(displayName, sorts);
            }

            ApplySortOption(option, persistPreference);
        }

    private void ApplySortOption(SortOption option, bool persistPreference)
        {
            if (_viewModel is null) return;

            var changed = !ReferenceEquals(_viewModel.SelectedSortOption, option);
            var previousSuppression = _suppressSortPreferenceSave;
            _suppressSortPreferenceSave = !persistPreference;

            try
            {
                if (changed)
                {
                    _viewModel.SelectedSortOption = option;
                }
                else
                {
                    option.Apply(_viewModel.ModsView);
                    UpdateSortPreferenceFromSelectedOption(persistPreference);
                }
            }
            finally
            {
                _suppressSortPreferenceSave = previousSuppression;
            }
        }

    private SortOption? FindMatchingSortOption(string sortMemberPath, ListSortDirection direction)
        {
            if (_viewModel is null) return null;

            sortMemberPath = ModSortHelper.NormalizeSortMemberPath(sortMemberPath);

            foreach (var option in _viewModel.SortOptions)
                if (ModSortHelper.SortOptionMatches(option, sortMemberPath, direction))
                    return option;

            if (_viewModel.SelectedSortOption != null
                && ModSortHelper.SortOptionMatches(_viewModel.SelectedSortOption, sortMemberPath, direction))
                return _viewModel.SelectedSortOption;

            return null;
        }

    private void UpdateSortPreferenceFromSelectedOption(bool persistPreference)
        {
            if (_viewModel?.SelectedSortOption is not { } option)
            {
                ClearColumnSortIndicators();
                if (persistPreference) _userConfiguration.SetModListSortPreference(null, ListSortDirection.Ascending);

                return;
            }

            if (option.SortDescriptions.Count == 0)
            {
                ClearColumnSortIndicators();
                if (persistPreference) _userConfiguration.SetModListSortPreference(null, ListSortDirection.Ascending);

                return;
            }

            var primary = option.SortDescriptions[0];
            UpdateColumnSortVisuals(primary.Property, primary.Direction);

            if (persistPreference) _userConfiguration.SetModListSortPreference(primary.Property, primary.Direction);
        }

    private void UpdateColumnSortVisuals(string sortMemberPath, ListSortDirection direction)
        {
            if (ModsDataGrid == null) return;

            foreach (var column in ModsDataGrid.Columns)
                if (ModSortHelper.SortMemberMatches(column.SortMemberPath, sortMemberPath))
                    column.SortDirection = direction;
                else
                    column.SortDirection = null;
        }

    private void ClearColumnSortIndicators()
        {
            if (ModsDataGrid == null) return;

            foreach (var column in ModsDataGrid.Columns) column.SortDirection = null;
        }

    private void ModsDataGrid_OnSorting(object sender, DataGridSortingEventArgs e)
        {
            if (_viewModel is null) return;

            var sortMemberPath = e.Column.SortMemberPath;
            if (string.IsNullOrWhiteSpace(sortMemberPath))
            {
                e.Handled = true;
                return;
            }

            e.Handled = true;

            var direction = e.Column.SortDirection == ListSortDirection.Ascending
                ? ListSortDirection.Descending
                : ListSortDirection.Ascending;

            ApplyModListSort(sortMemberPath, direction, true);
        }
}
