// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private async void DeleteCachedModsMenuItem_OnClick(object sender, RoutedEventArgs e)
    {
        var result = WpfMessageBox.Show(
            "This will only delete the managers cached mods to save some disk space, it will not affect your installed mods.",
            "Simple VS Manager",
            MessageBoxButton.YesNo,
            MessageBoxImage.Warning);

        if (result != MessageBoxResult.Yes) return;

        try
        {
            var deletionStatus = ManagerCacheCleanupService.DeleteCachedMods();

            switch (deletionStatus)
            {
                case CachedModsDeletionStatus.DirectoryUnavailable:
                    WpfMessageBox.Show(
                        "Could not determine the cached mods directory.",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Warning);
                    break;

                case CachedModsDeletionStatus.DirectoryNotFound:
                    WpfMessageBox.Show(
                        "No cached mods were found.",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Information);
                    break;

                case CachedModsDeletionStatus.Deleted:
                    WpfMessageBox.Show(
                        "Cached mods deleted successfully.",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Information);
                    break;

                default:
                    throw new ArgumentOutOfRangeException();
            }
        }
        catch (Exception ex)
        {
            WpfMessageBox.Show(
                $"Failed to delete cached mods:\n{ex.Message}",
                "Simple VS Manager",
                MessageBoxButton.OK,
                MessageBoxImage.Error);
        }

        await RefreshDeleteCachedModsMenuHeaderAsync();
    }

    private void ManagerDataFolderMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            var directory = GetManagerDataDirectory();
            if (string.IsNullOrWhiteSpace(directory))
            {
                WpfMessageBox.Show(
                    "The manager data folder is not available on this system.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
                return;
            }

            try
            {
                Directory.CreateDirectory(directory);
            }
            catch (Exception ex)
            {
                WpfMessageBox.Show(
                    $"Failed to open the manager data folder:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return;
            }

            OpenFolder(directory, "manager data");
        }

    private void ManagerModDbPageMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            OpenManagerModDatabasePage();
        }

    private void ChangeManagerFolderMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            var currentFolder = ModCacheLocator.GetManagerDataDirectory();
            if (string.IsNullOrWhiteSpace(currentFolder))
            {
                WpfMessageBox.Show(
                    "Cannot determine the current manager data folder location.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return;
            }

            var dialog = new ChangeManagerFolderDialog(this, currentFolder);
            var dialogResult = dialog.ShowDialog();

            if (dialogResult != true)
                return;

            if (dialog.Result == ChangeManagerFolderDialogResult.Reset)
            {
                HandleResetManagerFolder(currentFolder);
                return;
            }

            if (dialog.Result != ChangeManagerFolderDialogResult.Yes)
                return;

            // Show folder browser dialog
            using var folderDialog = new WinForms.FolderBrowserDialog
            {
                Description = "Select the new location for the \"Simple VS Manager\" folder.\n" +
                              "The folder will be created if it doesn't exist.",
                ShowNewFolderButton = true,
                UseDescriptionForTitle = true
            };

            if (folderDialog.ShowDialog() != WinForms.DialogResult.OK)
                return;

            var newParentFolder = folderDialog.SelectedPath;
            if (string.IsNullOrWhiteSpace(newParentFolder))
                return;

            var newManagerFolder = Path.Combine(newParentFolder, "Simple VS Manager");

            // Check if the destination already exists and is not the current folder
            if (Directory.Exists(newManagerFolder) &&
                !string.Equals(currentFolder, newManagerFolder, StringComparison.OrdinalIgnoreCase))
            {
                var overwriteMessage = $"The folder \"{newManagerFolder}\" already exists.\n\n" +
                                       "Do you want to merge with the existing folder?\n" +
                                       "(Existing files with the same name will be overwritten)";

                var overwriteResult = WpfMessageBox.Show(
                    overwriteMessage,
                    "Folder Already Exists",
                    MessageBoxButton.YesNo,
                    MessageBoxImage.Warning);

                if (overwriteResult != MessageBoxResult.Yes)
                    return;
            }

            // Confirm the move
            var confirmMessage = $"Move manager folder from:\n{currentFolder}\n\nTo:\n{newManagerFolder}\n\n" +
                                 "The application will restart after the move is complete.\n\n" +
                                 "Continue?";

            var confirmResult = WpfMessageBox.Show(
                confirmMessage,
                "Confirm Move",
                MessageBoxButton.YesNo,
                MessageBoxImage.Warning);

            if (confirmResult != MessageBoxResult.Yes)
                return;

            try
            {
                // If moving to the same location, just cancel
                if (string.Equals(currentFolder, newManagerFolder, StringComparison.OrdinalIgnoreCase))
                {
                    WpfMessageBox.Show(
                        "The selected location is the same as the current location.",
                        "Simple VS Manager",
                        MessageBoxButton.OK,
                        MessageBoxImage.Information);
                    return;
                }

                // Create the new folder if it doesn't exist
                Directory.CreateDirectory(newManagerFolder);

                // Move all files and subdirectories
                DirectoryUtility.MoveDirectoryContents(currentFolder, newManagerFolder);

                // Save the new custom folder path
                CustomConfigFolderManager.SetCustomConfigFolder(newManagerFolder);

                // Show success message
                var successMessage = $"Manager folder moved successfully to:\n{newManagerFolder}\n\n" +
                                     "The application will now restart.";

                WpfMessageBox.Show(
                    successMessage,
                    "Move Complete",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);

                // Restart the application
                RestartApplication();
            }
            catch (Exception ex)
            {
                WpfMessageBox.Show(
                    $"Failed to move the manager folder:\n\n{ex.Message}",
                    "Error",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }

    private void HandleResetManagerFolder(string currentFolder)
        {
            // Get the default location
            var defaultFolder = ModCacheLocator.GetDefaultManagerDataDirectory();
            if (string.IsNullOrWhiteSpace(defaultFolder))
            {
                WpfMessageBox.Show(
                    "Cannot determine the default manager data folder location.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return;
            }

            // Check if already at default location
            if (string.Equals(currentFolder, defaultFolder, StringComparison.OrdinalIgnoreCase))
            {
                WpfMessageBox.Show(
                    $"Already using the default manager folder location:\n{defaultFolder}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                return;
            }

            // Confirm reset
            var confirmMessage = $"Reset manager folder to default location?\n\n" +
                                 $"Current location:\n{currentFolder}\n\n" +
                                 $"Default location:\n{defaultFolder}\n\n" +
                                 "The manager will:\n" +
                                 "• Move all configuration files, cached mods, backups, and presets\n" +
                                 "• Update the configuration to use the default location\n" +
                                 "• Require a restart to complete the change\n\n" +
                                 "Note: The Firebase authentication backup (SVSM Backup folder) will remain in its original location.\n\n" +
                                 "Continue?";

            var confirmResult = WpfMessageBox.Show(
                confirmMessage,
                "Reset to Default Location",
                MessageBoxButton.YesNo,
                MessageBoxImage.Question);

            if (confirmResult != MessageBoxResult.Yes)
                return;

            try
            {
                // Check if the destination already exists
                if (Directory.Exists(defaultFolder))
                {
                    var overwriteMessage = $"The default folder \"{defaultFolder}\" already exists.\n\n" +
                                           "Do you want to merge with the existing folder?\n" +
                                           "(Existing files with the same name will be overwritten)";

                    var overwriteResult = WpfMessageBox.Show(
                        overwriteMessage,
                        "Folder Already Exists",
                        MessageBoxButton.YesNo,
                        MessageBoxImage.Warning);

                    if (overwriteResult != MessageBoxResult.Yes)
                        return;
                }

                // Create the default folder if it doesn't exist
                Directory.CreateDirectory(defaultFolder);

                // Move all files and subdirectories
                DirectoryUtility.MoveDirectoryContents(currentFolder, defaultFolder);

                // Clear the custom folder configuration to use the default
                CustomConfigFolderManager.ClearCustomConfigFolder();

                // Show success message
                var successMessage = $"Manager folder reset to default location:\n{defaultFolder}\n\n" +
                                     "The application will now restart.";

                WpfMessageBox.Show(
                    successMessage,
                    "Reset Complete",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);

                // Restart the application
                RestartApplication();
            }
            catch (Exception ex)
            {
                WpfMessageBox.Show(
                    $"Failed to reset the manager folder:\n\n{ex.Message}",
                    "Error",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }

    private static void RestartApplication()
        {
            var currentExecutable = Environment.ProcessPath;
            if (string.IsNullOrWhiteSpace(currentExecutable))
            {
                var mainModule = Process.GetCurrentProcess().MainModule;
                if (mainModule != null)
                {
                    currentExecutable = mainModule.FileName;
                }
            }

            if (!string.IsNullOrWhiteSpace(currentExecutable))
            {
                try
                {
                    Process.Start(currentExecutable);
                    System.Windows.Application.Current.Shutdown();
                }
                catch (Exception)
                {
                    // If restart fails, just close the application
                    System.Windows.Application.Current.Shutdown();
                }
            }
            else
            {
                System.Windows.Application.Current.Shutdown();
            }
        }

    private void ClearAllCachesMenuItem_OnClick(object sender, RoutedEventArgs e)
    {
        const string confirmationMessage =
            "This will delete all cache folders used by Simple VS Manager:\n\n" +
            "• Temp Cache (contains all cache data)\n\n" +
            "Your settings, modlists and installed mods will NOT be affected.\n\n" +
            "This is useful when experiencing problems with the mod database or cached data.\n\n" +
            "Continue?";

        var confirmation = WpfMessageBox.Show(
            this,
            confirmationMessage,
            "Simple VS Manager",
            MessageBoxButton.OKCancel,
            MessageBoxImage.Question);

        if (confirmation != MessageBoxResult.OK) return;

        try
        {
            var clearResult = ManagerCacheCleanupService.ClearAllManagerCacheFolders();

            if (!clearResult.DataDirectoryAvailable)
            {
                WpfMessageBox.Show(
                    this,
                    "Could not locate the Simple VS Manager data directory.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return;
            }

            var messageBuilder = new StringBuilder();

            if (clearResult.DeletedFolders.Count > 0)
            {
                messageBuilder.AppendLine("Successfully deleted the following cache folders:");
                foreach (var folder in clearResult.DeletedFolders)
                    messageBuilder.AppendLine($"• {folder}");
            }
            else if (clearResult.FailedFolders.Count == 0)
            {
                messageBuilder.AppendLine("No cache folders were found to delete.");
            }

            if (clearResult.FailedFolders.Count > 0)
            {
                if (messageBuilder.Length > 0) messageBuilder.AppendLine();

                messageBuilder.AppendLine("Failed to delete the following cache folders:");
                foreach (var error in clearResult.FailedFolders)
                    messageBuilder.AppendLine($"• {error}");
            }

            WpfMessageBox.Show(
                this,
                messageBuilder.ToString(),
                "Simple VS Manager",
                MessageBoxButton.OK,
                clearResult.FailedFolders.Count > 0
                    ? MessageBoxImage.Warning
                    : MessageBoxImage.Information);
        }
        catch (Exception ex)
        {
            WpfMessageBox.Show(
                this,
                $"An error occurred while clearing caches:\n\n{ex.Message}",
                "Simple VS Manager",
                MessageBoxButton.OK,
                MessageBoxImage.Error);
        }
    }

    private void RestoreFirebaseAuthBackupMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            const string confirmationMessage =
                "This will copy the firebase-auth.json file from the SVSM Backup folder " +
                "(AppData/Local/SVSM Backup) into the Simple VS Manager folder and replace the current file.\n\n" +
                "Use this if you lost access to online modlists or votes after moving or deleting files.\n\n" +
                "Continue?";

            var confirmation = WpfMessageBox.Show(
                this,
                confirmationMessage,
                "Simple VS Manager",
                MessageBoxButton.OKCancel,
                MessageBoxImage.Question);

            if (confirmation != MessageBoxResult.OK) return;

            var backupPath = FirebaseAnonymousAuthenticator.GetBackupFilePath();
            if (string.IsNullOrWhiteSpace(backupPath))
            {
                WpfMessageBox.Show(
                    this,
                    "Could not determine the location of the firebase-auth.json backup.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return;
            }

            if (!File.Exists(backupPath))
            {
                WpfMessageBox.Show(
                    this,
                    "No firebase-auth.json backup was found in the SVSM Backup folder.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Warning);
                return;
            }

            var stateFilePath = FirebaseAnonymousAuthenticator.GetStateFilePath();
            if (string.IsNullOrWhiteSpace(stateFilePath))
            {
                WpfMessageBox.Show(
                    this,
                    "Could not determine the Simple VS Manager folder for firebase-auth.json.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return;
            }

            try
            {
                var stateDirectory = Path.GetDirectoryName(stateFilePath);
                if (!string.IsNullOrWhiteSpace(stateDirectory)) Directory.CreateDirectory(stateDirectory);

                File.Copy(backupPath, stateFilePath, true);

                WpfMessageBox.Show(
                    this,
                    "Restored firebase-auth.json from the SVSM Backup folder.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or NotSupportedException
                                           or SecurityException)
            {
                WpfMessageBox.Show(
                    this,
                    $"Failed to restore firebase-auth.json: {ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }

    private async void DeleteAllManagerFilesMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            const string confirmationMessage =
                "This will move every file Simple VS Manager created to the Recycle Bin, including its configuration folder, any ModData backups, cached mods, presets, and Firebase authentication tokens.\n\n" +
                "You can restore them from the Recycle Bin if needed. Continue?";

            var confirmation = WpfMessageBox.Show(
                this,
                confirmationMessage,
                "Simple VS Manager",
                MessageBoxButton.OKCancel,
                MessageBoxImage.Warning);

            if (confirmation != MessageBoxResult.OK) return;

            await ExecuteCloudOperationAsync(
                store => DeleteAllCloudModlistsAndAuthorizationAsync(store, false),
                "delete the Firebase user and cloud data");

            var dataDirectory = _dataDirectory;
            var deletionResult = await Task.Run(() => ManagerDataDeletionService.DeleteAllManagerFiles(dataDirectory)).ConfigureAwait(true);

            if (deletionResult.DeletedPaths.Count == 0 && deletionResult.FailedPaths.Count == 0)
            {
                WpfMessageBox.Show(
                    this,
                    "No Simple VS Manager files were found.",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                SwitchToInstalledModsTab();
                return;
            }

            var builder = new StringBuilder();

            if (deletionResult.DeletedPaths.Count > 0)
            {
                builder.AppendLine("Moved the following locations to the Recycle Bin:");
                foreach (var path in deletionResult.DeletedPaths) builder.AppendLine($"• {path}");
            }

            if (deletionResult.FailedPaths.Count == 0)
            {
                var message = builder.Length > 0
                    ? builder.ToString()
                    : "Finished moving Simple VS Manager files to the Recycle Bin.";

                WpfMessageBox.Show(
                    this,
                    message,
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Information);
                SwitchToInstalledModsTab();
                return;
            }

            if (builder.Length > 0) builder.AppendLine();

            builder.AppendLine(
                "The following locations could not be moved to the Recycle Bin. Please remove them manually:");
            foreach (var path in deletionResult.FailedPaths) builder.AppendLine($"• {path}");

            WpfMessageBox.Show(
                this,
                builder.ToString(),
                "Simple VS Manager",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
            SwitchToInstalledModsTab();
        }

    private void SwitchToInstalledModsTab()
        {
            if (_viewModel?.ShowMainTabCommand?.CanExecute(null) == true)
                _viewModel.ShowMainTabCommand.Execute(null);
        }

    private void PrepareForModlistLoad()
        {
            SwitchToInstalledModsTab();
            ClearSelection(true);
        }

    private void UpdateModlistLoadingUiState()
        {
            var isEnabled = !_isApplyingPreset;

            if (UpdateAllButton != null) UpdateAllButton.IsEnabled = isEnabled;

            if (LaunchGameButton != null) LaunchGameButton.IsEnabled = isEnabled;

            if (PresetsAndModlistsMenuItem != null) PresetsAndModlistsMenuItem.IsEnabled = isEnabled;

            if (ModsDataGrid != null)
            {
                if (isEnabled)
                    ModsDataGrid.ClearValue(IsEnabledProperty);
                else
                    ModsDataGrid.IsEnabled = false;
            }

        }

    private async Task RefreshDeleteCachedModsMenuHeaderAsync()
    {
        if (DeleteCachedModsMenuItem is null) return;

        const string baseHeader = "_Delete Cached Mods";
        var header = baseHeader;

        var cacheSize = await Task.Run(ManagerCacheCleanupService.GetCachedModsSize);
        if (cacheSize is long cacheSizeInBytes)
        {
            var cacheSizeInMegabytes =
                (long)Math.Round(cacheSizeInBytes / (1024d * 1024d), MidpointRounding.AwayFromZero);

            if (cacheSizeInMegabytes < 0) cacheSizeInMegabytes = 0;

            header = string.Format(
                CultureInfo.InvariantCulture,
                "{0} ({1}MB)",
                baseHeader,
                cacheSizeInMegabytes);
        }

        DeleteCachedModsMenuItem.Header = header;
    }

    private static string? GetManagerDataDirectory()
        {
            return ModCacheLocator.GetManagerDataDirectory();
        }

    private async Task RefreshModsWithErrorHandlingAsync()
        {
            if (_viewModel == null) return;

            if (Dispatcher.CheckAccess())
                await Dispatcher.Yield(DispatcherPriority.Background);
            else
                await Task.Yield();

            if (_userConfiguration.DisableAutoRefresh)
                _viewModel.EnableUserReportFetching(true);

            try
            {
                RefreshModDetailsOnly();
            }
            catch (Exception ex)
            {
                WpfMessageBox.Show(
                    $"Failed to refresh mod details:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }

}
