// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private void SavePresetMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            var presetDirectory = EnsurePresetDirectory();
            TrySaveSnapshot(
                presetDirectory,
                "Save Mod Preset",
                "Preset files (*.json)|*.json|All files (*.*)|*.*",
                "Presets must be saved inside the Presets folder.",
                "Preset",
                () => _userConfiguration.GetLastSelectedPresetName(),
                name =>
                {
                    _userConfiguration.SetLastSelectedPresetName(name);
                    _viewModel?.ReportStatus($"Saved preset \"{name}\".");
                },
                "preset",
                false,
                false);
        }

    private bool TrySaveModlist()
        {
            return TrySaveModlist(null, out _);
        }

    private bool TrySaveModlist(Func<string?>? suggestedNameProvider, out string? savedFilePath)
        {
            savedFilePath = null;

            var configOptions = BuildModConfigOptions();
            var suggestedName = suggestedNameProvider?.Invoke();

            var metadataDialog = new SaveInstalledModsDialog(
                suggestedName,
                configOptions,
                GetUploaderNameForPdf(),
                defaultVersion: null,
                defaultGameVersion: _viewModel?.InstalledGameVersion,
                SaveInstalledModsDialogResult.SaveJson)
            {
                Owner = this
            };

            var dialogResult = metadataDialog.ShowDialog();
            if (dialogResult != true) return false;

            var listName = metadataDialog.ListName;
            var version = metadataDialog.Version;
            var description = metadataDialog.Description;
            var createdBy = metadataDialog.CreatedBy;
            createdBy = string.IsNullOrWhiteSpace(createdBy)
                ? GetUploaderNameForPdf()
                : createdBy!.Trim();
            var gameVersion = ResolveGameVersion(metadataDialog.VintageStoryVersion);

            var selectedConfigOptions = metadataDialog.GetSelectedConfigOptions();
            var includedConfigurations = TryReadModConfigurations(selectedConfigOptions);

            if (metadataDialog.SelectedAction == SaveInstalledModsDialogResult.SavePdf)
            {
                return TrySaveInstalledModsPdf(
                    listName,
                    version,
                    description,
                    createdBy,
                    includedConfigurations,
                    gameVersion);
            }

            try
            {
                var modListDirectory = EnsureModListDirectory();
                var suggestedEntryName = !string.IsNullOrWhiteSpace(listName)
                    ? listName
                    : suggestedName;
                var entryName = FileNameHelper.BuildSuggestedFileName(suggestedEntryName, "Modlist");
                var filePath = Path.Combine(modListDirectory, entryName + ".json");

                if (File.Exists(filePath))
                {
                    var message =
                        $"A modlist named \"{Path.GetFileName(filePath)}\" already exists in the Modlists folder. Do you want to replace it?";
                    var confirmation = WpfMessageBox.Show(
                        this,
                        message,
                        "Replace Modlist",
                        MessageBoxButton.YesNo,
                        MessageBoxImage.Question);

                    if (confirmation != MessageBoxResult.Yes) return false;
                }

                var serializable = PresetSnapshotBuilder.BuildSerializablePreset(
                    _viewModel!.GetCurrentModStates(),
                    entryName,
                    true,
                    true,
                    includedConfigurations,
                    gameVersion);
                if (!string.IsNullOrWhiteSpace(listName)) serializable.Name = listName.Trim();
                serializable.Description = description;
                serializable.Version = version;
                serializable.Uploader = string.IsNullOrWhiteSpace(createdBy)
                    ? null
                    : createdBy.Trim();

                var json =
                    PdfModlistSerializer.SerializeToJson(serializable);
                File.WriteAllText(filePath, json);

                _viewModel?.ReportStatus($"Saved modlist \"{entryName}\".");
                savedFilePath = filePath;
                return true;
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or NotSupportedException
                                          or PathTooLongException)
            {
                WpfMessageBox.Show($"Failed to save the modlist:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                return false;
            }
        }

    private bool TrySaveAutomaticModlist(string requestedName, out string savedName, out string filePath)
        {
            savedName = string.Empty;
            filePath = string.Empty;

            if (_viewModel is null) return false;

            var modListDirectory = EnsureRebuiltModListDirectory();
            savedName = FileNameHelper.BuildSuggestedFileName(requestedName, "Modlist");
            filePath = Path.Combine(modListDirectory, savedName + ".json");

            var serializable = PresetSnapshotBuilder.BuildSerializablePreset(
                _viewModel!.GetCurrentModStates(),
                savedName,
                true,
                true,
                gameVersion: ResolveGameVersion(null));

            try
            {
                var json =
                    PdfModlistSerializer.SerializeToJson(serializable);
                File.WriteAllText(filePath, json);

                _viewModel.ReportStatus($"Saved modlist \"{savedName}\".");
                return true;
            }
            catch (Exception ex) when (ex is IOException or UnauthorizedAccessException)
            {
                WpfMessageBox.Show($"Failed to save the modlist:\n{ex.Message}",
                    "Simple VS Manager",
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
                savedName = string.Empty;
                filePath = string.Empty;
                return false;
            }
        }

    private ModlistLoadMode? PromptModlistLoadMode()
        {
            var behavior = _userConfiguration.ModlistAutoLoadBehavior;
            switch (behavior)
            {
                case ModlistAutoLoadBehavior.Replace:
                    return ModlistLoadMode.Replace;
                case ModlistAutoLoadBehavior.Add:
                    return ModlistLoadMode.Add;
            }

            var buttonOverrides = new MessageDialogButtonContentOverrides
            {
                Yes = "Only Modlist mods",
                No = "Add Modlist mods"
            };

            var result = WpfMessageBox.Show(
                this,
                "How would you like to load the modlist?" +
                "\n\nOnly Modlist mods: Delete your current mods and install only the mods from the modlist." +
                "\nAdd Modlist mods: Keep your current mods and add any missing mods from the modlist." +
                "\nCancel: Do nothing.",
                "Load Modlist",
                MessageBoxButton.YesNoCancel,
                MessageBoxImage.Question,
                buttonContentOverrides: buttonOverrides);

            return result switch
            {
                MessageBoxResult.Yes => ModlistLoadMode.Replace,
                MessageBoxResult.No => ModlistLoadMode.Add,
                _ => null
            };
        }

    private PresetLoadOptions GetModlistLoadOptions(ModlistLoadMode mode)
        {
            if (mode == ModlistLoadMode.Replace) return ModListLoadOptions;

            return new PresetLoadOptions(ModListLoadOptions.ApplyModStatus, ModListLoadOptions.ApplyModVersions, false);
        }

    private bool EnsureModlistBackupBeforeLoad()
        {
            MessageBoxResult prompt;
            if (_userConfiguration.SuppressModlistSavePrompt)
            {
                prompt = MessageBoxResult.No;
            }
            else
            {
                var suppressButton = new MessageDialogExtraButton(
                    "No, don't ask again",
                    MessageBoxResult.No,
                    () => _userConfiguration.SetSuppressModlistSavePrompt(true));

                prompt = WpfMessageBox.Show(
                    "Would you like to backup your current mods as a Modlist before loading the selected Modlist? Your current mods will be deleted! ",
                    "Simple VS Manager",
                    MessageBoxButton.YesNoCancel,
                    MessageBoxImage.Question,
                    suppressButton);
            }

            if (prompt == MessageBoxResult.Cancel) return false;

            if (prompt == MessageBoxResult.Yes)
            {
                var result = TrySaveModlist(null, out var savedFilePath);
                if (result)
                {
                    if (!string.IsNullOrWhiteSpace(savedFilePath))
                        RefreshLocalModlists(true, new[] { savedFilePath });
                    else
                        RefreshLocalModlists(true);
                }

                return result;
            }

            return true;
        }

    private bool TryBuildCurrentModlistJson(
            string modlistName,
            string? description,
            string? version,
            string uploader,
            IReadOnlyDictionary<string, IReadOnlyList<ModConfigurationSnapshot>>? includedConfigurations,
            string? gameVersion,
            out string json)
        {
            json = string.Empty;

            var trimmedName = string.IsNullOrWhiteSpace(modlistName) ? null : modlistName.Trim();
            if (string.IsNullOrEmpty(trimmedName) || _viewModel is null) return false;

            var serializable = PresetSnapshotBuilder.BuildModlistPreset(
                _viewModel!.GetCurrentModStates(),
                trimmedName,
                description,
                version,
                uploader,
                includedConfigurations,
                gameVersion);

            json =
                PdfModlistSerializer.SerializeToJson(serializable);
            return true;
        }

    private Task CreateAutomaticBackupAsync(string trigger)
        {
            return CreateBackupAsync(
                trigger,
                "Backup",
                true,
                false);
        }

    private async Task RefreshManagerUpdateLinkAsync()
        {
            if (ManagerUpdateLinkTextBlock is null) return;

            if (InternetAccessManager.IsInternetAccessDisabled)
            {
                ManagerUpdateLinkTextBlock.Visibility = Visibility.Collapsed;
                return;
            }

            var currentVersion = GetManagerInformationalVersion();
            if (string.IsNullOrWhiteSpace(currentVersion))
            {
                ManagerUpdateLinkTextBlock.Visibility = Visibility.Collapsed;
                return;
            }

            try
            {
                // Use relaxed mode for manager updates to allow more flexible compatibility
                var info = await _modDatabaseService
                    .TryLoadDatabaseInfoAsync(ManagerModDatabaseModId, currentVersion, null)
                    .ConfigureAwait(true);

                var hasUpdate = info?.LatestVersion is string latestVersion
                                && VersionStringUtility.IsCandidateVersionNewer(latestVersion, currentVersion);

                ManagerUpdateLinkTextBlock.Visibility = hasUpdate ? Visibility.Visible : Visibility.Collapsed;
            }
            catch (OperationCanceledException)
            {
                throw;
            }
            catch (Exception)
            {
                ManagerUpdateLinkTextBlock.Visibility = Visibility.Collapsed;
            }
        }

    private static string? GetManagerInformationalVersion()
        {
            try
            {
                var assembly = typeof(MainWindow).Assembly;
                if (assembly is null) return null;

                var informationalVersion = assembly
                                               .GetCustomAttribute<AssemblyInformationalVersionAttribute>()?
                                               .InformationalVersion
                                           ?? assembly.GetName().Version?.ToString();

                if (string.IsNullOrWhiteSpace(informationalVersion)) return null;

                var buildMetadataSeparatorIndex = informationalVersion.IndexOf('+');
                if (buildMetadataSeparatorIndex >= 0)
                    informationalVersion = informationalVersion[..buildMetadataSeparatorIndex];

                return informationalVersion.Trim();
            }
            catch (Exception)
            {
                return null;
            }
        }

}
