// <auto-generated-preview>
// This file is a preview generated by SplitPlanPreview.
// It is not part of the application build.
// Source: C:\sc\games\Simple-Mod-Manager-Refactor\VintageStoryModManager\Views\MainWindow.xaml.cs
// Plan: C:\sc\games\Simple-Mod-Manager-Refactor\reports\MainWindow-split-plan.csv
// </auto-generated-preview>
#nullable enable
using CommunityToolkit.Mvvm.Input;
using ModernWpf.Controls;
using QuestPDF;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SimpleVsManager.Cloud;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Navigation;
using System.Windows.Threading;
using UglyToad.PdfPig;
using VintageStoryModManager.Models;
using VintageStoryModManager.Services;
using VintageStoryModManager.Helpers;
using VintageStoryModManager.ViewModels;
using VintageStoryModManager.Views.Dialogs;
using YamlDotNet.Core;
using ButtonBase = System.Windows.Controls.Primitives.ButtonBase;
using ModUserReportChangedEventArgs = VintageStoryModManager.ViewModels.MainViewModel.ModUserReportChangedEventArgs;
using Colors = QuestPDF.Helpers.Colors;
using ComboBox = System.Windows.Controls.ComboBox;
using Cursors = System.Windows.Input.Cursors;
using DataFolderBackupProgress = VintageStoryModManager.Services.DataBackupProgress;
using DataFolderBackupSummary = VintageStoryModManager.Services.DataBackupSummary;
using DataFormats = System.Windows.DataFormats;
using DragDropEffects = System.Windows.DragDropEffects;
using DragEventArgs = System.Windows.DragEventArgs;
using FileRecycleOption = Microsoft.VisualBasic.FileIO.RecycleOption;
using FileSystem = Microsoft.VisualBasic.FileIO.FileSystem;
using FileUIOption = Microsoft.VisualBasic.FileIO.UIOption;
using HorizontalAlignment = System.Windows.HorizontalAlignment;
using KeyEventArgs = System.Windows.Input.KeyEventArgs;
using ListView = System.Windows.Controls.ListView;
using ListViewItem = System.Windows.Controls.ListViewItem;
using MouseEventArgs = System.Windows.Input.MouseEventArgs;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using Point = System.Windows.Point;
using ProgressBar = System.Windows.Controls.ProgressBar;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using ScrollBar = System.Windows.Controls.Primitives.ScrollBar;
using TabControl = System.Windows.Controls.TabControl;
using TextBox = System.Windows.Controls.TextBox;
using TextBoxBase = System.Windows.Controls.Primitives.TextBoxBase;
using VerticalAlignment = System.Windows.VerticalAlignment;
using WinForms = System.Windows.Forms;
using WpfButton = System.Windows.Controls.Button;
using WpfMessageBox = VintageStoryModManager.Services.ModManagerMessageBox;
using WpfToolTip = System.Windows.Controls.ToolTip;

namespace VintageStoryModManager.Views;

public partial class MainWindow
{

    private void ThemeMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            if (sender is not MenuItem menuItem) return;

            if (menuItem.Tag is string themeName)
            {
                if (!_userConfiguration.TryActivateTheme(themeName)) return;

                var selectedPalette = _userConfiguration.GetThemePaletteColors();
                UpdateThemeMenuSelection(_userConfiguration.ColorTheme, themeName);
                App.ApplyTheme(_userConfiguration.ColorTheme, selectedPalette.Count > 0 ? selectedPalette : null);
                return;
            }

            if (menuItem.Tag is not ColorTheme theme) return;

            var currentTheme = _userConfiguration.ColorTheme;
            IReadOnlyDictionary<string, string>? paletteOverride = null;

            if (theme == ColorTheme.SurpriseMe) paletteOverride = GenerateSurprisePalette();

            if (theme == currentTheme && paletteOverride is null)
            {
                UpdateThemeMenuSelection(currentTheme, _userConfiguration.GetCurrentThemeName());
                return;
            }

            UpdateThemeMenuSelection(theme, UserConfigurationService.GetThemeDisplayName(theme));
            _userConfiguration.SetColorTheme(theme, paletteOverride);
            var palette = _userConfiguration.GetThemePaletteColors();
            App.ApplyTheme(theme, palette.Count > 0 ? palette : null);
            ClearScrollViewerCache();
        }

    private void EditThemeMenuItem_OnClick(object sender, RoutedEventArgs e)
        {
            ShowCustomThemeEditor();
        }

    private void UpdateThemeMenuSelection(ColorTheme theme, string? themeName = null)
        {
            if (VintageStoryThemeMenuItem is not null)
                VintageStoryThemeMenuItem.IsChecked = theme == ColorTheme.VintageStory;

            if (DarkThemeMenuItem is not null) DarkThemeMenuItem.IsChecked = theme == ColorTheme.Dark;

            if (LightThemeMenuItem is not null) LightThemeMenuItem.IsChecked = theme == ColorTheme.Light;

            var normalizedName = themeName ?? _userConfiguration.GetCurrentThemeName();
            foreach (var menuItem in _customThemeMenuItems)
            {
                var header = menuItem.Header?.ToString();
                menuItem.IsChecked = theme == ColorTheme.Custom
                                     && !string.IsNullOrWhiteSpace(header)
                                     && string.Equals(header, normalizedName, StringComparison.OrdinalIgnoreCase);
            }
        }

    private static IReadOnlyDictionary<string, string> GenerateSurprisePalette()
        {
            var defaults = UserConfigurationService.GetDefaultThemePalette(ColorTheme.VintageStory);
            var result = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

            foreach (var pair in defaults) result[pair.Key] = GenerateRandomColor(pair.Value);

            return result;
        }

    private static string GenerateRandomColor(string baseColor)
        {
            byte alpha = 0xFF;

            if (!string.IsNullOrWhiteSpace(baseColor) && baseColor.Length == 9)
            {
                var alphaComponent = baseColor.AsSpan(1, 2);
                if (byte.TryParse(alphaComponent, NumberStyles.HexNumber, CultureInfo.InvariantCulture,
                        out var parsedAlpha)) alpha = parsedAlpha;
            }

            Span<byte> rgb = stackalloc byte[3];
            RandomNumberGenerator.Fill(rgb);

            return $"#{alpha:X2}{rgb[0]:X2}{rgb[1]:X2}{rgb[2]:X2}";
        }

    private void RefreshCustomThemeMenuItems()
        {
            if (ThemesMenuItem is null) return;

            foreach (var item in _customThemeMenuItems)
            {
                item.Click -= ThemeMenuItem_OnClick;
                ThemesMenuItem.Items.Remove(item);
            }

            _customThemeMenuItems.Clear();

            var customThemes = _userConfiguration.GetCustomThemeNames();

            if (customThemes.Count == 0)
            {
                if (CustomThemesSeparator is not null)
                    CustomThemesSeparator.Visibility = Visibility.Collapsed;
                return;
            }

            if (CustomThemesSeparator is not null)
                CustomThemesSeparator.Visibility = Visibility.Visible;

            var toggleStyle = TryFindResource("ToggleMenuItemStyle") as Style;

            // Find the separator index
            var separatorIndex = CustomThemesSeparator is not null && ThemesMenuItem.Items.Contains(CustomThemesSeparator)
                ? ThemesMenuItem.Items.IndexOf(CustomThemesSeparator)
                : ThemesMenuItem.Items.Count;

            // Insert custom themes BEFORE the separator
            foreach (var name in customThemes)
            {
                var menuItem = new MenuItem
                {
                    Header = name,
                    Height = 35,
                    IsCheckable = true,
                    Tag = name,
                    Style = toggleStyle
                };

                menuItem.Click += ThemeMenuItem_OnClick;
                _customThemeMenuItems.Add(menuItem);
                ThemesMenuItem.Items.Insert(separatorIndex, menuItem);
                separatorIndex++; // Increment to keep adding before the separator
            }
        }

    private void ShowCustomThemeEditor()
        {
            var currentTheme = _userConfiguration.ColorTheme;
            var currentThemeName = _userConfiguration.GetCurrentThemeName();

            UpdateThemeMenuSelection(currentTheme, currentThemeName);

            var palette = _userConfiguration.GetThemePaletteColors();
            App.ApplyTheme(currentTheme, palette.Count > 0 ? palette : null);
            ClearScrollViewerCache();

            var dialog = new ThemePaletteEditorDialog(_userConfiguration)
            {
                Owner = this
            };

            _ = dialog.ShowDialog();

            RefreshCustomThemeMenuItems();
            UpdateThemeMenuSelection(_userConfiguration.ColorTheme, _userConfiguration.GetCurrentThemeName());
            ClearScrollViewerCache();

        }
}
